// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: attribute.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attribute represents an attribute definition
type Attribute struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeDefinitionId string                 `protobuf:"bytes,2,opt,name=type_definition_id,json=typeDefinitionId,proto3" json:"type_definition_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DataType         string                 `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Required         bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	ValidationRules  string                 `protobuf:"bytes,7,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	Version          int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ArchivedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetTypeDefinitionId() string {
	if x != nil {
		return x.TypeDefinitionId
	}
	return ""
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Attribute) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Attribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Attribute) GetValidationRules() string {
	if x != nil {
		return x.ValidationRules
	}
	return ""
}

func (x *Attribute) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Attribute) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Attribute) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Attribute) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

// AttributeList represents a list of attributes
type AttributeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*Attribute           `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeList) Reset() {
	*x = AttributeList{}
	mi := &file_attribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeList) ProtoMessage() {}

func (x *AttributeList) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeList.ProtoReflect.Descriptor instead.
func (*AttributeList) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeList) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// CreateAttributeRequest represents a request to create an attribute
type CreateAttributeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TypeDefinitionId string                 `protobuf:"bytes,1,opt,name=type_definition_id,json=typeDefinitionId,proto3" json:"type_definition_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DataType         string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Required         bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	ValidationRules  string                 `protobuf:"bytes,6,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAttributeRequest) Reset() {
	*x = CreateAttributeRequest{}
	mi := &file_attribute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeRequest) ProtoMessage() {}

func (x *CreateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAttributeRequest) GetTypeDefinitionId() string {
	if x != nil {
		return x.TypeDefinitionId
	}
	return ""
}

func (x *CreateAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAttributeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAttributeRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *CreateAttributeRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CreateAttributeRequest) GetValidationRules() string {
	if x != nil {
		return x.ValidationRules
	}
	return ""
}

// UpdateAttributeRequest represents a request to update an attribute
type UpdateAttributeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeDefinitionId string                 `protobuf:"bytes,2,opt,name=type_definition_id,json=typeDefinitionId,proto3" json:"type_definition_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DataType         string                 `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Required         bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	ValidationRules  string                 `protobuf:"bytes,7,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	Version          int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateAttributeRequest) Reset() {
	*x = UpdateAttributeRequest{}
	mi := &file_attribute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttributeRequest) ProtoMessage() {}

func (x *UpdateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttributeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAttributeRequest) GetTypeDefinitionId() string {
	if x != nil {
		return x.TypeDefinitionId
	}
	return ""
}

func (x *UpdateAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAttributeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAttributeRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *UpdateAttributeRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *UpdateAttributeRequest) GetValidationRules() string {
	if x != nil {
		return x.ValidationRules
	}
	return ""
}

func (x *UpdateAttributeRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetAttributeRequest represents a request to get an attribute
type GetAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeRequest) Reset() {
	*x = GetAttributeRequest{}
	mi := &file_attribute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeRequest) ProtoMessage() {}

func (x *GetAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ArchiveAttributeRequest represents a request to archive an attribute
type ArchiveAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveAttributeRequest) Reset() {
	*x = ArchiveAttributeRequest{}
	mi := &file_attribute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveAttributeRequest) ProtoMessage() {}

func (x *ArchiveAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveAttributeRequest.ProtoReflect.Descriptor instead.
func (*ArchiveAttributeRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListAttributesRequest represents a request to list attributes
type ListAttributesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LatestVersion    bool                   `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Ids              []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	TypeDefinitionId string                 `protobuf:"bytes,4,opt,name=type_definition_id,json=typeDefinitionId,proto3" json:"type_definition_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListAttributesRequest) Reset() {
	*x = ListAttributesRequest{}
	mi := &file_attribute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesRequest) ProtoMessage() {}

func (x *ListAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{6}
}

func (x *ListAttributesRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListAttributesRequest) GetLatestVersion() bool {
	if x != nil {
		return x.LatestVersion
	}
	return false
}

func (x *ListAttributesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListAttributesRequest) GetTypeDefinitionId() string {
	if x != nil {
		return x.TypeDefinitionId
	}
	return ""
}

// ListAttributesResponse represents a response to list attributes
type ListAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*Attribute           `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesResponse) Reset() {
	*x = ListAttributesResponse{}
	mi := &file_attribute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesResponse) ProtoMessage() {}

func (x *ListAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{7}
}

func (x *ListAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// GetAttributesByTypeDefinitionIDRequest represents a request to get attributes by type definition ID
type GetAttributesByTypeDefinitionIDRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TypeDefinitionId string                 `protobuf:"bytes,1,opt,name=type_definition_id,json=typeDefinitionId,proto3" json:"type_definition_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAttributesByTypeDefinitionIDRequest) Reset() {
	*x = GetAttributesByTypeDefinitionIDRequest{}
	mi := &file_attribute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributesByTypeDefinitionIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributesByTypeDefinitionIDRequest) ProtoMessage() {}

func (x *GetAttributesByTypeDefinitionIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributesByTypeDefinitionIDRequest.ProtoReflect.Descriptor instead.
func (*GetAttributesByTypeDefinitionIDRequest) Descriptor() ([]byte, []int) {
	return file_attribute_proto_rawDescGZIP(), []int{8}
}

func (x *GetAttributesByTypeDefinitionIDRequest) GetTypeDefinitionId() string {
	if x != nil {
		return x.TypeDefinitionId
	}
	return ""
}

var File_attribute_proto protoreflect.FileDescriptor

const file_attribute_proto_rawDesc = "" +
	"\n" +
	"\x0fattribute.proto\x12\tflexitype\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb0\x03\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12type_definition_id\x18\x02 \x01(\tR\x10typeDefinitionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x05 \x01(\tR\bdataType\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12)\n" +
	"\x10validation_rules\x18\a \x01(\tR\x0fvalidationRules\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\varchived_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\"E\n" +
	"\rAttributeList\x124\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x14.flexitype.AttributeR\n" +
	"attributes\"\xe0\x01\n" +
	"\x16CreateAttributeRequest\x12,\n" +
	"\x12type_definition_id\x18\x01 \x01(\tR\x10typeDefinitionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12)\n" +
	"\x10validation_rules\x18\x06 \x01(\tR\x0fvalidationRules\"\x8a\x02\n" +
	"\x16UpdateAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12type_definition_id\x18\x02 \x01(\tR\x10typeDefinitionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x05 \x01(\tR\bdataType\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12)\n" +
	"\x10validation_rules\x18\a \x01(\tR\x0fvalidationRules\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\"%\n" +
	"\x13GetAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17ArchiveAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x01\n" +
	"\x15ListAttributesRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\bR\rlatestVersion\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12,\n" +
	"\x12type_definition_id\x18\x04 \x01(\tR\x10typeDefinitionId\"N\n" +
	"\x16ListAttributesResponse\x124\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x14.flexitype.AttributeR\n" +
	"attributes\"V\n" +
	"&GetAttributesByTypeDefinitionIDRequest\x12,\n" +
	"\x12type_definition_id\x18\x01 \x01(\tR\x10typeDefinitionId2\x93\x04\n" +
	"\x10AttributeService\x12L\n" +
	"\x0fCreateAttribute\x12!.flexitype.CreateAttributeRequest\x1a\x14.flexitype.Attribute\"\x00\x12L\n" +
	"\x0fUpdateAttribute\x12!.flexitype.UpdateAttributeRequest\x1a\x14.flexitype.Attribute\"\x00\x12F\n" +
	"\fGetAttribute\x12\x1e.flexitype.GetAttributeRequest\x1a\x14.flexitype.Attribute\"\x00\x12P\n" +
	"\x10ArchiveAttribute\x12\".flexitype.ArchiveAttributeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12W\n" +
	"\x0eListAttributes\x12 .flexitype.ListAttributesRequest\x1a!.flexitype.ListAttributesResponse\"\x00\x12p\n" +
	"\x1fGetAttributesByTypeDefinitionID\x121.flexitype.GetAttributesByTypeDefinitionIDRequest\x1a\x18.flexitype.AttributeList\"\x00B8Z6github.com/zkrebbekx/flexitype/internal/api/connect/pbb\x06proto3"

var (
	file_attribute_proto_rawDescOnce sync.Once
	file_attribute_proto_rawDescData []byte
)

func file_attribute_proto_rawDescGZIP() []byte {
	file_attribute_proto_rawDescOnce.Do(func() {
		file_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attribute_proto_rawDesc), len(file_attribute_proto_rawDesc)))
	})
	return file_attribute_proto_rawDescData
}

var file_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_attribute_proto_goTypes = []any{
	(*Attribute)(nil),                              // 0: flexitype.Attribute
	(*AttributeList)(nil),                          // 1: flexitype.AttributeList
	(*CreateAttributeRequest)(nil),                 // 2: flexitype.CreateAttributeRequest
	(*UpdateAttributeRequest)(nil),                 // 3: flexitype.UpdateAttributeRequest
	(*GetAttributeRequest)(nil),                    // 4: flexitype.GetAttributeRequest
	(*ArchiveAttributeRequest)(nil),                // 5: flexitype.ArchiveAttributeRequest
	(*ListAttributesRequest)(nil),                  // 6: flexitype.ListAttributesRequest
	(*ListAttributesResponse)(nil),                 // 7: flexitype.ListAttributesResponse
	(*GetAttributesByTypeDefinitionIDRequest)(nil), // 8: flexitype.GetAttributesByTypeDefinitionIDRequest
	(*timestamppb.Timestamp)(nil),                  // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                          // 10: google.protobuf.Empty
}
var file_attribute_proto_depIdxs = []int32{
	9,  // 0: flexitype.Attribute.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: flexitype.Attribute.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: flexitype.Attribute.archived_at:type_name -> google.protobuf.Timestamp
	0,  // 3: flexitype.AttributeList.attributes:type_name -> flexitype.Attribute
	0,  // 4: flexitype.ListAttributesResponse.attributes:type_name -> flexitype.Attribute
	2,  // 5: flexitype.AttributeService.CreateAttribute:input_type -> flexitype.CreateAttributeRequest
	3,  // 6: flexitype.AttributeService.UpdateAttribute:input_type -> flexitype.UpdateAttributeRequest
	4,  // 7: flexitype.AttributeService.GetAttribute:input_type -> flexitype.GetAttributeRequest
	5,  // 8: flexitype.AttributeService.ArchiveAttribute:input_type -> flexitype.ArchiveAttributeRequest
	6,  // 9: flexitype.AttributeService.ListAttributes:input_type -> flexitype.ListAttributesRequest
	8,  // 10: flexitype.AttributeService.GetAttributesByTypeDefinitionID:input_type -> flexitype.GetAttributesByTypeDefinitionIDRequest
	0,  // 11: flexitype.AttributeService.CreateAttribute:output_type -> flexitype.Attribute
	0,  // 12: flexitype.AttributeService.UpdateAttribute:output_type -> flexitype.Attribute
	0,  // 13: flexitype.AttributeService.GetAttribute:output_type -> flexitype.Attribute
	10, // 14: flexitype.AttributeService.ArchiveAttribute:output_type -> google.protobuf.Empty
	7,  // 15: flexitype.AttributeService.ListAttributes:output_type -> flexitype.ListAttributesResponse
	1,  // 16: flexitype.AttributeService.GetAttributesByTypeDefinitionID:output_type -> flexitype.AttributeList
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_attribute_proto_init() }
func file_attribute_proto_init() {
	if File_attribute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attribute_proto_rawDesc), len(file_attribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attribute_proto_goTypes,
		DependencyIndexes: file_attribute_proto_depIdxs,
		MessageInfos:      file_attribute_proto_msgTypes,
	}.Build()
	File_attribute_proto = out.File
	file_attribute_proto_goTypes = nil
	file_attribute_proto_depIdxs = nil
}
