// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: attribute_value_dependency.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attribute Value Dependency
type AttributeValueDependency struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceAttributeId string                 `protobuf:"bytes,2,opt,name=source_attribute_id,json=sourceAttributeId,proto3" json:"source_attribute_id,omitempty"`
	TargetAttributeId string                 `protobuf:"bytes,3,opt,name=target_attribute_id,json=targetAttributeId,proto3" json:"target_attribute_id,omitempty"`
	DependencyType    string                 `protobuf:"bytes,4,opt,name=dependency_type,json=dependencyType,proto3" json:"dependency_type,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Version           int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ArchivedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributeValueDependency) Reset() {
	*x = AttributeValueDependency{}
	mi := &file_attribute_value_dependency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueDependency) ProtoMessage() {}

func (x *AttributeValueDependency) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueDependency.ProtoReflect.Descriptor instead.
func (*AttributeValueDependency) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeValueDependency) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeValueDependency) GetSourceAttributeId() string {
	if x != nil {
		return x.SourceAttributeId
	}
	return ""
}

func (x *AttributeValueDependency) GetTargetAttributeId() string {
	if x != nil {
		return x.TargetAttributeId
	}
	return ""
}

func (x *AttributeValueDependency) GetDependencyType() string {
	if x != nil {
		return x.DependencyType
	}
	return ""
}

func (x *AttributeValueDependency) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttributeValueDependency) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AttributeValueDependency) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AttributeValueDependency) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AttributeValueDependency) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

// AttributeValueDependencyList represents a list of attribute value dependencies
type AttributeValueDependencyList struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Dependencies  []*AttributeValueDependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValueDependencyList) Reset() {
	*x = AttributeValueDependencyList{}
	mi := &file_attribute_value_dependency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueDependencyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueDependencyList) ProtoMessage() {}

func (x *AttributeValueDependencyList) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueDependencyList.ProtoReflect.Descriptor instead.
func (*AttributeValueDependencyList) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeValueDependencyList) GetDependencies() []*AttributeValueDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

// CreateAttributeValueDependencyRequest represents a request to create a dependency
type CreateAttributeValueDependencyRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	SourceAttributeDefinitionId string                 `protobuf:"bytes,1,opt,name=source_attribute_definition_id,json=sourceAttributeDefinitionId,proto3" json:"source_attribute_definition_id,omitempty"`
	TargetAttributeDefinitionId string                 `protobuf:"bytes,2,opt,name=target_attribute_definition_id,json=targetAttributeDefinitionId,proto3" json:"target_attribute_definition_id,omitempty"`
	SourceConditions            string                 `protobuf:"bytes,3,opt,name=source_conditions,json=sourceConditions,proto3" json:"source_conditions,omitempty"`
	TargetValues                string                 `protobuf:"bytes,4,opt,name=target_values,json=targetValues,proto3" json:"target_values,omitempty"`
	ValidationRules             string                 `protobuf:"bytes,5,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateAttributeValueDependencyRequest) Reset() {
	*x = CreateAttributeValueDependencyRequest{}
	mi := &file_attribute_value_dependency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeValueDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeValueDependencyRequest) ProtoMessage() {}

func (x *CreateAttributeValueDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeValueDependencyRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeValueDependencyRequest) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAttributeValueDependencyRequest) GetSourceAttributeDefinitionId() string {
	if x != nil {
		return x.SourceAttributeDefinitionId
	}
	return ""
}

func (x *CreateAttributeValueDependencyRequest) GetTargetAttributeDefinitionId() string {
	if x != nil {
		return x.TargetAttributeDefinitionId
	}
	return ""
}

func (x *CreateAttributeValueDependencyRequest) GetSourceConditions() string {
	if x != nil {
		return x.SourceConditions
	}
	return ""
}

func (x *CreateAttributeValueDependencyRequest) GetTargetValues() string {
	if x != nil {
		return x.TargetValues
	}
	return ""
}

func (x *CreateAttributeValueDependencyRequest) GetValidationRules() string {
	if x != nil {
		return x.ValidationRules
	}
	return ""
}

// UpdateAttributeValueDependencyRequest represents a request to update a dependency
type UpdateAttributeValueDependencyRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceAttributeDefinitionId string                 `protobuf:"bytes,2,opt,name=source_attribute_definition_id,json=sourceAttributeDefinitionId,proto3" json:"source_attribute_definition_id,omitempty"`
	TargetAttributeDefinitionId string                 `protobuf:"bytes,3,opt,name=target_attribute_definition_id,json=targetAttributeDefinitionId,proto3" json:"target_attribute_definition_id,omitempty"`
	SourceConditions            string                 `protobuf:"bytes,4,opt,name=source_conditions,json=sourceConditions,proto3" json:"source_conditions,omitempty"`
	TargetValues                string                 `protobuf:"bytes,5,opt,name=target_values,json=targetValues,proto3" json:"target_values,omitempty"`
	ValidationRules             string                 `protobuf:"bytes,6,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	Version                     int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateAttributeValueDependencyRequest) Reset() {
	*x = UpdateAttributeValueDependencyRequest{}
	mi := &file_attribute_value_dependency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttributeValueDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttributeValueDependencyRequest) ProtoMessage() {}

func (x *UpdateAttributeValueDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttributeValueDependencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttributeValueDependencyRequest) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAttributeValueDependencyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAttributeValueDependencyRequest) GetSourceAttributeDefinitionId() string {
	if x != nil {
		return x.SourceAttributeDefinitionId
	}
	return ""
}

func (x *UpdateAttributeValueDependencyRequest) GetTargetAttributeDefinitionId() string {
	if x != nil {
		return x.TargetAttributeDefinitionId
	}
	return ""
}

func (x *UpdateAttributeValueDependencyRequest) GetSourceConditions() string {
	if x != nil {
		return x.SourceConditions
	}
	return ""
}

func (x *UpdateAttributeValueDependencyRequest) GetTargetValues() string {
	if x != nil {
		return x.TargetValues
	}
	return ""
}

func (x *UpdateAttributeValueDependencyRequest) GetValidationRules() string {
	if x != nil {
		return x.ValidationRules
	}
	return ""
}

func (x *UpdateAttributeValueDependencyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Request/Response messages for Attribute Value Dependency
type GetAttributeValueDependencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeValueDependencyRequest) Reset() {
	*x = GetAttributeValueDependencyRequest{}
	mi := &file_attribute_value_dependency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeValueDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeValueDependencyRequest) ProtoMessage() {}

func (x *GetAttributeValueDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeValueDependencyRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeValueDependencyRequest) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttributeValueDependencyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArchiveAttributeValueDependencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveAttributeValueDependencyRequest) Reset() {
	*x = ArchiveAttributeValueDependencyRequest{}
	mi := &file_attribute_value_dependency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveAttributeValueDependencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveAttributeValueDependencyRequest) ProtoMessage() {}

func (x *ArchiveAttributeValueDependencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveAttributeValueDependencyRequest.ProtoReflect.Descriptor instead.
func (*ArchiveAttributeValueDependencyRequest) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveAttributeValueDependencyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAttributeValueDependenciesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LatestVersion     bool                   `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Ids               []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	SourceAttributeId string                 `protobuf:"bytes,4,opt,name=source_attribute_id,json=sourceAttributeId,proto3" json:"source_attribute_id,omitempty"`
	TargetAttributeId string                 `protobuf:"bytes,5,opt,name=target_attribute_id,json=targetAttributeId,proto3" json:"target_attribute_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListAttributeValueDependenciesRequest) Reset() {
	*x = ListAttributeValueDependenciesRequest{}
	mi := &file_attribute_value_dependency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeValueDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeValueDependenciesRequest) ProtoMessage() {}

func (x *ListAttributeValueDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeValueDependenciesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributeValueDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{6}
}

func (x *ListAttributeValueDependenciesRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListAttributeValueDependenciesRequest) GetLatestVersion() bool {
	if x != nil {
		return x.LatestVersion
	}
	return false
}

func (x *ListAttributeValueDependenciesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListAttributeValueDependenciesRequest) GetSourceAttributeId() string {
	if x != nil {
		return x.SourceAttributeId
	}
	return ""
}

func (x *ListAttributeValueDependenciesRequest) GetTargetAttributeId() string {
	if x != nil {
		return x.TargetAttributeId
	}
	return ""
}

type ListAttributeValueDependenciesResponse struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	AttributeValueDependencies []*AttributeValueDependency `protobuf:"bytes,1,rep,name=attribute_value_dependencies,json=attributeValueDependencies,proto3" json:"attribute_value_dependencies,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ListAttributeValueDependenciesResponse) Reset() {
	*x = ListAttributeValueDependenciesResponse{}
	mi := &file_attribute_value_dependency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeValueDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeValueDependenciesResponse) ProtoMessage() {}

func (x *ListAttributeValueDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeValueDependenciesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributeValueDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{7}
}

func (x *ListAttributeValueDependenciesResponse) GetAttributeValueDependencies() []*AttributeValueDependency {
	if x != nil {
		return x.AttributeValueDependencies
	}
	return nil
}

// GetDependentValuesRequest represents a request to get dependent values
type GetDependentValuesRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	SourceAttributeDefinitionId string                 `protobuf:"bytes,1,opt,name=source_attribute_definition_id,json=sourceAttributeDefinitionId,proto3" json:"source_attribute_definition_id,omitempty"`
	SourceValue                 string                 `protobuf:"bytes,2,opt,name=source_value,json=sourceValue,proto3" json:"source_value,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GetDependentValuesRequest) Reset() {
	*x = GetDependentValuesRequest{}
	mi := &file_attribute_value_dependency_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependentValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependentValuesRequest) ProtoMessage() {}

func (x *GetDependentValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attribute_value_dependency_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependentValuesRequest.ProtoReflect.Descriptor instead.
func (*GetDependentValuesRequest) Descriptor() ([]byte, []int) {
	return file_attribute_value_dependency_proto_rawDescGZIP(), []int{8}
}

func (x *GetDependentValuesRequest) GetSourceAttributeDefinitionId() string {
	if x != nil {
		return x.SourceAttributeDefinitionId
	}
	return ""
}

func (x *GetDependentValuesRequest) GetSourceValue() string {
	if x != nil {
		return x.SourceValue
	}
	return ""
}

var File_attribute_value_dependency_proto protoreflect.FileDescriptor

const file_attribute_value_dependency_proto_rawDesc = "" +
	"\n" +
	" attribute_value_dependency.proto\x12\tflexitype\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa2\x03\n" +
	"\x18AttributeValueDependency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13source_attribute_id\x18\x02 \x01(\tR\x11sourceAttributeId\x12.\n" +
	"\x13target_attribute_id\x18\x03 \x01(\tR\x11targetAttributeId\x12'\n" +
	"\x0fdependency_type\x18\x04 \x01(\tR\x0edependencyType\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\varchived_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\"g\n" +
	"\x1cAttributeValueDependencyList\x12G\n" +
	"\fdependencies\x18\x01 \x03(\v2#.flexitype.AttributeValueDependencyR\fdependencies\"\xae\x02\n" +
	"%CreateAttributeValueDependencyRequest\x12C\n" +
	"\x1esource_attribute_definition_id\x18\x01 \x01(\tR\x1bsourceAttributeDefinitionId\x12C\n" +
	"\x1etarget_attribute_definition_id\x18\x02 \x01(\tR\x1btargetAttributeDefinitionId\x12+\n" +
	"\x11source_conditions\x18\x03 \x01(\tR\x10sourceConditions\x12#\n" +
	"\rtarget_values\x18\x04 \x01(\tR\ftargetValues\x12)\n" +
	"\x10validation_rules\x18\x05 \x01(\tR\x0fvalidationRules\"\xd8\x02\n" +
	"%UpdateAttributeValueDependencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\x1esource_attribute_definition_id\x18\x02 \x01(\tR\x1bsourceAttributeDefinitionId\x12C\n" +
	"\x1etarget_attribute_definition_id\x18\x03 \x01(\tR\x1btargetAttributeDefinitionId\x12+\n" +
	"\x11source_conditions\x18\x04 \x01(\tR\x10sourceConditions\x12#\n" +
	"\rtarget_values\x18\x05 \x01(\tR\ftargetValues\x12)\n" +
	"\x10validation_rules\x18\x06 \x01(\tR\x0fvalidationRules\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\"4\n" +
	"\"GetAttributeValueDependencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"&ArchiveAttributeValueDependencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xda\x01\n" +
	"%ListAttributeValueDependenciesRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\bR\rlatestVersion\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12.\n" +
	"\x13source_attribute_id\x18\x04 \x01(\tR\x11sourceAttributeId\x12.\n" +
	"\x13target_attribute_id\x18\x05 \x01(\tR\x11targetAttributeId\"\x8f\x01\n" +
	"&ListAttributeValueDependenciesResponse\x12e\n" +
	"\x1cattribute_value_dependencies\x18\x01 \x03(\v2#.flexitype.AttributeValueDependencyR\x1aattributeValueDependencies\"\x83\x01\n" +
	"\x19GetDependentValuesRequest\x12C\n" +
	"\x1esource_attribute_definition_id\x18\x01 \x01(\tR\x1bsourceAttributeDefinitionId\x12!\n" +
	"\fsource_value\x18\x02 \x01(\tR\vsourceValue2\xed\x05\n" +
	"\x1fAttributeValueDependencyService\x12y\n" +
	"\x1eCreateAttributeValueDependency\x120.flexitype.CreateAttributeValueDependencyRequest\x1a#.flexitype.AttributeValueDependency\"\x00\x12y\n" +
	"\x1eUpdateAttributeValueDependency\x120.flexitype.UpdateAttributeValueDependencyRequest\x1a#.flexitype.AttributeValueDependency\"\x00\x12s\n" +
	"\x1bGetAttributeValueDependency\x12-.flexitype.GetAttributeValueDependencyRequest\x1a#.flexitype.AttributeValueDependency\"\x00\x12n\n" +
	"\x1fArchiveAttributeValueDependency\x121.flexitype.ArchiveAttributeValueDependencyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x87\x01\n" +
	"\x1eListAttributeValueDependencies\x120.flexitype.ListAttributeValueDependenciesRequest\x1a1.flexitype.ListAttributeValueDependenciesResponse\"\x00\x12e\n" +
	"\x12GetDependentValues\x12$.flexitype.GetDependentValuesRequest\x1a'.flexitype.AttributeValueDependencyList\"\x00B8Z6github.com/zkrebbekx/flexitype/internal/api/connect/pbb\x06proto3"

var (
	file_attribute_value_dependency_proto_rawDescOnce sync.Once
	file_attribute_value_dependency_proto_rawDescData []byte
)

func file_attribute_value_dependency_proto_rawDescGZIP() []byte {
	file_attribute_value_dependency_proto_rawDescOnce.Do(func() {
		file_attribute_value_dependency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attribute_value_dependency_proto_rawDesc), len(file_attribute_value_dependency_proto_rawDesc)))
	})
	return file_attribute_value_dependency_proto_rawDescData
}

var file_attribute_value_dependency_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_attribute_value_dependency_proto_goTypes = []any{
	(*AttributeValueDependency)(nil),               // 0: flexitype.AttributeValueDependency
	(*AttributeValueDependencyList)(nil),           // 1: flexitype.AttributeValueDependencyList
	(*CreateAttributeValueDependencyRequest)(nil),  // 2: flexitype.CreateAttributeValueDependencyRequest
	(*UpdateAttributeValueDependencyRequest)(nil),  // 3: flexitype.UpdateAttributeValueDependencyRequest
	(*GetAttributeValueDependencyRequest)(nil),     // 4: flexitype.GetAttributeValueDependencyRequest
	(*ArchiveAttributeValueDependencyRequest)(nil), // 5: flexitype.ArchiveAttributeValueDependencyRequest
	(*ListAttributeValueDependenciesRequest)(nil),  // 6: flexitype.ListAttributeValueDependenciesRequest
	(*ListAttributeValueDependenciesResponse)(nil), // 7: flexitype.ListAttributeValueDependenciesResponse
	(*GetDependentValuesRequest)(nil),              // 8: flexitype.GetDependentValuesRequest
	(*timestamppb.Timestamp)(nil),                  // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                          // 10: google.protobuf.Empty
}
var file_attribute_value_dependency_proto_depIdxs = []int32{
	9,  // 0: flexitype.AttributeValueDependency.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: flexitype.AttributeValueDependency.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: flexitype.AttributeValueDependency.archived_at:type_name -> google.protobuf.Timestamp
	0,  // 3: flexitype.AttributeValueDependencyList.dependencies:type_name -> flexitype.AttributeValueDependency
	0,  // 4: flexitype.ListAttributeValueDependenciesResponse.attribute_value_dependencies:type_name -> flexitype.AttributeValueDependency
	2,  // 5: flexitype.AttributeValueDependencyService.CreateAttributeValueDependency:input_type -> flexitype.CreateAttributeValueDependencyRequest
	3,  // 6: flexitype.AttributeValueDependencyService.UpdateAttributeValueDependency:input_type -> flexitype.UpdateAttributeValueDependencyRequest
	4,  // 7: flexitype.AttributeValueDependencyService.GetAttributeValueDependency:input_type -> flexitype.GetAttributeValueDependencyRequest
	5,  // 8: flexitype.AttributeValueDependencyService.ArchiveAttributeValueDependency:input_type -> flexitype.ArchiveAttributeValueDependencyRequest
	6,  // 9: flexitype.AttributeValueDependencyService.ListAttributeValueDependencies:input_type -> flexitype.ListAttributeValueDependenciesRequest
	8,  // 10: flexitype.AttributeValueDependencyService.GetDependentValues:input_type -> flexitype.GetDependentValuesRequest
	0,  // 11: flexitype.AttributeValueDependencyService.CreateAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	0,  // 12: flexitype.AttributeValueDependencyService.UpdateAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	0,  // 13: flexitype.AttributeValueDependencyService.GetAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	10, // 14: flexitype.AttributeValueDependencyService.ArchiveAttributeValueDependency:output_type -> google.protobuf.Empty
	7,  // 15: flexitype.AttributeValueDependencyService.ListAttributeValueDependencies:output_type -> flexitype.ListAttributeValueDependenciesResponse
	1,  // 16: flexitype.AttributeValueDependencyService.GetDependentValues:output_type -> flexitype.AttributeValueDependencyList
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_attribute_value_dependency_proto_init() }
func file_attribute_value_dependency_proto_init() {
	if File_attribute_value_dependency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attribute_value_dependency_proto_rawDesc), len(file_attribute_value_dependency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attribute_value_dependency_proto_goTypes,
		DependencyIndexes: file_attribute_value_dependency_proto_depIdxs,
		MessageInfos:      file_attribute_value_dependency_proto_msgTypes,
	}.Build()
	File_attribute_value_dependency_proto = out.File
	file_attribute_value_dependency_proto_goTypes = nil
	file_attribute_value_dependency_proto_depIdxs = nil
}
