// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: attribute_value_dependency.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttributeValueDependencyService_CreateAttributeValueDependency_FullMethodName  = "/flexitype.AttributeValueDependencyService/CreateAttributeValueDependency"
	AttributeValueDependencyService_UpdateAttributeValueDependency_FullMethodName  = "/flexitype.AttributeValueDependencyService/UpdateAttributeValueDependency"
	AttributeValueDependencyService_GetAttributeValueDependency_FullMethodName     = "/flexitype.AttributeValueDependencyService/GetAttributeValueDependency"
	AttributeValueDependencyService_ArchiveAttributeValueDependency_FullMethodName = "/flexitype.AttributeValueDependencyService/ArchiveAttributeValueDependency"
	AttributeValueDependencyService_ListAttributeValueDependencies_FullMethodName  = "/flexitype.AttributeValueDependencyService/ListAttributeValueDependencies"
	AttributeValueDependencyService_GetDependentValues_FullMethodName              = "/flexitype.AttributeValueDependencyService/GetDependentValues"
)

// AttributeValueDependencyServiceClient is the client API for AttributeValueDependencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AttributeValueDependencyService provides operations for managing attribute value dependencies
type AttributeValueDependencyServiceClient interface {
	// CreateAttributeValueDependency creates a new dependency
	CreateAttributeValueDependency(ctx context.Context, in *CreateAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	// UpdateAttributeValueDependency updates an existing dependency
	UpdateAttributeValueDependency(ctx context.Context, in *UpdateAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	// GetAttributeValueDependency retrieves a dependency by ID
	GetAttributeValueDependency(ctx context.Context, in *GetAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	// ArchiveAttributeValueDependency archives a dependency
	ArchiveAttributeValueDependency(ctx context.Context, in *ArchiveAttributeValueDependencyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListAttributeValueDependencies lists dependencies based on filter criteria
	ListAttributeValueDependencies(ctx context.Context, in *ListAttributeValueDependenciesRequest, opts ...grpc.CallOption) (*ListAttributeValueDependenciesResponse, error)
	// GetDependentValues retrieves dependent values for a source value
	GetDependentValues(ctx context.Context, in *GetDependentValuesRequest, opts ...grpc.CallOption) (*AttributeValueDependencyList, error)
}

type attributeValueDependencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeValueDependencyServiceClient(cc grpc.ClientConnInterface) AttributeValueDependencyServiceClient {
	return &attributeValueDependencyServiceClient{cc}
}

func (c *attributeValueDependencyServiceClient) CreateAttributeValueDependency(ctx context.Context, in *CreateAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, AttributeValueDependencyService_CreateAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueDependencyServiceClient) UpdateAttributeValueDependency(ctx context.Context, in *UpdateAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, AttributeValueDependencyService_UpdateAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueDependencyServiceClient) GetAttributeValueDependency(ctx context.Context, in *GetAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, AttributeValueDependencyService_GetAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueDependencyServiceClient) ArchiveAttributeValueDependency(ctx context.Context, in *ArchiveAttributeValueDependencyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AttributeValueDependencyService_ArchiveAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueDependencyServiceClient) ListAttributeValueDependencies(ctx context.Context, in *ListAttributeValueDependenciesRequest, opts ...grpc.CallOption) (*ListAttributeValueDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributeValueDependenciesResponse)
	err := c.cc.Invoke(ctx, AttributeValueDependencyService_ListAttributeValueDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueDependencyServiceClient) GetDependentValues(ctx context.Context, in *GetDependentValuesRequest, opts ...grpc.CallOption) (*AttributeValueDependencyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependencyList)
	err := c.cc.Invoke(ctx, AttributeValueDependencyService_GetDependentValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeValueDependencyServiceServer is the server API for AttributeValueDependencyService service.
// All implementations must embed UnimplementedAttributeValueDependencyServiceServer
// for forward compatibility.
//
// AttributeValueDependencyService provides operations for managing attribute value dependencies
type AttributeValueDependencyServiceServer interface {
	// CreateAttributeValueDependency creates a new dependency
	CreateAttributeValueDependency(context.Context, *CreateAttributeValueDependencyRequest) (*AttributeValueDependency, error)
	// UpdateAttributeValueDependency updates an existing dependency
	UpdateAttributeValueDependency(context.Context, *UpdateAttributeValueDependencyRequest) (*AttributeValueDependency, error)
	// GetAttributeValueDependency retrieves a dependency by ID
	GetAttributeValueDependency(context.Context, *GetAttributeValueDependencyRequest) (*AttributeValueDependency, error)
	// ArchiveAttributeValueDependency archives a dependency
	ArchiveAttributeValueDependency(context.Context, *ArchiveAttributeValueDependencyRequest) (*emptypb.Empty, error)
	// ListAttributeValueDependencies lists dependencies based on filter criteria
	ListAttributeValueDependencies(context.Context, *ListAttributeValueDependenciesRequest) (*ListAttributeValueDependenciesResponse, error)
	// GetDependentValues retrieves dependent values for a source value
	GetDependentValues(context.Context, *GetDependentValuesRequest) (*AttributeValueDependencyList, error)
	mustEmbedUnimplementedAttributeValueDependencyServiceServer()
}

// UnimplementedAttributeValueDependencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttributeValueDependencyServiceServer struct{}

func (UnimplementedAttributeValueDependencyServiceServer) CreateAttributeValueDependency(context.Context, *CreateAttributeValueDependencyRequest) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttributeValueDependency not implemented")
}
func (UnimplementedAttributeValueDependencyServiceServer) UpdateAttributeValueDependency(context.Context, *UpdateAttributeValueDependencyRequest) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttributeValueDependency not implemented")
}
func (UnimplementedAttributeValueDependencyServiceServer) GetAttributeValueDependency(context.Context, *GetAttributeValueDependencyRequest) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributeValueDependency not implemented")
}
func (UnimplementedAttributeValueDependencyServiceServer) ArchiveAttributeValueDependency(context.Context, *ArchiveAttributeValueDependencyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveAttributeValueDependency not implemented")
}
func (UnimplementedAttributeValueDependencyServiceServer) ListAttributeValueDependencies(context.Context, *ListAttributeValueDependenciesRequest) (*ListAttributeValueDependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttributeValueDependencies not implemented")
}
func (UnimplementedAttributeValueDependencyServiceServer) GetDependentValues(context.Context, *GetDependentValuesRequest) (*AttributeValueDependencyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependentValues not implemented")
}
func (UnimplementedAttributeValueDependencyServiceServer) mustEmbedUnimplementedAttributeValueDependencyServiceServer() {
}
func (UnimplementedAttributeValueDependencyServiceServer) testEmbeddedByValue() {}

// UnsafeAttributeValueDependencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeValueDependencyServiceServer will
// result in compilation errors.
type UnsafeAttributeValueDependencyServiceServer interface {
	mustEmbedUnimplementedAttributeValueDependencyServiceServer()
}

func RegisterAttributeValueDependencyServiceServer(s grpc.ServiceRegistrar, srv AttributeValueDependencyServiceServer) {
	// If the following call pancis, it indicates UnimplementedAttributeValueDependencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttributeValueDependencyService_ServiceDesc, srv)
}

func _AttributeValueDependencyService_CreateAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttributeValueDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueDependencyServiceServer).CreateAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueDependencyService_CreateAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueDependencyServiceServer).CreateAttributeValueDependency(ctx, req.(*CreateAttributeValueDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueDependencyService_UpdateAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttributeValueDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueDependencyServiceServer).UpdateAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueDependencyService_UpdateAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueDependencyServiceServer).UpdateAttributeValueDependency(ctx, req.(*UpdateAttributeValueDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueDependencyService_GetAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeValueDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueDependencyServiceServer).GetAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueDependencyService_GetAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueDependencyServiceServer).GetAttributeValueDependency(ctx, req.(*GetAttributeValueDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueDependencyService_ArchiveAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveAttributeValueDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueDependencyServiceServer).ArchiveAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueDependencyService_ArchiveAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueDependencyServiceServer).ArchiveAttributeValueDependency(ctx, req.(*ArchiveAttributeValueDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueDependencyService_ListAttributeValueDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributeValueDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueDependencyServiceServer).ListAttributeValueDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueDependencyService_ListAttributeValueDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueDependencyServiceServer).ListAttributeValueDependencies(ctx, req.(*ListAttributeValueDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueDependencyService_GetDependentValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDependentValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueDependencyServiceServer).GetDependentValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueDependencyService_GetDependentValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueDependencyServiceServer).GetDependentValues(ctx, req.(*GetDependentValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeValueDependencyService_ServiceDesc is the grpc.ServiceDesc for AttributeValueDependencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeValueDependencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexitype.AttributeValueDependencyService",
	HandlerType: (*AttributeValueDependencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAttributeValueDependency",
			Handler:    _AttributeValueDependencyService_CreateAttributeValueDependency_Handler,
		},
		{
			MethodName: "UpdateAttributeValueDependency",
			Handler:    _AttributeValueDependencyService_UpdateAttributeValueDependency_Handler,
		},
		{
			MethodName: "GetAttributeValueDependency",
			Handler:    _AttributeValueDependencyService_GetAttributeValueDependency_Handler,
		},
		{
			MethodName: "ArchiveAttributeValueDependency",
			Handler:    _AttributeValueDependencyService_ArchiveAttributeValueDependency_Handler,
		},
		{
			MethodName: "ListAttributeValueDependencies",
			Handler:    _AttributeValueDependencyService_ListAttributeValueDependencies_Handler,
		},
		{
			MethodName: "GetDependentValues",
			Handler:    _AttributeValueDependencyService_GetDependentValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attribute_value_dependency.proto",
}
