// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: attribute_value.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttributeValueService_CreateAttributeValue_FullMethodName            = "/flexitype.AttributeValueService/CreateAttributeValue"
	AttributeValueService_UpdateAttributeValue_FullMethodName            = "/flexitype.AttributeValueService/UpdateAttributeValue"
	AttributeValueService_GetAttributeValue_FullMethodName               = "/flexitype.AttributeValueService/GetAttributeValue"
	AttributeValueService_ArchiveAttributeValue_FullMethodName           = "/flexitype.AttributeValueService/ArchiveAttributeValue"
	AttributeValueService_ListAttributeValues_FullMethodName             = "/flexitype.AttributeValueService/ListAttributeValues"
	AttributeValueService_GetAttributeValuesByAttributeID_FullMethodName = "/flexitype.AttributeValueService/GetAttributeValuesByAttributeID"
)

// AttributeValueServiceClient is the client API for AttributeValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AttributeValueService provides operations for managing attribute values
type AttributeValueServiceClient interface {
	// CreateAttributeValue creates a new attribute value
	CreateAttributeValue(ctx context.Context, in *CreateAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error)
	// UpdateAttributeValue updates an existing attribute value
	UpdateAttributeValue(ctx context.Context, in *UpdateAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error)
	// GetAttributeValue retrieves an attribute value by ID
	GetAttributeValue(ctx context.Context, in *GetAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error)
	// ArchiveAttributeValue archives an attribute value
	ArchiveAttributeValue(ctx context.Context, in *ArchiveAttributeValueRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListAttributeValues lists attribute values based on filter criteria
	ListAttributeValues(ctx context.Context, in *ListAttributeValuesRequest, opts ...grpc.CallOption) (*ListAttributeValuesResponse, error)
	// GetAttributeValuesByAttributeID retrieves values for a specific attribute
	GetAttributeValuesByAttributeID(ctx context.Context, in *GetAttributeValuesByAttributeIDRequest, opts ...grpc.CallOption) (*AttributeValueList, error)
}

type attributeValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeValueServiceClient(cc grpc.ClientConnInterface) AttributeValueServiceClient {
	return &attributeValueServiceClient{cc}
}

func (c *attributeValueServiceClient) CreateAttributeValue(ctx context.Context, in *CreateAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, AttributeValueService_CreateAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueServiceClient) UpdateAttributeValue(ctx context.Context, in *UpdateAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, AttributeValueService_UpdateAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueServiceClient) GetAttributeValue(ctx context.Context, in *GetAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, AttributeValueService_GetAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueServiceClient) ArchiveAttributeValue(ctx context.Context, in *ArchiveAttributeValueRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AttributeValueService_ArchiveAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueServiceClient) ListAttributeValues(ctx context.Context, in *ListAttributeValuesRequest, opts ...grpc.CallOption) (*ListAttributeValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributeValuesResponse)
	err := c.cc.Invoke(ctx, AttributeValueService_ListAttributeValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeValueServiceClient) GetAttributeValuesByAttributeID(ctx context.Context, in *GetAttributeValuesByAttributeIDRequest, opts ...grpc.CallOption) (*AttributeValueList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueList)
	err := c.cc.Invoke(ctx, AttributeValueService_GetAttributeValuesByAttributeID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeValueServiceServer is the server API for AttributeValueService service.
// All implementations must embed UnimplementedAttributeValueServiceServer
// for forward compatibility.
//
// AttributeValueService provides operations for managing attribute values
type AttributeValueServiceServer interface {
	// CreateAttributeValue creates a new attribute value
	CreateAttributeValue(context.Context, *CreateAttributeValueRequest) (*AttributeValue, error)
	// UpdateAttributeValue updates an existing attribute value
	UpdateAttributeValue(context.Context, *UpdateAttributeValueRequest) (*AttributeValue, error)
	// GetAttributeValue retrieves an attribute value by ID
	GetAttributeValue(context.Context, *GetAttributeValueRequest) (*AttributeValue, error)
	// ArchiveAttributeValue archives an attribute value
	ArchiveAttributeValue(context.Context, *ArchiveAttributeValueRequest) (*emptypb.Empty, error)
	// ListAttributeValues lists attribute values based on filter criteria
	ListAttributeValues(context.Context, *ListAttributeValuesRequest) (*ListAttributeValuesResponse, error)
	// GetAttributeValuesByAttributeID retrieves values for a specific attribute
	GetAttributeValuesByAttributeID(context.Context, *GetAttributeValuesByAttributeIDRequest) (*AttributeValueList, error)
	mustEmbedUnimplementedAttributeValueServiceServer()
}

// UnimplementedAttributeValueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttributeValueServiceServer struct{}

func (UnimplementedAttributeValueServiceServer) CreateAttributeValue(context.Context, *CreateAttributeValueRequest) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttributeValue not implemented")
}
func (UnimplementedAttributeValueServiceServer) UpdateAttributeValue(context.Context, *UpdateAttributeValueRequest) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttributeValue not implemented")
}
func (UnimplementedAttributeValueServiceServer) GetAttributeValue(context.Context, *GetAttributeValueRequest) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributeValue not implemented")
}
func (UnimplementedAttributeValueServiceServer) ArchiveAttributeValue(context.Context, *ArchiveAttributeValueRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveAttributeValue not implemented")
}
func (UnimplementedAttributeValueServiceServer) ListAttributeValues(context.Context, *ListAttributeValuesRequest) (*ListAttributeValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttributeValues not implemented")
}
func (UnimplementedAttributeValueServiceServer) GetAttributeValuesByAttributeID(context.Context, *GetAttributeValuesByAttributeIDRequest) (*AttributeValueList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributeValuesByAttributeID not implemented")
}
func (UnimplementedAttributeValueServiceServer) mustEmbedUnimplementedAttributeValueServiceServer() {}
func (UnimplementedAttributeValueServiceServer) testEmbeddedByValue()                               {}

// UnsafeAttributeValueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeValueServiceServer will
// result in compilation errors.
type UnsafeAttributeValueServiceServer interface {
	mustEmbedUnimplementedAttributeValueServiceServer()
}

func RegisterAttributeValueServiceServer(s grpc.ServiceRegistrar, srv AttributeValueServiceServer) {
	// If the following call pancis, it indicates UnimplementedAttributeValueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttributeValueService_ServiceDesc, srv)
}

func _AttributeValueService_CreateAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttributeValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueServiceServer).CreateAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueService_CreateAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueServiceServer).CreateAttributeValue(ctx, req.(*CreateAttributeValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueService_UpdateAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttributeValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueServiceServer).UpdateAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueService_UpdateAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueServiceServer).UpdateAttributeValue(ctx, req.(*UpdateAttributeValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueService_GetAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueServiceServer).GetAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueService_GetAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueServiceServer).GetAttributeValue(ctx, req.(*GetAttributeValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueService_ArchiveAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveAttributeValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueServiceServer).ArchiveAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueService_ArchiveAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueServiceServer).ArchiveAttributeValue(ctx, req.(*ArchiveAttributeValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueService_ListAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributeValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueServiceServer).ListAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueService_ListAttributeValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueServiceServer).ListAttributeValues(ctx, req.(*ListAttributeValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeValueService_GetAttributeValuesByAttributeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeValuesByAttributeIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeValueServiceServer).GetAttributeValuesByAttributeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeValueService_GetAttributeValuesByAttributeID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeValueServiceServer).GetAttributeValuesByAttributeID(ctx, req.(*GetAttributeValuesByAttributeIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeValueService_ServiceDesc is the grpc.ServiceDesc for AttributeValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexitype.AttributeValueService",
	HandlerType: (*AttributeValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAttributeValue",
			Handler:    _AttributeValueService_CreateAttributeValue_Handler,
		},
		{
			MethodName: "UpdateAttributeValue",
			Handler:    _AttributeValueService_UpdateAttributeValue_Handler,
		},
		{
			MethodName: "GetAttributeValue",
			Handler:    _AttributeValueService_GetAttributeValue_Handler,
		},
		{
			MethodName: "ArchiveAttributeValue",
			Handler:    _AttributeValueService_ArchiveAttributeValue_Handler,
		},
		{
			MethodName: "ListAttributeValues",
			Handler:    _AttributeValueService_ListAttributeValues_Handler,
		},
		{
			MethodName: "GetAttributeValuesByAttributeID",
			Handler:    _AttributeValueService_GetAttributeValuesByAttributeID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attribute_value.proto",
}
