// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: flexitype.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlexitypeService_CreateTypeDefinition_FullMethodName            = "/flexitype.FlexitypeService/CreateTypeDefinition"
	FlexitypeService_GetTypeDefinition_FullMethodName               = "/flexitype.FlexitypeService/GetTypeDefinition"
	FlexitypeService_UpdateTypeDefinition_FullMethodName            = "/flexitype.FlexitypeService/UpdateTypeDefinition"
	FlexitypeService_ArchiveTypeDefinition_FullMethodName           = "/flexitype.FlexitypeService/ArchiveTypeDefinition"
	FlexitypeService_ListTypeDefinitions_FullMethodName             = "/flexitype.FlexitypeService/ListTypeDefinitions"
	FlexitypeService_CreateAttribute_FullMethodName                 = "/flexitype.FlexitypeService/CreateAttribute"
	FlexitypeService_GetAttribute_FullMethodName                    = "/flexitype.FlexitypeService/GetAttribute"
	FlexitypeService_UpdateAttribute_FullMethodName                 = "/flexitype.FlexitypeService/UpdateAttribute"
	FlexitypeService_ArchiveAttribute_FullMethodName                = "/flexitype.FlexitypeService/ArchiveAttribute"
	FlexitypeService_ListAttributes_FullMethodName                  = "/flexitype.FlexitypeService/ListAttributes"
	FlexitypeService_GetAttributesByTypeDefinitionID_FullMethodName = "/flexitype.FlexitypeService/GetAttributesByTypeDefinitionID"
	FlexitypeService_CreateAttributeValue_FullMethodName            = "/flexitype.FlexitypeService/CreateAttributeValue"
	FlexitypeService_GetAttributeValue_FullMethodName               = "/flexitype.FlexitypeService/GetAttributeValue"
	FlexitypeService_UpdateAttributeValue_FullMethodName            = "/flexitype.FlexitypeService/UpdateAttributeValue"
	FlexitypeService_ArchiveAttributeValue_FullMethodName           = "/flexitype.FlexitypeService/ArchiveAttributeValue"
	FlexitypeService_ListAttributeValues_FullMethodName             = "/flexitype.FlexitypeService/ListAttributeValues"
	FlexitypeService_CreateAttributeValueDependency_FullMethodName  = "/flexitype.FlexitypeService/CreateAttributeValueDependency"
	FlexitypeService_GetAttributeValueDependency_FullMethodName     = "/flexitype.FlexitypeService/GetAttributeValueDependency"
	FlexitypeService_UpdateAttributeValueDependency_FullMethodName  = "/flexitype.FlexitypeService/UpdateAttributeValueDependency"
	FlexitypeService_ArchiveAttributeValueDependency_FullMethodName = "/flexitype.FlexitypeService/ArchiveAttributeValueDependency"
	FlexitypeService_ListAttributeValueDependencies_FullMethodName  = "/flexitype.FlexitypeService/ListAttributeValueDependencies"
)

// FlexitypeServiceClient is the client API for FlexitypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definitions
type FlexitypeServiceClient interface {
	// Type Definition operations
	CreateTypeDefinition(ctx context.Context, in *TypeDefinition, opts ...grpc.CallOption) (*TypeDefinition, error)
	GetTypeDefinition(ctx context.Context, in *GetTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error)
	UpdateTypeDefinition(ctx context.Context, in *TypeDefinition, opts ...grpc.CallOption) (*TypeDefinition, error)
	ArchiveTypeDefinition(ctx context.Context, in *ArchiveTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error)
	ListTypeDefinitions(ctx context.Context, in *ListTypeDefinitionsRequest, opts ...grpc.CallOption) (*ListTypeDefinitionsResponse, error)
	// Attribute operations
	CreateAttribute(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*Attribute, error)
	GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*Attribute, error)
	UpdateAttribute(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*Attribute, error)
	ArchiveAttribute(ctx context.Context, in *ArchiveAttributeRequest, opts ...grpc.CallOption) (*Attribute, error)
	ListAttributes(ctx context.Context, in *ListAttributesRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error)
	GetAttributesByTypeDefinitionID(ctx context.Context, in *GetAttributesByTypeDefinitionIDRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error)
	// Attribute Value operations
	CreateAttributeValue(ctx context.Context, in *AttributeValue, opts ...grpc.CallOption) (*AttributeValue, error)
	GetAttributeValue(ctx context.Context, in *GetAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error)
	UpdateAttributeValue(ctx context.Context, in *AttributeValue, opts ...grpc.CallOption) (*AttributeValue, error)
	ArchiveAttributeValue(ctx context.Context, in *ArchiveAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error)
	ListAttributeValues(ctx context.Context, in *ListAttributeValuesRequest, opts ...grpc.CallOption) (*ListAttributeValuesResponse, error)
	// Attribute Value Dependency operations
	CreateAttributeValueDependency(ctx context.Context, in *AttributeValueDependency, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	GetAttributeValueDependency(ctx context.Context, in *GetAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	UpdateAttributeValueDependency(ctx context.Context, in *AttributeValueDependency, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	ArchiveAttributeValueDependency(ctx context.Context, in *ArchiveAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error)
	ListAttributeValueDependencies(ctx context.Context, in *ListAttributeValueDependenciesRequest, opts ...grpc.CallOption) (*ListAttributeValueDependenciesResponse, error)
}

type flexitypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlexitypeServiceClient(cc grpc.ClientConnInterface) FlexitypeServiceClient {
	return &flexitypeServiceClient{cc}
}

func (c *flexitypeServiceClient) CreateTypeDefinition(ctx context.Context, in *TypeDefinition, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, FlexitypeService_CreateTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) GetTypeDefinition(ctx context.Context, in *GetTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, FlexitypeService_GetTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) UpdateTypeDefinition(ctx context.Context, in *TypeDefinition, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, FlexitypeService_UpdateTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ArchiveTypeDefinition(ctx context.Context, in *ArchiveTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, FlexitypeService_ArchiveTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ListTypeDefinitions(ctx context.Context, in *ListTypeDefinitionsRequest, opts ...grpc.CallOption) (*ListTypeDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTypeDefinitionsResponse)
	err := c.cc.Invoke(ctx, FlexitypeService_ListTypeDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) CreateAttribute(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*Attribute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attribute)
	err := c.cc.Invoke(ctx, FlexitypeService_CreateAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*Attribute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attribute)
	err := c.cc.Invoke(ctx, FlexitypeService_GetAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) UpdateAttribute(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*Attribute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attribute)
	err := c.cc.Invoke(ctx, FlexitypeService_UpdateAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ArchiveAttribute(ctx context.Context, in *ArchiveAttributeRequest, opts ...grpc.CallOption) (*Attribute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attribute)
	err := c.cc.Invoke(ctx, FlexitypeService_ArchiveAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ListAttributes(ctx context.Context, in *ListAttributesRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributesResponse)
	err := c.cc.Invoke(ctx, FlexitypeService_ListAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) GetAttributesByTypeDefinitionID(ctx context.Context, in *GetAttributesByTypeDefinitionIDRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributesResponse)
	err := c.cc.Invoke(ctx, FlexitypeService_GetAttributesByTypeDefinitionID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) CreateAttributeValue(ctx context.Context, in *AttributeValue, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, FlexitypeService_CreateAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) GetAttributeValue(ctx context.Context, in *GetAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, FlexitypeService_GetAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) UpdateAttributeValue(ctx context.Context, in *AttributeValue, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, FlexitypeService_UpdateAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ArchiveAttributeValue(ctx context.Context, in *ArchiveAttributeValueRequest, opts ...grpc.CallOption) (*AttributeValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValue)
	err := c.cc.Invoke(ctx, FlexitypeService_ArchiveAttributeValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ListAttributeValues(ctx context.Context, in *ListAttributeValuesRequest, opts ...grpc.CallOption) (*ListAttributeValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributeValuesResponse)
	err := c.cc.Invoke(ctx, FlexitypeService_ListAttributeValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) CreateAttributeValueDependency(ctx context.Context, in *AttributeValueDependency, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, FlexitypeService_CreateAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) GetAttributeValueDependency(ctx context.Context, in *GetAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, FlexitypeService_GetAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) UpdateAttributeValueDependency(ctx context.Context, in *AttributeValueDependency, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, FlexitypeService_UpdateAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ArchiveAttributeValueDependency(ctx context.Context, in *ArchiveAttributeValueDependencyRequest, opts ...grpc.CallOption) (*AttributeValueDependency, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeValueDependency)
	err := c.cc.Invoke(ctx, FlexitypeService_ArchiveAttributeValueDependency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flexitypeServiceClient) ListAttributeValueDependencies(ctx context.Context, in *ListAttributeValueDependenciesRequest, opts ...grpc.CallOption) (*ListAttributeValueDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributeValueDependenciesResponse)
	err := c.cc.Invoke(ctx, FlexitypeService_ListAttributeValueDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlexitypeServiceServer is the server API for FlexitypeService service.
// All implementations must embed UnimplementedFlexitypeServiceServer
// for forward compatibility.
//
// Service definitions
type FlexitypeServiceServer interface {
	// Type Definition operations
	CreateTypeDefinition(context.Context, *TypeDefinition) (*TypeDefinition, error)
	GetTypeDefinition(context.Context, *GetTypeDefinitionRequest) (*TypeDefinition, error)
	UpdateTypeDefinition(context.Context, *TypeDefinition) (*TypeDefinition, error)
	ArchiveTypeDefinition(context.Context, *ArchiveTypeDefinitionRequest) (*TypeDefinition, error)
	ListTypeDefinitions(context.Context, *ListTypeDefinitionsRequest) (*ListTypeDefinitionsResponse, error)
	// Attribute operations
	CreateAttribute(context.Context, *Attribute) (*Attribute, error)
	GetAttribute(context.Context, *GetAttributeRequest) (*Attribute, error)
	UpdateAttribute(context.Context, *Attribute) (*Attribute, error)
	ArchiveAttribute(context.Context, *ArchiveAttributeRequest) (*Attribute, error)
	ListAttributes(context.Context, *ListAttributesRequest) (*ListAttributesResponse, error)
	GetAttributesByTypeDefinitionID(context.Context, *GetAttributesByTypeDefinitionIDRequest) (*ListAttributesResponse, error)
	// Attribute Value operations
	CreateAttributeValue(context.Context, *AttributeValue) (*AttributeValue, error)
	GetAttributeValue(context.Context, *GetAttributeValueRequest) (*AttributeValue, error)
	UpdateAttributeValue(context.Context, *AttributeValue) (*AttributeValue, error)
	ArchiveAttributeValue(context.Context, *ArchiveAttributeValueRequest) (*AttributeValue, error)
	ListAttributeValues(context.Context, *ListAttributeValuesRequest) (*ListAttributeValuesResponse, error)
	// Attribute Value Dependency operations
	CreateAttributeValueDependency(context.Context, *AttributeValueDependency) (*AttributeValueDependency, error)
	GetAttributeValueDependency(context.Context, *GetAttributeValueDependencyRequest) (*AttributeValueDependency, error)
	UpdateAttributeValueDependency(context.Context, *AttributeValueDependency) (*AttributeValueDependency, error)
	ArchiveAttributeValueDependency(context.Context, *ArchiveAttributeValueDependencyRequest) (*AttributeValueDependency, error)
	ListAttributeValueDependencies(context.Context, *ListAttributeValueDependenciesRequest) (*ListAttributeValueDependenciesResponse, error)
	mustEmbedUnimplementedFlexitypeServiceServer()
}

// UnimplementedFlexitypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlexitypeServiceServer struct{}

func (UnimplementedFlexitypeServiceServer) CreateTypeDefinition(context.Context, *TypeDefinition) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTypeDefinition not implemented")
}
func (UnimplementedFlexitypeServiceServer) GetTypeDefinition(context.Context, *GetTypeDefinitionRequest) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTypeDefinition not implemented")
}
func (UnimplementedFlexitypeServiceServer) UpdateTypeDefinition(context.Context, *TypeDefinition) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTypeDefinition not implemented")
}
func (UnimplementedFlexitypeServiceServer) ArchiveTypeDefinition(context.Context, *ArchiveTypeDefinitionRequest) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveTypeDefinition not implemented")
}
func (UnimplementedFlexitypeServiceServer) ListTypeDefinitions(context.Context, *ListTypeDefinitionsRequest) (*ListTypeDefinitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTypeDefinitions not implemented")
}
func (UnimplementedFlexitypeServiceServer) CreateAttribute(context.Context, *Attribute) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttribute not implemented")
}
func (UnimplementedFlexitypeServiceServer) GetAttribute(context.Context, *GetAttributeRequest) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttribute not implemented")
}
func (UnimplementedFlexitypeServiceServer) UpdateAttribute(context.Context, *Attribute) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttribute not implemented")
}
func (UnimplementedFlexitypeServiceServer) ArchiveAttribute(context.Context, *ArchiveAttributeRequest) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveAttribute not implemented")
}
func (UnimplementedFlexitypeServiceServer) ListAttributes(context.Context, *ListAttributesRequest) (*ListAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttributes not implemented")
}
func (UnimplementedFlexitypeServiceServer) GetAttributesByTypeDefinitionID(context.Context, *GetAttributesByTypeDefinitionIDRequest) (*ListAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributesByTypeDefinitionID not implemented")
}
func (UnimplementedFlexitypeServiceServer) CreateAttributeValue(context.Context, *AttributeValue) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttributeValue not implemented")
}
func (UnimplementedFlexitypeServiceServer) GetAttributeValue(context.Context, *GetAttributeValueRequest) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributeValue not implemented")
}
func (UnimplementedFlexitypeServiceServer) UpdateAttributeValue(context.Context, *AttributeValue) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttributeValue not implemented")
}
func (UnimplementedFlexitypeServiceServer) ArchiveAttributeValue(context.Context, *ArchiveAttributeValueRequest) (*AttributeValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveAttributeValue not implemented")
}
func (UnimplementedFlexitypeServiceServer) ListAttributeValues(context.Context, *ListAttributeValuesRequest) (*ListAttributeValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttributeValues not implemented")
}
func (UnimplementedFlexitypeServiceServer) CreateAttributeValueDependency(context.Context, *AttributeValueDependency) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttributeValueDependency not implemented")
}
func (UnimplementedFlexitypeServiceServer) GetAttributeValueDependency(context.Context, *GetAttributeValueDependencyRequest) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttributeValueDependency not implemented")
}
func (UnimplementedFlexitypeServiceServer) UpdateAttributeValueDependency(context.Context, *AttributeValueDependency) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttributeValueDependency not implemented")
}
func (UnimplementedFlexitypeServiceServer) ArchiveAttributeValueDependency(context.Context, *ArchiveAttributeValueDependencyRequest) (*AttributeValueDependency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveAttributeValueDependency not implemented")
}
func (UnimplementedFlexitypeServiceServer) ListAttributeValueDependencies(context.Context, *ListAttributeValueDependenciesRequest) (*ListAttributeValueDependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAttributeValueDependencies not implemented")
}
func (UnimplementedFlexitypeServiceServer) mustEmbedUnimplementedFlexitypeServiceServer() {}
func (UnimplementedFlexitypeServiceServer) testEmbeddedByValue()                          {}

// UnsafeFlexitypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlexitypeServiceServer will
// result in compilation errors.
type UnsafeFlexitypeServiceServer interface {
	mustEmbedUnimplementedFlexitypeServiceServer()
}

func RegisterFlexitypeServiceServer(s grpc.ServiceRegistrar, srv FlexitypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlexitypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlexitypeService_ServiceDesc, srv)
}

func _FlexitypeService_CreateTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeDefinition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).CreateTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_CreateTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).CreateTypeDefinition(ctx, req.(*TypeDefinition))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_GetTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).GetTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_GetTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).GetTypeDefinition(ctx, req.(*GetTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_UpdateTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeDefinition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).UpdateTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_UpdateTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).UpdateTypeDefinition(ctx, req.(*TypeDefinition))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ArchiveTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ArchiveTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ArchiveTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ArchiveTypeDefinition(ctx, req.(*ArchiveTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ListTypeDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTypeDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ListTypeDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ListTypeDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ListTypeDefinitions(ctx, req.(*ListTypeDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_CreateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attribute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).CreateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_CreateAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).CreateAttribute(ctx, req.(*Attribute))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_GetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).GetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_GetAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).GetAttribute(ctx, req.(*GetAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_UpdateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attribute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).UpdateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_UpdateAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).UpdateAttribute(ctx, req.(*Attribute))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ArchiveAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ArchiveAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ArchiveAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ArchiveAttribute(ctx, req.(*ArchiveAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ListAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ListAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ListAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ListAttributes(ctx, req.(*ListAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_GetAttributesByTypeDefinitionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesByTypeDefinitionIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).GetAttributesByTypeDefinitionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_GetAttributesByTypeDefinitionID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).GetAttributesByTypeDefinitionID(ctx, req.(*GetAttributesByTypeDefinitionIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_CreateAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).CreateAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_CreateAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).CreateAttributeValue(ctx, req.(*AttributeValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_GetAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).GetAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_GetAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).GetAttributeValue(ctx, req.(*GetAttributeValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_UpdateAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).UpdateAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_UpdateAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).UpdateAttributeValue(ctx, req.(*AttributeValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ArchiveAttributeValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveAttributeValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ArchiveAttributeValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ArchiveAttributeValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ArchiveAttributeValue(ctx, req.(*ArchiveAttributeValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ListAttributeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributeValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ListAttributeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ListAttributeValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ListAttributeValues(ctx, req.(*ListAttributeValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_CreateAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeValueDependency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).CreateAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_CreateAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).CreateAttributeValueDependency(ctx, req.(*AttributeValueDependency))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_GetAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeValueDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).GetAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_GetAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).GetAttributeValueDependency(ctx, req.(*GetAttributeValueDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_UpdateAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeValueDependency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).UpdateAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_UpdateAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).UpdateAttributeValueDependency(ctx, req.(*AttributeValueDependency))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ArchiveAttributeValueDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveAttributeValueDependencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ArchiveAttributeValueDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ArchiveAttributeValueDependency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ArchiveAttributeValueDependency(ctx, req.(*ArchiveAttributeValueDependencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlexitypeService_ListAttributeValueDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributeValueDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexitypeServiceServer).ListAttributeValueDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlexitypeService_ListAttributeValueDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexitypeServiceServer).ListAttributeValueDependencies(ctx, req.(*ListAttributeValueDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlexitypeService_ServiceDesc is the grpc.ServiceDesc for FlexitypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlexitypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexitype.FlexitypeService",
	HandlerType: (*FlexitypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTypeDefinition",
			Handler:    _FlexitypeService_CreateTypeDefinition_Handler,
		},
		{
			MethodName: "GetTypeDefinition",
			Handler:    _FlexitypeService_GetTypeDefinition_Handler,
		},
		{
			MethodName: "UpdateTypeDefinition",
			Handler:    _FlexitypeService_UpdateTypeDefinition_Handler,
		},
		{
			MethodName: "ArchiveTypeDefinition",
			Handler:    _FlexitypeService_ArchiveTypeDefinition_Handler,
		},
		{
			MethodName: "ListTypeDefinitions",
			Handler:    _FlexitypeService_ListTypeDefinitions_Handler,
		},
		{
			MethodName: "CreateAttribute",
			Handler:    _FlexitypeService_CreateAttribute_Handler,
		},
		{
			MethodName: "GetAttribute",
			Handler:    _FlexitypeService_GetAttribute_Handler,
		},
		{
			MethodName: "UpdateAttribute",
			Handler:    _FlexitypeService_UpdateAttribute_Handler,
		},
		{
			MethodName: "ArchiveAttribute",
			Handler:    _FlexitypeService_ArchiveAttribute_Handler,
		},
		{
			MethodName: "ListAttributes",
			Handler:    _FlexitypeService_ListAttributes_Handler,
		},
		{
			MethodName: "GetAttributesByTypeDefinitionID",
			Handler:    _FlexitypeService_GetAttributesByTypeDefinitionID_Handler,
		},
		{
			MethodName: "CreateAttributeValue",
			Handler:    _FlexitypeService_CreateAttributeValue_Handler,
		},
		{
			MethodName: "GetAttributeValue",
			Handler:    _FlexitypeService_GetAttributeValue_Handler,
		},
		{
			MethodName: "UpdateAttributeValue",
			Handler:    _FlexitypeService_UpdateAttributeValue_Handler,
		},
		{
			MethodName: "ArchiveAttributeValue",
			Handler:    _FlexitypeService_ArchiveAttributeValue_Handler,
		},
		{
			MethodName: "ListAttributeValues",
			Handler:    _FlexitypeService_ListAttributeValues_Handler,
		},
		{
			MethodName: "CreateAttributeValueDependency",
			Handler:    _FlexitypeService_CreateAttributeValueDependency_Handler,
		},
		{
			MethodName: "GetAttributeValueDependency",
			Handler:    _FlexitypeService_GetAttributeValueDependency_Handler,
		},
		{
			MethodName: "UpdateAttributeValueDependency",
			Handler:    _FlexitypeService_UpdateAttributeValueDependency_Handler,
		},
		{
			MethodName: "ArchiveAttributeValueDependency",
			Handler:    _FlexitypeService_ArchiveAttributeValueDependency_Handler,
		},
		{
			MethodName: "ListAttributeValueDependencies",
			Handler:    _FlexitypeService_ListAttributeValueDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flexitype.proto",
}
