// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: flexitype.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_flexitype_proto protoreflect.FileDescriptor

const file_flexitype_proto_rawDesc = "" +
	"\n" +
	"\x0fflexitype.proto\x12\tflexitype\x1a\x15type_definition.proto\x1a\x0fattribute.proto\x1a\x15attribute_value.proto\x1a attribute_value_dependency.proto2\xd4\x0f\n" +
	"\x10FlexitypeService\x12N\n" +
	"\x14CreateTypeDefinition\x12\x19.flexitype.TypeDefinition\x1a\x19.flexitype.TypeDefinition\"\x00\x12U\n" +
	"\x11GetTypeDefinition\x12#.flexitype.GetTypeDefinitionRequest\x1a\x19.flexitype.TypeDefinition\"\x00\x12N\n" +
	"\x14UpdateTypeDefinition\x12\x19.flexitype.TypeDefinition\x1a\x19.flexitype.TypeDefinition\"\x00\x12]\n" +
	"\x15ArchiveTypeDefinition\x12'.flexitype.ArchiveTypeDefinitionRequest\x1a\x19.flexitype.TypeDefinition\"\x00\x12f\n" +
	"\x13ListTypeDefinitions\x12%.flexitype.ListTypeDefinitionsRequest\x1a&.flexitype.ListTypeDefinitionsResponse\"\x00\x12?\n" +
	"\x0fCreateAttribute\x12\x14.flexitype.Attribute\x1a\x14.flexitype.Attribute\"\x00\x12F\n" +
	"\fGetAttribute\x12\x1e.flexitype.GetAttributeRequest\x1a\x14.flexitype.Attribute\"\x00\x12?\n" +
	"\x0fUpdateAttribute\x12\x14.flexitype.Attribute\x1a\x14.flexitype.Attribute\"\x00\x12N\n" +
	"\x10ArchiveAttribute\x12\".flexitype.ArchiveAttributeRequest\x1a\x14.flexitype.Attribute\"\x00\x12W\n" +
	"\x0eListAttributes\x12 .flexitype.ListAttributesRequest\x1a!.flexitype.ListAttributesResponse\"\x00\x12y\n" +
	"\x1fGetAttributesByTypeDefinitionID\x121.flexitype.GetAttributesByTypeDefinitionIDRequest\x1a!.flexitype.ListAttributesResponse\"\x00\x12N\n" +
	"\x14CreateAttributeValue\x12\x19.flexitype.AttributeValue\x1a\x19.flexitype.AttributeValue\"\x00\x12U\n" +
	"\x11GetAttributeValue\x12#.flexitype.GetAttributeValueRequest\x1a\x19.flexitype.AttributeValue\"\x00\x12N\n" +
	"\x14UpdateAttributeValue\x12\x19.flexitype.AttributeValue\x1a\x19.flexitype.AttributeValue\"\x00\x12]\n" +
	"\x15ArchiveAttributeValue\x12'.flexitype.ArchiveAttributeValueRequest\x1a\x19.flexitype.AttributeValue\"\x00\x12f\n" +
	"\x13ListAttributeValues\x12%.flexitype.ListAttributeValuesRequest\x1a&.flexitype.ListAttributeValuesResponse\"\x00\x12l\n" +
	"\x1eCreateAttributeValueDependency\x12#.flexitype.AttributeValueDependency\x1a#.flexitype.AttributeValueDependency\"\x00\x12s\n" +
	"\x1bGetAttributeValueDependency\x12-.flexitype.GetAttributeValueDependencyRequest\x1a#.flexitype.AttributeValueDependency\"\x00\x12l\n" +
	"\x1eUpdateAttributeValueDependency\x12#.flexitype.AttributeValueDependency\x1a#.flexitype.AttributeValueDependency\"\x00\x12{\n" +
	"\x1fArchiveAttributeValueDependency\x121.flexitype.ArchiveAttributeValueDependencyRequest\x1a#.flexitype.AttributeValueDependency\"\x00\x12\x87\x01\n" +
	"\x1eListAttributeValueDependencies\x120.flexitype.ListAttributeValueDependenciesRequest\x1a1.flexitype.ListAttributeValueDependenciesResponse\"\x00B8Z6github.com/zkrebbekx/flexitype/internal/api/connect/pbb\x06proto3"

var file_flexitype_proto_goTypes = []any{
	(*TypeDefinition)(nil),                         // 0: flexitype.TypeDefinition
	(*GetTypeDefinitionRequest)(nil),               // 1: flexitype.GetTypeDefinitionRequest
	(*ArchiveTypeDefinitionRequest)(nil),           // 2: flexitype.ArchiveTypeDefinitionRequest
	(*ListTypeDefinitionsRequest)(nil),             // 3: flexitype.ListTypeDefinitionsRequest
	(*Attribute)(nil),                              // 4: flexitype.Attribute
	(*GetAttributeRequest)(nil),                    // 5: flexitype.GetAttributeRequest
	(*ArchiveAttributeRequest)(nil),                // 6: flexitype.ArchiveAttributeRequest
	(*ListAttributesRequest)(nil),                  // 7: flexitype.ListAttributesRequest
	(*GetAttributesByTypeDefinitionIDRequest)(nil), // 8: flexitype.GetAttributesByTypeDefinitionIDRequest
	(*AttributeValue)(nil),                         // 9: flexitype.AttributeValue
	(*GetAttributeValueRequest)(nil),               // 10: flexitype.GetAttributeValueRequest
	(*ArchiveAttributeValueRequest)(nil),           // 11: flexitype.ArchiveAttributeValueRequest
	(*ListAttributeValuesRequest)(nil),             // 12: flexitype.ListAttributeValuesRequest
	(*AttributeValueDependency)(nil),               // 13: flexitype.AttributeValueDependency
	(*GetAttributeValueDependencyRequest)(nil),     // 14: flexitype.GetAttributeValueDependencyRequest
	(*ArchiveAttributeValueDependencyRequest)(nil), // 15: flexitype.ArchiveAttributeValueDependencyRequest
	(*ListAttributeValueDependenciesRequest)(nil),  // 16: flexitype.ListAttributeValueDependenciesRequest
	(*ListTypeDefinitionsResponse)(nil),            // 17: flexitype.ListTypeDefinitionsResponse
	(*ListAttributesResponse)(nil),                 // 18: flexitype.ListAttributesResponse
	(*ListAttributeValuesResponse)(nil),            // 19: flexitype.ListAttributeValuesResponse
	(*ListAttributeValueDependenciesResponse)(nil), // 20: flexitype.ListAttributeValueDependenciesResponse
}
var file_flexitype_proto_depIdxs = []int32{
	0,  // 0: flexitype.FlexitypeService.CreateTypeDefinition:input_type -> flexitype.TypeDefinition
	1,  // 1: flexitype.FlexitypeService.GetTypeDefinition:input_type -> flexitype.GetTypeDefinitionRequest
	0,  // 2: flexitype.FlexitypeService.UpdateTypeDefinition:input_type -> flexitype.TypeDefinition
	2,  // 3: flexitype.FlexitypeService.ArchiveTypeDefinition:input_type -> flexitype.ArchiveTypeDefinitionRequest
	3,  // 4: flexitype.FlexitypeService.ListTypeDefinitions:input_type -> flexitype.ListTypeDefinitionsRequest
	4,  // 5: flexitype.FlexitypeService.CreateAttribute:input_type -> flexitype.Attribute
	5,  // 6: flexitype.FlexitypeService.GetAttribute:input_type -> flexitype.GetAttributeRequest
	4,  // 7: flexitype.FlexitypeService.UpdateAttribute:input_type -> flexitype.Attribute
	6,  // 8: flexitype.FlexitypeService.ArchiveAttribute:input_type -> flexitype.ArchiveAttributeRequest
	7,  // 9: flexitype.FlexitypeService.ListAttributes:input_type -> flexitype.ListAttributesRequest
	8,  // 10: flexitype.FlexitypeService.GetAttributesByTypeDefinitionID:input_type -> flexitype.GetAttributesByTypeDefinitionIDRequest
	9,  // 11: flexitype.FlexitypeService.CreateAttributeValue:input_type -> flexitype.AttributeValue
	10, // 12: flexitype.FlexitypeService.GetAttributeValue:input_type -> flexitype.GetAttributeValueRequest
	9,  // 13: flexitype.FlexitypeService.UpdateAttributeValue:input_type -> flexitype.AttributeValue
	11, // 14: flexitype.FlexitypeService.ArchiveAttributeValue:input_type -> flexitype.ArchiveAttributeValueRequest
	12, // 15: flexitype.FlexitypeService.ListAttributeValues:input_type -> flexitype.ListAttributeValuesRequest
	13, // 16: flexitype.FlexitypeService.CreateAttributeValueDependency:input_type -> flexitype.AttributeValueDependency
	14, // 17: flexitype.FlexitypeService.GetAttributeValueDependency:input_type -> flexitype.GetAttributeValueDependencyRequest
	13, // 18: flexitype.FlexitypeService.UpdateAttributeValueDependency:input_type -> flexitype.AttributeValueDependency
	15, // 19: flexitype.FlexitypeService.ArchiveAttributeValueDependency:input_type -> flexitype.ArchiveAttributeValueDependencyRequest
	16, // 20: flexitype.FlexitypeService.ListAttributeValueDependencies:input_type -> flexitype.ListAttributeValueDependenciesRequest
	0,  // 21: flexitype.FlexitypeService.CreateTypeDefinition:output_type -> flexitype.TypeDefinition
	0,  // 22: flexitype.FlexitypeService.GetTypeDefinition:output_type -> flexitype.TypeDefinition
	0,  // 23: flexitype.FlexitypeService.UpdateTypeDefinition:output_type -> flexitype.TypeDefinition
	0,  // 24: flexitype.FlexitypeService.ArchiveTypeDefinition:output_type -> flexitype.TypeDefinition
	17, // 25: flexitype.FlexitypeService.ListTypeDefinitions:output_type -> flexitype.ListTypeDefinitionsResponse
	4,  // 26: flexitype.FlexitypeService.CreateAttribute:output_type -> flexitype.Attribute
	4,  // 27: flexitype.FlexitypeService.GetAttribute:output_type -> flexitype.Attribute
	4,  // 28: flexitype.FlexitypeService.UpdateAttribute:output_type -> flexitype.Attribute
	4,  // 29: flexitype.FlexitypeService.ArchiveAttribute:output_type -> flexitype.Attribute
	18, // 30: flexitype.FlexitypeService.ListAttributes:output_type -> flexitype.ListAttributesResponse
	18, // 31: flexitype.FlexitypeService.GetAttributesByTypeDefinitionID:output_type -> flexitype.ListAttributesResponse
	9,  // 32: flexitype.FlexitypeService.CreateAttributeValue:output_type -> flexitype.AttributeValue
	9,  // 33: flexitype.FlexitypeService.GetAttributeValue:output_type -> flexitype.AttributeValue
	9,  // 34: flexitype.FlexitypeService.UpdateAttributeValue:output_type -> flexitype.AttributeValue
	9,  // 35: flexitype.FlexitypeService.ArchiveAttributeValue:output_type -> flexitype.AttributeValue
	19, // 36: flexitype.FlexitypeService.ListAttributeValues:output_type -> flexitype.ListAttributeValuesResponse
	13, // 37: flexitype.FlexitypeService.CreateAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	13, // 38: flexitype.FlexitypeService.GetAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	13, // 39: flexitype.FlexitypeService.UpdateAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	13, // 40: flexitype.FlexitypeService.ArchiveAttributeValueDependency:output_type -> flexitype.AttributeValueDependency
	20, // 41: flexitype.FlexitypeService.ListAttributeValueDependencies:output_type -> flexitype.ListAttributeValueDependenciesResponse
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_flexitype_proto_init() }
func file_flexitype_proto_init() {
	if File_flexitype_proto != nil {
		return
	}
	file_type_definition_proto_init()
	file_attribute_proto_init()
	file_attribute_value_proto_init()
	file_attribute_value_dependency_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flexitype_proto_rawDesc), len(file_flexitype_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flexitype_proto_goTypes,
		DependencyIndexes: file_flexitype_proto_depIdxs,
	}.Build()
	File_flexitype_proto = out.File
	file_flexitype_proto_goTypes = nil
	file_flexitype_proto_depIdxs = nil
}
