// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: flexitype.proto

package flexitypev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type-related messages
type CreateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentTypeId  string                 `protobuf:"bytes,4,opt,name=parent_type_id,json=parentTypeId,proto3" json:"parent_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeRequest) Reset() {
	*x = CreateTypeRequest{}
	mi := &file_flexitype_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeRequest) ProtoMessage() {}

func (x *CreateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTypeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTypeRequest) GetParentTypeId() string {
	if x != nil {
		return x.ParentTypeId
	}
	return ""
}

type GetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeRequest) Reset() {
	*x = GetTypeRequest{}
	mi := &file_flexitype_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRequest) ProtoMessage() {}

func (x *GetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{1}
}

func (x *GetTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTypesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination and filtering options
	PageSize        int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	IncludeArchived bool   `protobuf:"varint,3,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"` // If true, include archived types in the results
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTypesRequest) Reset() {
	*x = ListTypesRequest{}
	mi := &file_flexitype_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesRequest) ProtoMessage() {}

func (x *ListTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesRequest.ProtoReflect.Descriptor instead.
func (*ListTypesRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{2}
}

func (x *ListTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTypesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTypesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*TypeDefinition      `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesResponse) Reset() {
	*x = ListTypesResponse{}
	mi := &file_flexitype_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesResponse) ProtoMessage() {}

func (x *ListTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesResponse.ProtoReflect.Descriptor instead.
func (*ListTypesResponse) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{3}
}

func (x *ListTypesResponse) GetTypes() []*TypeDefinition {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ListTypesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentTypeId  string                 `protobuf:"bytes,4,opt,name=parent_type_id,json=parentTypeId,proto3" json:"parent_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTypeRequest) Reset() {
	*x = UpdateTypeRequest{}
	mi := &file_flexitype_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeRequest) ProtoMessage() {}

func (x *UpdateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTypeRequest) GetParentTypeId() string {
	if x != nil {
		return x.ParentTypeId
	}
	return ""
}

type ArchiveTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveTypeRequest) Reset() {
	*x = ArchiveTypeRequest{}
	mi := &file_flexitype_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTypeRequest) ProtoMessage() {}

func (x *ArchiveTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTypeRequest.ProtoReflect.Descriptor instead.
func (*ArchiveTypeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnarchiveTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveTypeRequest) Reset() {
	*x = UnarchiveTypeRequest{}
	mi := &file_flexitype_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveTypeRequest) ProtoMessage() {}

func (x *UnarchiveTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveTypeRequest.ProtoReflect.Descriptor instead.
func (*UnarchiveTypeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{6}
}

func (x *UnarchiveTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *TypeDefinition        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_flexitype_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{7}
}

func (x *TypeResponse) GetType() *TypeDefinition {
	if x != nil {
		return x.Type
	}
	return nil
}

// Attribute-related messages
type AddAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Attribute     *AttributeDefinition   `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAttributeRequest) Reset() {
	*x = AddAttributeRequest{}
	mi := &file_flexitype_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAttributeRequest) ProtoMessage() {}

func (x *AddAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAttributeRequest.ProtoReflect.Descriptor instead.
func (*AddAttributeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{8}
}

func (x *AddAttributeRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *AddAttributeRequest) GetAttribute() *AttributeDefinition {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type UpdateAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Attribute     *AttributeDefinition   `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttributeRequest) Reset() {
	*x = UpdateAttributeRequest{}
	mi := &file_flexitype_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttributeRequest) ProtoMessage() {}

func (x *UpdateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttributeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAttributeRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *UpdateAttributeRequest) GetAttribute() *AttributeDefinition {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type DeleteAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	AttributeId   string                 `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributeRequest) Reset() {
	*x = DeleteAttributeRequest{}
	mi := &file_flexitype_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributeRequest) ProtoMessage() {}

func (x *DeleteAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributeRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttributeRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAttributeRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *DeleteAttributeRequest) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

type SetAttributeDisabledStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	AttributeId   string                 `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Disabled      bool                   `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttributeDisabledStateRequest) Reset() {
	*x = SetAttributeDisabledStateRequest{}
	mi := &file_flexitype_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttributeDisabledStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttributeDisabledStateRequest) ProtoMessage() {}

func (x *SetAttributeDisabledStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttributeDisabledStateRequest.ProtoReflect.Descriptor instead.
func (*SetAttributeDisabledStateRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{11}
}

func (x *SetAttributeDisabledStateRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *SetAttributeDisabledStateRequest) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

func (x *SetAttributeDisabledStateRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

// Instance-related messages
type CreateInstanceRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Id              string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId          string                     `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	AttributeValues map[string]*AttributeValue `protobuf:"bytes,3,rep,name=attribute_values,json=attributeValues,proto3" json:"attribute_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_flexitype_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{12}
}

func (x *CreateInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateInstanceRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreateInstanceRequest) GetAttributeValues() map[string]*AttributeValue {
	if x != nil {
		return x.AttributeValues
	}
	return nil
}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_flexitype_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{13}
}

func (x *GetInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryInstancesRequest struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	TypeId           string                     `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	AttributeFilters map[string]*AttributeValue `protobuf:"bytes,2,rep,name=attribute_filters,json=attributeFilters,proto3" json:"attribute_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PageSize         int32                      `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken        string                     `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	IncludeArchived  bool                       `protobuf:"varint,5,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"` // If true, include archived instances in query results
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryInstancesRequest) Reset() {
	*x = QueryInstancesRequest{}
	mi := &file_flexitype_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInstancesRequest) ProtoMessage() {}

func (x *QueryInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInstancesRequest.ProtoReflect.Descriptor instead.
func (*QueryInstancesRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{14}
}

func (x *QueryInstancesRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *QueryInstancesRequest) GetAttributeFilters() map[string]*AttributeValue {
	if x != nil {
		return x.AttributeFilters
	}
	return nil
}

func (x *QueryInstancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryInstancesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *QueryInstancesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type QueryInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInstancesResponse) Reset() {
	*x = QueryInstancesResponse{}
	mi := &file_flexitype_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInstancesResponse) ProtoMessage() {}

func (x *QueryInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInstancesResponse.ProtoReflect.Descriptor instead.
func (*QueryInstancesResponse) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{15}
}

func (x *QueryInstancesResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *QueryInstancesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateInstanceRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Id              string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeValues map[string]*AttributeValue `protobuf:"bytes,2,rep,name=attribute_values,json=attributeValues,proto3" json:"attribute_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateInstanceRequest) Reset() {
	*x = UpdateInstanceRequest{}
	mi := &file_flexitype_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceRequest) ProtoMessage() {}

func (x *UpdateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInstanceRequest) GetAttributeValues() map[string]*AttributeValue {
	if x != nil {
		return x.AttributeValues
	}
	return nil
}

type ArchiveInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveInstanceRequest) Reset() {
	*x = ArchiveInstanceRequest{}
	mi := &file_flexitype_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveInstanceRequest) ProtoMessage() {}

func (x *ArchiveInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveInstanceRequest.ProtoReflect.Descriptor instead.
func (*ArchiveInstanceRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{17}
}

func (x *ArchiveInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnarchiveInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveInstanceRequest) Reset() {
	*x = UnarchiveInstanceRequest{}
	mi := &file_flexitype_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveInstanceRequest) ProtoMessage() {}

func (x *UnarchiveInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveInstanceRequest.ProtoReflect.Descriptor instead.
func (*UnarchiveInstanceRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{18}
}

func (x *UnarchiveInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceResponse) Reset() {
	*x = InstanceResponse{}
	mi := &file_flexitype_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceResponse) ProtoMessage() {}

func (x *InstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceResponse.ProtoReflect.Descriptor instead.
func (*InstanceResponse) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{19}
}

func (x *InstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// Schema operations
type ExportTypeSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTypeSchemaRequest) Reset() {
	*x = ExportTypeSchemaRequest{}
	mi := &file_flexitype_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTypeSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTypeSchemaRequest) ProtoMessage() {}

func (x *ExportTypeSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTypeSchemaRequest.ProtoReflect.Descriptor instead.
func (*ExportTypeSchemaRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{20}
}

func (x *ExportTypeSchemaRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

type ImportTypeSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YamlContent   string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportTypeSchemaRequest) Reset() {
	*x = ImportTypeSchemaRequest{}
	mi := &file_flexitype_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTypeSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTypeSchemaRequest) ProtoMessage() {}

func (x *ImportTypeSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTypeSchemaRequest.ProtoReflect.Descriptor instead.
func (*ImportTypeSchemaRequest) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{21}
}

func (x *ImportTypeSchemaRequest) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YamlContent   string                 `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_flexitype_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{22}
}

func (x *SchemaResponse) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

// Type definition
type TypeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	ParentTypeId  string                 `protobuf:"bytes,5,opt,name=parent_type_id,json=parentTypeId,proto3" json:"parent_type_id,omitempty"`
	Attributes    []*AttributeDefinition `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // ISO8601 formatted timestamp when the type was created
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // ISO8601 formatted timestamp when the type was last updated
	ArchivedAt    string                 `protobuf:"bytes,9,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"` // ISO8601 formatted timestamp when the type was archived
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDefinition) Reset() {
	*x = TypeDefinition{}
	mi := &file_flexitype_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinition) ProtoMessage() {}

func (x *TypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinition.ProtoReflect.Descriptor instead.
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{23}
}

func (x *TypeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TypeDefinition) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TypeDefinition) GetParentTypeId() string {
	if x != nil {
		return x.ParentTypeId
	}
	return ""
}

func (x *TypeDefinition) GetAttributes() []*AttributeDefinition {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TypeDefinition) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TypeDefinition) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TypeDefinition) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

// Attribute definition
type AttributeDefinition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DataType        string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Required        bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue    *AttributeValue        `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	MultiValued     bool                   `protobuf:"varint,7,opt,name=multi_valued,json=multiValued,proto3" json:"multi_valued,omitempty"`
	Disabled        bool                   `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Cascades        []*CascadeDefinition   `protobuf:"bytes,13,rep,name=cascades,proto3" json:"cascades,omitempty"` // Multiple cascades for inheritance
	ValidationRules []*ValidationRule      `protobuf:"bytes,10,rep,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO8601 formatted timestamp when the attribute was created
	UpdatedAt       string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO8601 formatted timestamp when the attribute was last updated
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	mi := &file_flexitype_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{24}
}

func (x *AttributeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttributeDefinition) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *AttributeDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AttributeDefinition) GetDefaultValue() *AttributeValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *AttributeDefinition) GetMultiValued() bool {
	if x != nil {
		return x.MultiValued
	}
	return false
}

func (x *AttributeDefinition) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *AttributeDefinition) GetCascades() []*CascadeDefinition {
	if x != nil {
		return x.Cascades
	}
	return nil
}

func (x *AttributeDefinition) GetValidationRules() []*ValidationRule {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

func (x *AttributeDefinition) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AttributeDefinition) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Cascade definition for inheritance
type CascadeDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Behavior         string                 `protobuf:"bytes,2,opt,name=behavior,proto3" json:"behavior,omitempty"`                                         // "inherit", "override", "disabled", or validation behaviors
	Logic            string                 `protobuf:"bytes,3,opt,name=logic,proto3" json:"logic,omitempty"`                                               // Logic expression
	Weight           int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`                                            // Execution weight (higher weight = higher priority)
	ValidationConfig *ValidationConfig      `protobuf:"bytes,5,opt,name=validation_config,json=validationConfig,proto3" json:"validation_config,omitempty"` // Optional validation configuration
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CascadeDefinition) Reset() {
	*x = CascadeDefinition{}
	mi := &file_flexitype_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CascadeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CascadeDefinition) ProtoMessage() {}

func (x *CascadeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CascadeDefinition.ProtoReflect.Descriptor instead.
func (*CascadeDefinition) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{25}
}

func (x *CascadeDefinition) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CascadeDefinition) GetBehavior() string {
	if x != nil {
		return x.Behavior
	}
	return ""
}

func (x *CascadeDefinition) GetLogic() string {
	if x != nil {
		return x.Logic
	}
	return ""
}

func (x *CascadeDefinition) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CascadeDefinition) GetValidationConfig() *ValidationConfig {
	if x != nil {
		return x.ValidationConfig
	}
	return nil
}

// Validation configuration for validation cascades
type ValidationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                   // "REQUIRE", "ENABLE", "ENUM_VALUES", "LENGTH", "PATTERN", "RANGE", etc.
	TargetField   string                 `protobuf:"bytes,2,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"`      // Target field for the validation
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`                                   // Array of string values (used for enum values)
	StringValue   string                 `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`      // String value (used for patterns)
	NumericValue  float64                `protobuf:"fixed64,5,opt,name=numeric_value,json=numericValue,proto3" json:"numeric_value,omitempty"` // Numeric value (used for range limits)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationConfig) Reset() {
	*x = ValidationConfig{}
	mi := &file_flexitype_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationConfig) ProtoMessage() {}

func (x *ValidationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationConfig.ProtoReflect.Descriptor instead.
func (*ValidationConfig) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{26}
}

func (x *ValidationConfig) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ValidationConfig) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

func (x *ValidationConfig) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ValidationConfig) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ValidationConfig) GetNumericValue() float64 {
	if x != nil {
		return x.NumericValue
	}
	return 0
}

// Multiple cascades definition for attributes
type MultiCascadeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cascades      []*CascadeDefinition   `protobuf:"bytes,1,rep,name=cascades,proto3" json:"cascades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiCascadeDefinition) Reset() {
	*x = MultiCascadeDefinition{}
	mi := &file_flexitype_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiCascadeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCascadeDefinition) ProtoMessage() {}

func (x *MultiCascadeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCascadeDefinition.ProtoReflect.Descriptor instead.
func (*MultiCascadeDefinition) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{27}
}

func (x *MultiCascadeDefinition) GetCascades() []*CascadeDefinition {
	if x != nil {
		return x.Cascades
	}
	return nil
}

// Validation rule
type ValidationRule struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          string                     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameters    map[string]*AttributeValue `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRule) Reset() {
	*x = ValidationRule{}
	mi := &file_flexitype_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRule) ProtoMessage() {}

func (x *ValidationRule) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRule.ProtoReflect.Descriptor instead.
func (*ValidationRule) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{28}
}

func (x *ValidationRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ValidationRule) GetParameters() map[string]*AttributeValue {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Instance
type Instance struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Id              string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId          string                     `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeVersion     int32                      `protobuf:"varint,3,opt,name=type_version,json=typeVersion,proto3" json:"type_version,omitempty"`
	AttributeValues map[string]*AttributeValue `protobuf:"bytes,4,rep,name=attribute_values,json=attributeValues,proto3" json:"attribute_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt       string                     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // ISO8601 formatted timestamp when the instance was created
	UpdatedAt       string                     `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // ISO8601 formatted timestamp when the instance was last updated
	ArchivedAt      string                     `protobuf:"bytes,7,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"` // ISO8601 formatted timestamp when the instance was archived
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_flexitype_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{29}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Instance) GetTypeVersion() int32 {
	if x != nil {
		return x.TypeVersion
	}
	return 0
}

func (x *Instance) GetAttributeValues() map[string]*AttributeValue {
	if x != nil {
		return x.AttributeValues
	}
	return nil
}

func (x *Instance) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Instance) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Instance) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

// Attribute value - can be of different types
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringValue
	//	*AttributeValue_IntValue
	//	*AttributeValue_FloatValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_DateValue
	//	*AttributeValue_ObjectValue
	//	*AttributeValue_ArrayValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_flexitype_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{30}
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AttributeValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AttributeValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AttributeValue) GetDateValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

func (x *AttributeValue) GetObjectValue() *ObjectValue {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_ObjectValue); ok {
			return x.ObjectValue
		}
	}
	return nil
}

func (x *AttributeValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AttributeValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_DateValue struct {
	DateValue string `protobuf:"bytes,5,opt,name=date_value,json=dateValue,proto3,oneof"` // ISO8601 formatted string
}

type AttributeValue_ObjectValue struct {
	ObjectValue *ObjectValue `protobuf:"bytes,6,opt,name=object_value,json=objectValue,proto3,oneof"`
}

type AttributeValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,7,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_IntValue) isAttributeValue_Value() {}

func (*AttributeValue_FloatValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_DateValue) isAttributeValue_Value() {}

func (*AttributeValue_ObjectValue) isAttributeValue_Value() {}

func (*AttributeValue_ArrayValue) isAttributeValue_Value() {}

type ObjectValue struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fields        map[string]*AttributeValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectValue) Reset() {
	*x = ObjectValue{}
	mi := &file_flexitype_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectValue) ProtoMessage() {}

func (x *ObjectValue) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectValue.ProtoReflect.Descriptor instead.
func (*ObjectValue) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{31}
}

func (x *ObjectValue) GetFields() map[string]*AttributeValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AttributeValue      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_flexitype_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_flexitype_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_flexitype_proto_rawDescGZIP(), []int{32}
}

func (x *ArrayValue) GetValues() []*AttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_flexitype_proto protoreflect.FileDescriptor

const file_flexitype_proto_rawDesc = "" +
	"\n" +
	"\x0fflexitype.proto\x12\fflexitype.v1\"\x7f\n" +
	"\x11CreateTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0eparent_type_id\x18\x04 \x01(\tR\fparentTypeId\" \n" +
	"\x0eGetTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x10ListTypesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12)\n" +
	"\x10include_archived\x18\x03 \x01(\bR\x0fincludeArchived\"o\n" +
	"\x11ListTypesResponse\x122\n" +
	"\x05types\x18\x01 \x03(\v2\x1c.flexitype.v1.TypeDefinitionR\x05types\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x7f\n" +
	"\x11UpdateTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0eparent_type_id\x18\x04 \x01(\tR\fparentTypeId\"$\n" +
	"\x12ArchiveTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14UnarchiveTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\fTypeResponse\x120\n" +
	"\x04type\x18\x01 \x01(\v2\x1c.flexitype.v1.TypeDefinitionR\x04type\"o\n" +
	"\x13AddAttributeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12?\n" +
	"\tattribute\x18\x02 \x01(\v2!.flexitype.v1.AttributeDefinitionR\tattribute\"r\n" +
	"\x16UpdateAttributeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12?\n" +
	"\tattribute\x18\x02 \x01(\v2!.flexitype.v1.AttributeDefinitionR\tattribute\"T\n" +
	"\x16DeleteAttributeRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12!\n" +
	"\fattribute_id\x18\x02 \x01(\tR\vattributeId\"z\n" +
	" SetAttributeDisabledStateRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12!\n" +
	"\fattribute_id\x18\x02 \x01(\tR\vattributeId\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\"\x87\x02\n" +
	"\x15CreateInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12c\n" +
	"\x10attribute_values\x18\x03 \x03(\v28.flexitype.v1.CreateInstanceRequest.AttributeValuesEntryR\x0fattributeValues\x1a`\n" +
	"\x14AttributeValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.flexitype.v1.AttributeValueR\x05value:\x028\x01\"$\n" +
	"\x12GetInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe2\x02\n" +
	"\x15QueryInstancesRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12f\n" +
	"\x11attribute_filters\x18\x02 \x03(\v29.flexitype.v1.QueryInstancesRequest.AttributeFiltersEntryR\x10attributeFilters\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12)\n" +
	"\x10include_archived\x18\x05 \x01(\bR\x0fincludeArchived\x1aa\n" +
	"\x15AttributeFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.flexitype.v1.AttributeValueR\x05value:\x028\x01\"v\n" +
	"\x16QueryInstancesResponse\x124\n" +
	"\tinstances\x18\x01 \x03(\v2\x16.flexitype.v1.InstanceR\tinstances\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xee\x01\n" +
	"\x15UpdateInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12c\n" +
	"\x10attribute_values\x18\x02 \x03(\v28.flexitype.v1.UpdateInstanceRequest.AttributeValuesEntryR\x0fattributeValues\x1a`\n" +
	"\x14AttributeValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.flexitype.v1.AttributeValueR\x05value:\x028\x01\"(\n" +
	"\x16ArchiveInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18UnarchiveInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x10InstanceResponse\x122\n" +
	"\binstance\x18\x01 \x01(\v2\x16.flexitype.v1.InstanceR\binstance\"2\n" +
	"\x17ExportTypeSchemaRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\"<\n" +
	"\x17ImportTypeSchemaRequest\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\"3\n" +
	"\x0eSchemaResponse\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\tR\vyamlContent\"\xb8\x02\n" +
	"\x0eTypeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12$\n" +
	"\x0eparent_type_id\x18\x05 \x01(\tR\fparentTypeId\x12A\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2!.flexitype.v1.AttributeDefinitionR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\varchived_at\x18\t \x01(\tR\n" +
	"archivedAt\"\xda\x03\n" +
	"\x13AttributeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12A\n" +
	"\rdefault_value\x18\x06 \x01(\v2\x1c.flexitype.v1.AttributeValueR\fdefaultValue\x12!\n" +
	"\fmulti_valued\x18\a \x01(\bR\vmultiValued\x12\x1a\n" +
	"\bdisabled\x18\b \x01(\bR\bdisabled\x12;\n" +
	"\bcascades\x18\r \x03(\v2\x1f.flexitype.v1.CascadeDefinitionR\bcascades\x12G\n" +
	"\x10validation_rules\x18\n" +
	" \x03(\v2\x1c.flexitype.v1.ValidationRuleR\x0fvalidationRules\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xc4\x01\n" +
	"\x11CascadeDefinition\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bbehavior\x18\x02 \x01(\tR\bbehavior\x12\x14\n" +
	"\x05logic\x18\x03 \x01(\tR\x05logic\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12K\n" +
	"\x11validation_config\x18\x05 \x01(\v2\x1e.flexitype.v1.ValidationConfigR\x10validationConfig\"\xad\x01\n" +
	"\x10ValidationConfig\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12!\n" +
	"\ftarget_field\x18\x02 \x01(\tR\vtargetField\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\x12!\n" +
	"\fstring_value\x18\x04 \x01(\tR\vstringValue\x12#\n" +
	"\rnumeric_value\x18\x05 \x01(\x01R\fnumericValue\"U\n" +
	"\x16MultiCascadeDefinition\x12;\n" +
	"\bcascades\x18\x01 \x03(\v2\x1f.flexitype.v1.CascadeDefinitionR\bcascades\"\xcf\x01\n" +
	"\x0eValidationRule\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12L\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2,.flexitype.v1.ValidationRule.ParametersEntryR\n" +
	"parameters\x1a[\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.flexitype.v1.AttributeValueR\x05value:\x028\x01\"\xef\x02\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12!\n" +
	"\ftype_version\x18\x03 \x01(\x05R\vtypeVersion\x12V\n" +
	"\x10attribute_values\x18\x04 \x03(\v2+.flexitype.v1.Instance.AttributeValuesEntryR\x0fattributeValues\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\varchived_at\x18\a \x01(\tR\n" +
	"archivedAt\x1a`\n" +
	"\x14AttributeValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.flexitype.v1.AttributeValueR\x05value:\x028\x01\"\xbf\x02\n" +
	"\x0eAttributeValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x05 \x01(\tH\x00R\tdateValue\x12>\n" +
	"\fobject_value\x18\x06 \x01(\v2\x19.flexitype.v1.ObjectValueH\x00R\vobjectValue\x12;\n" +
	"\varray_value\x18\a \x01(\v2\x18.flexitype.v1.ArrayValueH\x00R\n" +
	"arrayValueB\a\n" +
	"\x05value\"\xa5\x01\n" +
	"\vObjectValue\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.flexitype.v1.ObjectValue.FieldsEntryR\x06fields\x1aW\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.flexitype.v1.AttributeValueR\x05value:\x028\x01\"B\n" +
	"\n" +
	"ArrayValue\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.flexitype.v1.AttributeValueR\x06values2\xfd\v\n" +
	"\x10FlexiTypeService\x12I\n" +
	"\n" +
	"CreateType\x12\x1f.flexitype.v1.CreateTypeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12C\n" +
	"\aGetType\x12\x1c.flexitype.v1.GetTypeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12L\n" +
	"\tListTypes\x12\x1e.flexitype.v1.ListTypesRequest\x1a\x1f.flexitype.v1.ListTypesResponse\x12I\n" +
	"\n" +
	"UpdateType\x12\x1f.flexitype.v1.UpdateTypeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12K\n" +
	"\vArchiveType\x12 .flexitype.v1.ArchiveTypeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12O\n" +
	"\rUnarchiveType\x12\".flexitype.v1.UnarchiveTypeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12M\n" +
	"\fAddAttribute\x12!.flexitype.v1.AddAttributeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12S\n" +
	"\x0fUpdateAttribute\x12$.flexitype.v1.UpdateAttributeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12S\n" +
	"\x0fDeleteAttribute\x12$.flexitype.v1.DeleteAttributeRequest\x1a\x1a.flexitype.v1.TypeResponse\x12g\n" +
	"\x19SetAttributeDisabledState\x12..flexitype.v1.SetAttributeDisabledStateRequest\x1a\x1a.flexitype.v1.TypeResponse\x12U\n" +
	"\x0eCreateInstance\x12#.flexitype.v1.CreateInstanceRequest\x1a\x1e.flexitype.v1.InstanceResponse\x12O\n" +
	"\vGetInstance\x12 .flexitype.v1.GetInstanceRequest\x1a\x1e.flexitype.v1.InstanceResponse\x12[\n" +
	"\x0eQueryInstances\x12#.flexitype.v1.QueryInstancesRequest\x1a$.flexitype.v1.QueryInstancesResponse\x12U\n" +
	"\x0eUpdateInstance\x12#.flexitype.v1.UpdateInstanceRequest\x1a\x1e.flexitype.v1.InstanceResponse\x12W\n" +
	"\x0fArchiveInstance\x12$.flexitype.v1.ArchiveInstanceRequest\x1a\x1e.flexitype.v1.InstanceResponse\x12[\n" +
	"\x11UnarchiveInstance\x12&.flexitype.v1.UnarchiveInstanceRequest\x1a\x1e.flexitype.v1.InstanceResponse\x12W\n" +
	"\x10ExportTypeSchema\x12%.flexitype.v1.ExportTypeSchemaRequest\x1a\x1c.flexitype.v1.SchemaResponse\x12U\n" +
	"\x10ImportTypeSchema\x12%.flexitype.v1.ImportTypeSchemaRequest\x1a\x1a.flexitype.v1.TypeResponseB9Z7github.com/zac300/flexitype/api/flexitypev1;flexitypev1b\x06proto3"

var (
	file_flexitype_proto_rawDescOnce sync.Once
	file_flexitype_proto_rawDescData []byte
)

func file_flexitype_proto_rawDescGZIP() []byte {
	file_flexitype_proto_rawDescOnce.Do(func() {
		file_flexitype_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flexitype_proto_rawDesc), len(file_flexitype_proto_rawDesc)))
	})
	return file_flexitype_proto_rawDescData
}

var file_flexitype_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_flexitype_proto_goTypes = []any{
	(*CreateTypeRequest)(nil),                // 0: flexitype.v1.CreateTypeRequest
	(*GetTypeRequest)(nil),                   // 1: flexitype.v1.GetTypeRequest
	(*ListTypesRequest)(nil),                 // 2: flexitype.v1.ListTypesRequest
	(*ListTypesResponse)(nil),                // 3: flexitype.v1.ListTypesResponse
	(*UpdateTypeRequest)(nil),                // 4: flexitype.v1.UpdateTypeRequest
	(*ArchiveTypeRequest)(nil),               // 5: flexitype.v1.ArchiveTypeRequest
	(*UnarchiveTypeRequest)(nil),             // 6: flexitype.v1.UnarchiveTypeRequest
	(*TypeResponse)(nil),                     // 7: flexitype.v1.TypeResponse
	(*AddAttributeRequest)(nil),              // 8: flexitype.v1.AddAttributeRequest
	(*UpdateAttributeRequest)(nil),           // 9: flexitype.v1.UpdateAttributeRequest
	(*DeleteAttributeRequest)(nil),           // 10: flexitype.v1.DeleteAttributeRequest
	(*SetAttributeDisabledStateRequest)(nil), // 11: flexitype.v1.SetAttributeDisabledStateRequest
	(*CreateInstanceRequest)(nil),            // 12: flexitype.v1.CreateInstanceRequest
	(*GetInstanceRequest)(nil),               // 13: flexitype.v1.GetInstanceRequest
	(*QueryInstancesRequest)(nil),            // 14: flexitype.v1.QueryInstancesRequest
	(*QueryInstancesResponse)(nil),           // 15: flexitype.v1.QueryInstancesResponse
	(*UpdateInstanceRequest)(nil),            // 16: flexitype.v1.UpdateInstanceRequest
	(*ArchiveInstanceRequest)(nil),           // 17: flexitype.v1.ArchiveInstanceRequest
	(*UnarchiveInstanceRequest)(nil),         // 18: flexitype.v1.UnarchiveInstanceRequest
	(*InstanceResponse)(nil),                 // 19: flexitype.v1.InstanceResponse
	(*ExportTypeSchemaRequest)(nil),          // 20: flexitype.v1.ExportTypeSchemaRequest
	(*ImportTypeSchemaRequest)(nil),          // 21: flexitype.v1.ImportTypeSchemaRequest
	(*SchemaResponse)(nil),                   // 22: flexitype.v1.SchemaResponse
	(*TypeDefinition)(nil),                   // 23: flexitype.v1.TypeDefinition
	(*AttributeDefinition)(nil),              // 24: flexitype.v1.AttributeDefinition
	(*CascadeDefinition)(nil),                // 25: flexitype.v1.CascadeDefinition
	(*ValidationConfig)(nil),                 // 26: flexitype.v1.ValidationConfig
	(*MultiCascadeDefinition)(nil),           // 27: flexitype.v1.MultiCascadeDefinition
	(*ValidationRule)(nil),                   // 28: flexitype.v1.ValidationRule
	(*Instance)(nil),                         // 29: flexitype.v1.Instance
	(*AttributeValue)(nil),                   // 30: flexitype.v1.AttributeValue
	(*ObjectValue)(nil),                      // 31: flexitype.v1.ObjectValue
	(*ArrayValue)(nil),                       // 32: flexitype.v1.ArrayValue
	nil,                                      // 33: flexitype.v1.CreateInstanceRequest.AttributeValuesEntry
	nil,                                      // 34: flexitype.v1.QueryInstancesRequest.AttributeFiltersEntry
	nil,                                      // 35: flexitype.v1.UpdateInstanceRequest.AttributeValuesEntry
	nil,                                      // 36: flexitype.v1.ValidationRule.ParametersEntry
	nil,                                      // 37: flexitype.v1.Instance.AttributeValuesEntry
	nil,                                      // 38: flexitype.v1.ObjectValue.FieldsEntry
}
var file_flexitype_proto_depIdxs = []int32{
	23, // 0: flexitype.v1.ListTypesResponse.types:type_name -> flexitype.v1.TypeDefinition
	23, // 1: flexitype.v1.TypeResponse.type:type_name -> flexitype.v1.TypeDefinition
	24, // 2: flexitype.v1.AddAttributeRequest.attribute:type_name -> flexitype.v1.AttributeDefinition
	24, // 3: flexitype.v1.UpdateAttributeRequest.attribute:type_name -> flexitype.v1.AttributeDefinition
	33, // 4: flexitype.v1.CreateInstanceRequest.attribute_values:type_name -> flexitype.v1.CreateInstanceRequest.AttributeValuesEntry
	34, // 5: flexitype.v1.QueryInstancesRequest.attribute_filters:type_name -> flexitype.v1.QueryInstancesRequest.AttributeFiltersEntry
	29, // 6: flexitype.v1.QueryInstancesResponse.instances:type_name -> flexitype.v1.Instance
	35, // 7: flexitype.v1.UpdateInstanceRequest.attribute_values:type_name -> flexitype.v1.UpdateInstanceRequest.AttributeValuesEntry
	29, // 8: flexitype.v1.InstanceResponse.instance:type_name -> flexitype.v1.Instance
	24, // 9: flexitype.v1.TypeDefinition.attributes:type_name -> flexitype.v1.AttributeDefinition
	30, // 10: flexitype.v1.AttributeDefinition.default_value:type_name -> flexitype.v1.AttributeValue
	25, // 11: flexitype.v1.AttributeDefinition.cascades:type_name -> flexitype.v1.CascadeDefinition
	28, // 12: flexitype.v1.AttributeDefinition.validation_rules:type_name -> flexitype.v1.ValidationRule
	26, // 13: flexitype.v1.CascadeDefinition.validation_config:type_name -> flexitype.v1.ValidationConfig
	25, // 14: flexitype.v1.MultiCascadeDefinition.cascades:type_name -> flexitype.v1.CascadeDefinition
	36, // 15: flexitype.v1.ValidationRule.parameters:type_name -> flexitype.v1.ValidationRule.ParametersEntry
	37, // 16: flexitype.v1.Instance.attribute_values:type_name -> flexitype.v1.Instance.AttributeValuesEntry
	31, // 17: flexitype.v1.AttributeValue.object_value:type_name -> flexitype.v1.ObjectValue
	32, // 18: flexitype.v1.AttributeValue.array_value:type_name -> flexitype.v1.ArrayValue
	38, // 19: flexitype.v1.ObjectValue.fields:type_name -> flexitype.v1.ObjectValue.FieldsEntry
	30, // 20: flexitype.v1.ArrayValue.values:type_name -> flexitype.v1.AttributeValue
	30, // 21: flexitype.v1.CreateInstanceRequest.AttributeValuesEntry.value:type_name -> flexitype.v1.AttributeValue
	30, // 22: flexitype.v1.QueryInstancesRequest.AttributeFiltersEntry.value:type_name -> flexitype.v1.AttributeValue
	30, // 23: flexitype.v1.UpdateInstanceRequest.AttributeValuesEntry.value:type_name -> flexitype.v1.AttributeValue
	30, // 24: flexitype.v1.ValidationRule.ParametersEntry.value:type_name -> flexitype.v1.AttributeValue
	30, // 25: flexitype.v1.Instance.AttributeValuesEntry.value:type_name -> flexitype.v1.AttributeValue
	30, // 26: flexitype.v1.ObjectValue.FieldsEntry.value:type_name -> flexitype.v1.AttributeValue
	0,  // 27: flexitype.v1.FlexiTypeService.CreateType:input_type -> flexitype.v1.CreateTypeRequest
	1,  // 28: flexitype.v1.FlexiTypeService.GetType:input_type -> flexitype.v1.GetTypeRequest
	2,  // 29: flexitype.v1.FlexiTypeService.ListTypes:input_type -> flexitype.v1.ListTypesRequest
	4,  // 30: flexitype.v1.FlexiTypeService.UpdateType:input_type -> flexitype.v1.UpdateTypeRequest
	5,  // 31: flexitype.v1.FlexiTypeService.ArchiveType:input_type -> flexitype.v1.ArchiveTypeRequest
	6,  // 32: flexitype.v1.FlexiTypeService.UnarchiveType:input_type -> flexitype.v1.UnarchiveTypeRequest
	8,  // 33: flexitype.v1.FlexiTypeService.AddAttribute:input_type -> flexitype.v1.AddAttributeRequest
	9,  // 34: flexitype.v1.FlexiTypeService.UpdateAttribute:input_type -> flexitype.v1.UpdateAttributeRequest
	10, // 35: flexitype.v1.FlexiTypeService.DeleteAttribute:input_type -> flexitype.v1.DeleteAttributeRequest
	11, // 36: flexitype.v1.FlexiTypeService.SetAttributeDisabledState:input_type -> flexitype.v1.SetAttributeDisabledStateRequest
	12, // 37: flexitype.v1.FlexiTypeService.CreateInstance:input_type -> flexitype.v1.CreateInstanceRequest
	13, // 38: flexitype.v1.FlexiTypeService.GetInstance:input_type -> flexitype.v1.GetInstanceRequest
	14, // 39: flexitype.v1.FlexiTypeService.QueryInstances:input_type -> flexitype.v1.QueryInstancesRequest
	16, // 40: flexitype.v1.FlexiTypeService.UpdateInstance:input_type -> flexitype.v1.UpdateInstanceRequest
	17, // 41: flexitype.v1.FlexiTypeService.ArchiveInstance:input_type -> flexitype.v1.ArchiveInstanceRequest
	18, // 42: flexitype.v1.FlexiTypeService.UnarchiveInstance:input_type -> flexitype.v1.UnarchiveInstanceRequest
	20, // 43: flexitype.v1.FlexiTypeService.ExportTypeSchema:input_type -> flexitype.v1.ExportTypeSchemaRequest
	21, // 44: flexitype.v1.FlexiTypeService.ImportTypeSchema:input_type -> flexitype.v1.ImportTypeSchemaRequest
	7,  // 45: flexitype.v1.FlexiTypeService.CreateType:output_type -> flexitype.v1.TypeResponse
	7,  // 46: flexitype.v1.FlexiTypeService.GetType:output_type -> flexitype.v1.TypeResponse
	3,  // 47: flexitype.v1.FlexiTypeService.ListTypes:output_type -> flexitype.v1.ListTypesResponse
	7,  // 48: flexitype.v1.FlexiTypeService.UpdateType:output_type -> flexitype.v1.TypeResponse
	7,  // 49: flexitype.v1.FlexiTypeService.ArchiveType:output_type -> flexitype.v1.TypeResponse
	7,  // 50: flexitype.v1.FlexiTypeService.UnarchiveType:output_type -> flexitype.v1.TypeResponse
	7,  // 51: flexitype.v1.FlexiTypeService.AddAttribute:output_type -> flexitype.v1.TypeResponse
	7,  // 52: flexitype.v1.FlexiTypeService.UpdateAttribute:output_type -> flexitype.v1.TypeResponse
	7,  // 53: flexitype.v1.FlexiTypeService.DeleteAttribute:output_type -> flexitype.v1.TypeResponse
	7,  // 54: flexitype.v1.FlexiTypeService.SetAttributeDisabledState:output_type -> flexitype.v1.TypeResponse
	19, // 55: flexitype.v1.FlexiTypeService.CreateInstance:output_type -> flexitype.v1.InstanceResponse
	19, // 56: flexitype.v1.FlexiTypeService.GetInstance:output_type -> flexitype.v1.InstanceResponse
	15, // 57: flexitype.v1.FlexiTypeService.QueryInstances:output_type -> flexitype.v1.QueryInstancesResponse
	19, // 58: flexitype.v1.FlexiTypeService.UpdateInstance:output_type -> flexitype.v1.InstanceResponse
	19, // 59: flexitype.v1.FlexiTypeService.ArchiveInstance:output_type -> flexitype.v1.InstanceResponse
	19, // 60: flexitype.v1.FlexiTypeService.UnarchiveInstance:output_type -> flexitype.v1.InstanceResponse
	22, // 61: flexitype.v1.FlexiTypeService.ExportTypeSchema:output_type -> flexitype.v1.SchemaResponse
	7,  // 62: flexitype.v1.FlexiTypeService.ImportTypeSchema:output_type -> flexitype.v1.TypeResponse
	45, // [45:63] is the sub-list for method output_type
	27, // [27:45] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_flexitype_proto_init() }
func file_flexitype_proto_init() {
	if File_flexitype_proto != nil {
		return
	}
	file_flexitype_proto_msgTypes[30].OneofWrappers = []any{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_IntValue)(nil),
		(*AttributeValue_FloatValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_DateValue)(nil),
		(*AttributeValue_ObjectValue)(nil),
		(*AttributeValue_ArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flexitype_proto_rawDesc), len(file_flexitype_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flexitype_proto_goTypes,
		DependencyIndexes: file_flexitype_proto_depIdxs,
		MessageInfos:      file_flexitype_proto_msgTypes,
	}.Build()
	File_flexitype_proto = out.File
	file_flexitype_proto_goTypes = nil
	file_flexitype_proto_depIdxs = nil
}
