-- Cross-tenant index for the media-blob GC reference count.
--
-- +flexitype:no-transaction
--
-- MediaKeyRefCount / MediaKeyRefCounts count the live rows that reference an
-- object key ACROSS tenants (blob keys live in one shared namespace). The only
-- object-key index (000021) leads with tenant_id, so the cross-tenant count
-- could not seek: every media overwrite/remove paid a scan of all media rows
-- post-commit, and a right-to-erasure purge ran one such scan per purged key
-- inside the shared post-commit budget until the budget expired and the
-- receipt reported the remaining bytes unpurged.
--
-- Partial on live media rows, because the count reads exactly that set:
-- archived rows are deliberately not counted (see the domain port).
--
-- Built CONCURRENTLY: flexitype_attribute_value is the largest table in the
-- database, where a plain CREATE INDEX would take a lock conflicting with
-- every write.
--
-- A failed concurrent build leaves an INVALID namesake behind that
-- IF NOT EXISTS would then skip forever. The runner reaps such an index before
-- it replays this file (reapInvalidIndexes in migrate.go), scoped to
-- current_schema(). This file must NOT carry its own catalogue guard, and once
-- did: a DO block matched pg_class.relname with no pg_namespace join, so an
-- invalid index in ANY schema of the database made it fire, and its
-- unqualified DROP INDEX resolved through search_path — into a missing index
-- (42704, and with MigrateOnStart a boot loop) or into THIS schema's valid
-- index (a write-blocking drop).
--
-- That is the same block #517 removed from 000030, reintroduced here and
-- removed again. See TestMigrationsDoNotQueryTheCatalogueBlind.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_flexitype_attribute_value_media_key_live
    ON flexitype_attribute_value ((value_json->>'object_key'))
    WHERE data_type = 'media' AND archived_at IS NULL;
