// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: flexitype.proto

package flexitypev1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	flexitypev1 "github.com/zac300/flexitype/api/flexitypev1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// FlexiTypeServiceName is the fully-qualified name of the FlexiTypeService service.
	FlexiTypeServiceName = "flexitype.v1.FlexiTypeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FlexiTypeServiceCreateTypeProcedure is the fully-qualified name of the FlexiTypeService's
	// CreateType RPC.
	FlexiTypeServiceCreateTypeProcedure = "/flexitype.v1.FlexiTypeService/CreateType"
	// FlexiTypeServiceGetTypeProcedure is the fully-qualified name of the FlexiTypeService's GetType
	// RPC.
	FlexiTypeServiceGetTypeProcedure = "/flexitype.v1.FlexiTypeService/GetType"
	// FlexiTypeServiceListTypesProcedure is the fully-qualified name of the FlexiTypeService's
	// ListTypes RPC.
	FlexiTypeServiceListTypesProcedure = "/flexitype.v1.FlexiTypeService/ListTypes"
	// FlexiTypeServiceUpdateTypeProcedure is the fully-qualified name of the FlexiTypeService's
	// UpdateType RPC.
	FlexiTypeServiceUpdateTypeProcedure = "/flexitype.v1.FlexiTypeService/UpdateType"
	// FlexiTypeServiceArchiveTypeProcedure is the fully-qualified name of the FlexiTypeService's
	// ArchiveType RPC.
	FlexiTypeServiceArchiveTypeProcedure = "/flexitype.v1.FlexiTypeService/ArchiveType"
	// FlexiTypeServiceUnarchiveTypeProcedure is the fully-qualified name of the FlexiTypeService's
	// UnarchiveType RPC.
	FlexiTypeServiceUnarchiveTypeProcedure = "/flexitype.v1.FlexiTypeService/UnarchiveType"
	// FlexiTypeServiceAddAttributeProcedure is the fully-qualified name of the FlexiTypeService's
	// AddAttribute RPC.
	FlexiTypeServiceAddAttributeProcedure = "/flexitype.v1.FlexiTypeService/AddAttribute"
	// FlexiTypeServiceUpdateAttributeProcedure is the fully-qualified name of the FlexiTypeService's
	// UpdateAttribute RPC.
	FlexiTypeServiceUpdateAttributeProcedure = "/flexitype.v1.FlexiTypeService/UpdateAttribute"
	// FlexiTypeServiceDeleteAttributeProcedure is the fully-qualified name of the FlexiTypeService's
	// DeleteAttribute RPC.
	FlexiTypeServiceDeleteAttributeProcedure = "/flexitype.v1.FlexiTypeService/DeleteAttribute"
	// FlexiTypeServiceSetAttributeDisabledStateProcedure is the fully-qualified name of the
	// FlexiTypeService's SetAttributeDisabledState RPC.
	FlexiTypeServiceSetAttributeDisabledStateProcedure = "/flexitype.v1.FlexiTypeService/SetAttributeDisabledState"
	// FlexiTypeServiceCreateInstanceProcedure is the fully-qualified name of the FlexiTypeService's
	// CreateInstance RPC.
	FlexiTypeServiceCreateInstanceProcedure = "/flexitype.v1.FlexiTypeService/CreateInstance"
	// FlexiTypeServiceGetInstanceProcedure is the fully-qualified name of the FlexiTypeService's
	// GetInstance RPC.
	FlexiTypeServiceGetInstanceProcedure = "/flexitype.v1.FlexiTypeService/GetInstance"
	// FlexiTypeServiceQueryInstancesProcedure is the fully-qualified name of the FlexiTypeService's
	// QueryInstances RPC.
	FlexiTypeServiceQueryInstancesProcedure = "/flexitype.v1.FlexiTypeService/QueryInstances"
	// FlexiTypeServiceUpdateInstanceProcedure is the fully-qualified name of the FlexiTypeService's
	// UpdateInstance RPC.
	FlexiTypeServiceUpdateInstanceProcedure = "/flexitype.v1.FlexiTypeService/UpdateInstance"
	// FlexiTypeServiceArchiveInstanceProcedure is the fully-qualified name of the FlexiTypeService's
	// ArchiveInstance RPC.
	FlexiTypeServiceArchiveInstanceProcedure = "/flexitype.v1.FlexiTypeService/ArchiveInstance"
	// FlexiTypeServiceUnarchiveInstanceProcedure is the fully-qualified name of the FlexiTypeService's
	// UnarchiveInstance RPC.
	FlexiTypeServiceUnarchiveInstanceProcedure = "/flexitype.v1.FlexiTypeService/UnarchiveInstance"
	// FlexiTypeServiceExportTypeSchemaProcedure is the fully-qualified name of the FlexiTypeService's
	// ExportTypeSchema RPC.
	FlexiTypeServiceExportTypeSchemaProcedure = "/flexitype.v1.FlexiTypeService/ExportTypeSchema"
	// FlexiTypeServiceImportTypeSchemaProcedure is the fully-qualified name of the FlexiTypeService's
	// ImportTypeSchema RPC.
	FlexiTypeServiceImportTypeSchemaProcedure = "/flexitype.v1.FlexiTypeService/ImportTypeSchema"
)

// FlexiTypeServiceClient is a client for the flexitype.v1.FlexiTypeService service.
type FlexiTypeServiceClient interface {
	// Type operations
	CreateType(context.Context, *connect_go.Request[flexitypev1.CreateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	GetType(context.Context, *connect_go.Request[flexitypev1.GetTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	ListTypes(context.Context, *connect_go.Request[flexitypev1.ListTypesRequest]) (*connect_go.Response[flexitypev1.ListTypesResponse], error)
	UpdateType(context.Context, *connect_go.Request[flexitypev1.UpdateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	ArchiveType(context.Context, *connect_go.Request[flexitypev1.ArchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	UnarchiveType(context.Context, *connect_go.Request[flexitypev1.UnarchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	// Attribute operations
	AddAttribute(context.Context, *connect_go.Request[flexitypev1.AddAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	UpdateAttribute(context.Context, *connect_go.Request[flexitypev1.UpdateAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	DeleteAttribute(context.Context, *connect_go.Request[flexitypev1.DeleteAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	SetAttributeDisabledState(context.Context, *connect_go.Request[flexitypev1.SetAttributeDisabledStateRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	// Instance operations
	CreateInstance(context.Context, *connect_go.Request[flexitypev1.CreateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	GetInstance(context.Context, *connect_go.Request[flexitypev1.GetInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	QueryInstances(context.Context, *connect_go.Request[flexitypev1.QueryInstancesRequest]) (*connect_go.Response[flexitypev1.QueryInstancesResponse], error)
	UpdateInstance(context.Context, *connect_go.Request[flexitypev1.UpdateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	ArchiveInstance(context.Context, *connect_go.Request[flexitypev1.ArchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	UnarchiveInstance(context.Context, *connect_go.Request[flexitypev1.UnarchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	// Schema operations
	ExportTypeSchema(context.Context, *connect_go.Request[flexitypev1.ExportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.SchemaResponse], error)
	ImportTypeSchema(context.Context, *connect_go.Request[flexitypev1.ImportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
}

// NewFlexiTypeServiceClient constructs a client for the flexitype.v1.FlexiTypeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFlexiTypeServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) FlexiTypeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &flexiTypeServiceClient{
		createType: connect_go.NewClient[flexitypev1.CreateTypeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceCreateTypeProcedure,
			opts...,
		),
		getType: connect_go.NewClient[flexitypev1.GetTypeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceGetTypeProcedure,
			opts...,
		),
		listTypes: connect_go.NewClient[flexitypev1.ListTypesRequest, flexitypev1.ListTypesResponse](
			httpClient,
			baseURL+FlexiTypeServiceListTypesProcedure,
			opts...,
		),
		updateType: connect_go.NewClient[flexitypev1.UpdateTypeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceUpdateTypeProcedure,
			opts...,
		),
		archiveType: connect_go.NewClient[flexitypev1.ArchiveTypeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceArchiveTypeProcedure,
			opts...,
		),
		unarchiveType: connect_go.NewClient[flexitypev1.UnarchiveTypeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceUnarchiveTypeProcedure,
			opts...,
		),
		addAttribute: connect_go.NewClient[flexitypev1.AddAttributeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceAddAttributeProcedure,
			opts...,
		),
		updateAttribute: connect_go.NewClient[flexitypev1.UpdateAttributeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceUpdateAttributeProcedure,
			opts...,
		),
		deleteAttribute: connect_go.NewClient[flexitypev1.DeleteAttributeRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceDeleteAttributeProcedure,
			opts...,
		),
		setAttributeDisabledState: connect_go.NewClient[flexitypev1.SetAttributeDisabledStateRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceSetAttributeDisabledStateProcedure,
			opts...,
		),
		createInstance: connect_go.NewClient[flexitypev1.CreateInstanceRequest, flexitypev1.InstanceResponse](
			httpClient,
			baseURL+FlexiTypeServiceCreateInstanceProcedure,
			opts...,
		),
		getInstance: connect_go.NewClient[flexitypev1.GetInstanceRequest, flexitypev1.InstanceResponse](
			httpClient,
			baseURL+FlexiTypeServiceGetInstanceProcedure,
			opts...,
		),
		queryInstances: connect_go.NewClient[flexitypev1.QueryInstancesRequest, flexitypev1.QueryInstancesResponse](
			httpClient,
			baseURL+FlexiTypeServiceQueryInstancesProcedure,
			opts...,
		),
		updateInstance: connect_go.NewClient[flexitypev1.UpdateInstanceRequest, flexitypev1.InstanceResponse](
			httpClient,
			baseURL+FlexiTypeServiceUpdateInstanceProcedure,
			opts...,
		),
		archiveInstance: connect_go.NewClient[flexitypev1.ArchiveInstanceRequest, flexitypev1.InstanceResponse](
			httpClient,
			baseURL+FlexiTypeServiceArchiveInstanceProcedure,
			opts...,
		),
		unarchiveInstance: connect_go.NewClient[flexitypev1.UnarchiveInstanceRequest, flexitypev1.InstanceResponse](
			httpClient,
			baseURL+FlexiTypeServiceUnarchiveInstanceProcedure,
			opts...,
		),
		exportTypeSchema: connect_go.NewClient[flexitypev1.ExportTypeSchemaRequest, flexitypev1.SchemaResponse](
			httpClient,
			baseURL+FlexiTypeServiceExportTypeSchemaProcedure,
			opts...,
		),
		importTypeSchema: connect_go.NewClient[flexitypev1.ImportTypeSchemaRequest, flexitypev1.TypeResponse](
			httpClient,
			baseURL+FlexiTypeServiceImportTypeSchemaProcedure,
			opts...,
		),
	}
}

// flexiTypeServiceClient implements FlexiTypeServiceClient.
type flexiTypeServiceClient struct {
	createType                *connect_go.Client[flexitypev1.CreateTypeRequest, flexitypev1.TypeResponse]
	getType                   *connect_go.Client[flexitypev1.GetTypeRequest, flexitypev1.TypeResponse]
	listTypes                 *connect_go.Client[flexitypev1.ListTypesRequest, flexitypev1.ListTypesResponse]
	updateType                *connect_go.Client[flexitypev1.UpdateTypeRequest, flexitypev1.TypeResponse]
	archiveType               *connect_go.Client[flexitypev1.ArchiveTypeRequest, flexitypev1.TypeResponse]
	unarchiveType             *connect_go.Client[flexitypev1.UnarchiveTypeRequest, flexitypev1.TypeResponse]
	addAttribute              *connect_go.Client[flexitypev1.AddAttributeRequest, flexitypev1.TypeResponse]
	updateAttribute           *connect_go.Client[flexitypev1.UpdateAttributeRequest, flexitypev1.TypeResponse]
	deleteAttribute           *connect_go.Client[flexitypev1.DeleteAttributeRequest, flexitypev1.TypeResponse]
	setAttributeDisabledState *connect_go.Client[flexitypev1.SetAttributeDisabledStateRequest, flexitypev1.TypeResponse]
	createInstance            *connect_go.Client[flexitypev1.CreateInstanceRequest, flexitypev1.InstanceResponse]
	getInstance               *connect_go.Client[flexitypev1.GetInstanceRequest, flexitypev1.InstanceResponse]
	queryInstances            *connect_go.Client[flexitypev1.QueryInstancesRequest, flexitypev1.QueryInstancesResponse]
	updateInstance            *connect_go.Client[flexitypev1.UpdateInstanceRequest, flexitypev1.InstanceResponse]
	archiveInstance           *connect_go.Client[flexitypev1.ArchiveInstanceRequest, flexitypev1.InstanceResponse]
	unarchiveInstance         *connect_go.Client[flexitypev1.UnarchiveInstanceRequest, flexitypev1.InstanceResponse]
	exportTypeSchema          *connect_go.Client[flexitypev1.ExportTypeSchemaRequest, flexitypev1.SchemaResponse]
	importTypeSchema          *connect_go.Client[flexitypev1.ImportTypeSchemaRequest, flexitypev1.TypeResponse]
}

// CreateType calls flexitype.v1.FlexiTypeService.CreateType.
func (c *flexiTypeServiceClient) CreateType(ctx context.Context, req *connect_go.Request[flexitypev1.CreateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.createType.CallUnary(ctx, req)
}

// GetType calls flexitype.v1.FlexiTypeService.GetType.
func (c *flexiTypeServiceClient) GetType(ctx context.Context, req *connect_go.Request[flexitypev1.GetTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.getType.CallUnary(ctx, req)
}

// ListTypes calls flexitype.v1.FlexiTypeService.ListTypes.
func (c *flexiTypeServiceClient) ListTypes(ctx context.Context, req *connect_go.Request[flexitypev1.ListTypesRequest]) (*connect_go.Response[flexitypev1.ListTypesResponse], error) {
	return c.listTypes.CallUnary(ctx, req)
}

// UpdateType calls flexitype.v1.FlexiTypeService.UpdateType.
func (c *flexiTypeServiceClient) UpdateType(ctx context.Context, req *connect_go.Request[flexitypev1.UpdateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.updateType.CallUnary(ctx, req)
}

// ArchiveType calls flexitype.v1.FlexiTypeService.ArchiveType.
func (c *flexiTypeServiceClient) ArchiveType(ctx context.Context, req *connect_go.Request[flexitypev1.ArchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.archiveType.CallUnary(ctx, req)
}

// UnarchiveType calls flexitype.v1.FlexiTypeService.UnarchiveType.
func (c *flexiTypeServiceClient) UnarchiveType(ctx context.Context, req *connect_go.Request[flexitypev1.UnarchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.unarchiveType.CallUnary(ctx, req)
}

// AddAttribute calls flexitype.v1.FlexiTypeService.AddAttribute.
func (c *flexiTypeServiceClient) AddAttribute(ctx context.Context, req *connect_go.Request[flexitypev1.AddAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.addAttribute.CallUnary(ctx, req)
}

// UpdateAttribute calls flexitype.v1.FlexiTypeService.UpdateAttribute.
func (c *flexiTypeServiceClient) UpdateAttribute(ctx context.Context, req *connect_go.Request[flexitypev1.UpdateAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.updateAttribute.CallUnary(ctx, req)
}

// DeleteAttribute calls flexitype.v1.FlexiTypeService.DeleteAttribute.
func (c *flexiTypeServiceClient) DeleteAttribute(ctx context.Context, req *connect_go.Request[flexitypev1.DeleteAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.deleteAttribute.CallUnary(ctx, req)
}

// SetAttributeDisabledState calls flexitype.v1.FlexiTypeService.SetAttributeDisabledState.
func (c *flexiTypeServiceClient) SetAttributeDisabledState(ctx context.Context, req *connect_go.Request[flexitypev1.SetAttributeDisabledStateRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.setAttributeDisabledState.CallUnary(ctx, req)
}

// CreateInstance calls flexitype.v1.FlexiTypeService.CreateInstance.
func (c *flexiTypeServiceClient) CreateInstance(ctx context.Context, req *connect_go.Request[flexitypev1.CreateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return c.createInstance.CallUnary(ctx, req)
}

// GetInstance calls flexitype.v1.FlexiTypeService.GetInstance.
func (c *flexiTypeServiceClient) GetInstance(ctx context.Context, req *connect_go.Request[flexitypev1.GetInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return c.getInstance.CallUnary(ctx, req)
}

// QueryInstances calls flexitype.v1.FlexiTypeService.QueryInstances.
func (c *flexiTypeServiceClient) QueryInstances(ctx context.Context, req *connect_go.Request[flexitypev1.QueryInstancesRequest]) (*connect_go.Response[flexitypev1.QueryInstancesResponse], error) {
	return c.queryInstances.CallUnary(ctx, req)
}

// UpdateInstance calls flexitype.v1.FlexiTypeService.UpdateInstance.
func (c *flexiTypeServiceClient) UpdateInstance(ctx context.Context, req *connect_go.Request[flexitypev1.UpdateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return c.updateInstance.CallUnary(ctx, req)
}

// ArchiveInstance calls flexitype.v1.FlexiTypeService.ArchiveInstance.
func (c *flexiTypeServiceClient) ArchiveInstance(ctx context.Context, req *connect_go.Request[flexitypev1.ArchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return c.archiveInstance.CallUnary(ctx, req)
}

// UnarchiveInstance calls flexitype.v1.FlexiTypeService.UnarchiveInstance.
func (c *flexiTypeServiceClient) UnarchiveInstance(ctx context.Context, req *connect_go.Request[flexitypev1.UnarchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return c.unarchiveInstance.CallUnary(ctx, req)
}

// ExportTypeSchema calls flexitype.v1.FlexiTypeService.ExportTypeSchema.
func (c *flexiTypeServiceClient) ExportTypeSchema(ctx context.Context, req *connect_go.Request[flexitypev1.ExportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.SchemaResponse], error) {
	return c.exportTypeSchema.CallUnary(ctx, req)
}

// ImportTypeSchema calls flexitype.v1.FlexiTypeService.ImportTypeSchema.
func (c *flexiTypeServiceClient) ImportTypeSchema(ctx context.Context, req *connect_go.Request[flexitypev1.ImportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return c.importTypeSchema.CallUnary(ctx, req)
}

// FlexiTypeServiceHandler is an implementation of the flexitype.v1.FlexiTypeService service.
type FlexiTypeServiceHandler interface {
	// Type operations
	CreateType(context.Context, *connect_go.Request[flexitypev1.CreateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	GetType(context.Context, *connect_go.Request[flexitypev1.GetTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	ListTypes(context.Context, *connect_go.Request[flexitypev1.ListTypesRequest]) (*connect_go.Response[flexitypev1.ListTypesResponse], error)
	UpdateType(context.Context, *connect_go.Request[flexitypev1.UpdateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	ArchiveType(context.Context, *connect_go.Request[flexitypev1.ArchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	UnarchiveType(context.Context, *connect_go.Request[flexitypev1.UnarchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	// Attribute operations
	AddAttribute(context.Context, *connect_go.Request[flexitypev1.AddAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	UpdateAttribute(context.Context, *connect_go.Request[flexitypev1.UpdateAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	DeleteAttribute(context.Context, *connect_go.Request[flexitypev1.DeleteAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	SetAttributeDisabledState(context.Context, *connect_go.Request[flexitypev1.SetAttributeDisabledStateRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
	// Instance operations
	CreateInstance(context.Context, *connect_go.Request[flexitypev1.CreateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	GetInstance(context.Context, *connect_go.Request[flexitypev1.GetInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	QueryInstances(context.Context, *connect_go.Request[flexitypev1.QueryInstancesRequest]) (*connect_go.Response[flexitypev1.QueryInstancesResponse], error)
	UpdateInstance(context.Context, *connect_go.Request[flexitypev1.UpdateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	ArchiveInstance(context.Context, *connect_go.Request[flexitypev1.ArchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	UnarchiveInstance(context.Context, *connect_go.Request[flexitypev1.UnarchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error)
	// Schema operations
	ExportTypeSchema(context.Context, *connect_go.Request[flexitypev1.ExportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.SchemaResponse], error)
	ImportTypeSchema(context.Context, *connect_go.Request[flexitypev1.ImportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error)
}

// NewFlexiTypeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFlexiTypeServiceHandler(svc FlexiTypeServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	flexiTypeServiceCreateTypeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceCreateTypeProcedure,
		svc.CreateType,
		opts...,
	)
	flexiTypeServiceGetTypeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceGetTypeProcedure,
		svc.GetType,
		opts...,
	)
	flexiTypeServiceListTypesHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceListTypesProcedure,
		svc.ListTypes,
		opts...,
	)
	flexiTypeServiceUpdateTypeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceUpdateTypeProcedure,
		svc.UpdateType,
		opts...,
	)
	flexiTypeServiceArchiveTypeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceArchiveTypeProcedure,
		svc.ArchiveType,
		opts...,
	)
	flexiTypeServiceUnarchiveTypeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceUnarchiveTypeProcedure,
		svc.UnarchiveType,
		opts...,
	)
	flexiTypeServiceAddAttributeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceAddAttributeProcedure,
		svc.AddAttribute,
		opts...,
	)
	flexiTypeServiceUpdateAttributeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceUpdateAttributeProcedure,
		svc.UpdateAttribute,
		opts...,
	)
	flexiTypeServiceDeleteAttributeHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceDeleteAttributeProcedure,
		svc.DeleteAttribute,
		opts...,
	)
	flexiTypeServiceSetAttributeDisabledStateHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceSetAttributeDisabledStateProcedure,
		svc.SetAttributeDisabledState,
		opts...,
	)
	flexiTypeServiceCreateInstanceHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceCreateInstanceProcedure,
		svc.CreateInstance,
		opts...,
	)
	flexiTypeServiceGetInstanceHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceGetInstanceProcedure,
		svc.GetInstance,
		opts...,
	)
	flexiTypeServiceQueryInstancesHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceQueryInstancesProcedure,
		svc.QueryInstances,
		opts...,
	)
	flexiTypeServiceUpdateInstanceHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceUpdateInstanceProcedure,
		svc.UpdateInstance,
		opts...,
	)
	flexiTypeServiceArchiveInstanceHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceArchiveInstanceProcedure,
		svc.ArchiveInstance,
		opts...,
	)
	flexiTypeServiceUnarchiveInstanceHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceUnarchiveInstanceProcedure,
		svc.UnarchiveInstance,
		opts...,
	)
	flexiTypeServiceExportTypeSchemaHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceExportTypeSchemaProcedure,
		svc.ExportTypeSchema,
		opts...,
	)
	flexiTypeServiceImportTypeSchemaHandler := connect_go.NewUnaryHandler(
		FlexiTypeServiceImportTypeSchemaProcedure,
		svc.ImportTypeSchema,
		opts...,
	)
	return "/flexitype.v1.FlexiTypeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FlexiTypeServiceCreateTypeProcedure:
			flexiTypeServiceCreateTypeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceGetTypeProcedure:
			flexiTypeServiceGetTypeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceListTypesProcedure:
			flexiTypeServiceListTypesHandler.ServeHTTP(w, r)
		case FlexiTypeServiceUpdateTypeProcedure:
			flexiTypeServiceUpdateTypeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceArchiveTypeProcedure:
			flexiTypeServiceArchiveTypeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceUnarchiveTypeProcedure:
			flexiTypeServiceUnarchiveTypeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceAddAttributeProcedure:
			flexiTypeServiceAddAttributeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceUpdateAttributeProcedure:
			flexiTypeServiceUpdateAttributeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceDeleteAttributeProcedure:
			flexiTypeServiceDeleteAttributeHandler.ServeHTTP(w, r)
		case FlexiTypeServiceSetAttributeDisabledStateProcedure:
			flexiTypeServiceSetAttributeDisabledStateHandler.ServeHTTP(w, r)
		case FlexiTypeServiceCreateInstanceProcedure:
			flexiTypeServiceCreateInstanceHandler.ServeHTTP(w, r)
		case FlexiTypeServiceGetInstanceProcedure:
			flexiTypeServiceGetInstanceHandler.ServeHTTP(w, r)
		case FlexiTypeServiceQueryInstancesProcedure:
			flexiTypeServiceQueryInstancesHandler.ServeHTTP(w, r)
		case FlexiTypeServiceUpdateInstanceProcedure:
			flexiTypeServiceUpdateInstanceHandler.ServeHTTP(w, r)
		case FlexiTypeServiceArchiveInstanceProcedure:
			flexiTypeServiceArchiveInstanceHandler.ServeHTTP(w, r)
		case FlexiTypeServiceUnarchiveInstanceProcedure:
			flexiTypeServiceUnarchiveInstanceHandler.ServeHTTP(w, r)
		case FlexiTypeServiceExportTypeSchemaProcedure:
			flexiTypeServiceExportTypeSchemaHandler.ServeHTTP(w, r)
		case FlexiTypeServiceImportTypeSchemaProcedure:
			flexiTypeServiceImportTypeSchemaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFlexiTypeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFlexiTypeServiceHandler struct{}

func (UnimplementedFlexiTypeServiceHandler) CreateType(context.Context, *connect_go.Request[flexitypev1.CreateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.CreateType is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) GetType(context.Context, *connect_go.Request[flexitypev1.GetTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.GetType is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) ListTypes(context.Context, *connect_go.Request[flexitypev1.ListTypesRequest]) (*connect_go.Response[flexitypev1.ListTypesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.ListTypes is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) UpdateType(context.Context, *connect_go.Request[flexitypev1.UpdateTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.UpdateType is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) ArchiveType(context.Context, *connect_go.Request[flexitypev1.ArchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.ArchiveType is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) UnarchiveType(context.Context, *connect_go.Request[flexitypev1.UnarchiveTypeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.UnarchiveType is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) AddAttribute(context.Context, *connect_go.Request[flexitypev1.AddAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.AddAttribute is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) UpdateAttribute(context.Context, *connect_go.Request[flexitypev1.UpdateAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.UpdateAttribute is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) DeleteAttribute(context.Context, *connect_go.Request[flexitypev1.DeleteAttributeRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.DeleteAttribute is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) SetAttributeDisabledState(context.Context, *connect_go.Request[flexitypev1.SetAttributeDisabledStateRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.SetAttributeDisabledState is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) CreateInstance(context.Context, *connect_go.Request[flexitypev1.CreateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.CreateInstance is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) GetInstance(context.Context, *connect_go.Request[flexitypev1.GetInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.GetInstance is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) QueryInstances(context.Context, *connect_go.Request[flexitypev1.QueryInstancesRequest]) (*connect_go.Response[flexitypev1.QueryInstancesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.QueryInstances is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) UpdateInstance(context.Context, *connect_go.Request[flexitypev1.UpdateInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.UpdateInstance is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) ArchiveInstance(context.Context, *connect_go.Request[flexitypev1.ArchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.ArchiveInstance is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) UnarchiveInstance(context.Context, *connect_go.Request[flexitypev1.UnarchiveInstanceRequest]) (*connect_go.Response[flexitypev1.InstanceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.UnarchiveInstance is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) ExportTypeSchema(context.Context, *connect_go.Request[flexitypev1.ExportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.SchemaResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.ExportTypeSchema is not implemented"))
}

func (UnimplementedFlexiTypeServiceHandler) ImportTypeSchema(context.Context, *connect_go.Request[flexitypev1.ImportTypeSchemaRequest]) (*connect_go.Response[flexitypev1.TypeResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.v1.FlexiTypeService.ImportTypeSchema is not implemented"))
}
