// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/connect/attribute_value.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/zkrebbekx/flexitype/internal/api/connect/pb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AttributeValueServiceName is the fully-qualified name of the AttributeValueService service.
	AttributeValueServiceName = "flexitype.AttributeValueService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AttributeValueServiceCreateAttributeValueProcedure is the fully-qualified name of the
	// AttributeValueService's CreateAttributeValue RPC.
	AttributeValueServiceCreateAttributeValueProcedure = "/flexitype.AttributeValueService/CreateAttributeValue"
	// AttributeValueServiceUpdateAttributeValueProcedure is the fully-qualified name of the
	// AttributeValueService's UpdateAttributeValue RPC.
	AttributeValueServiceUpdateAttributeValueProcedure = "/flexitype.AttributeValueService/UpdateAttributeValue"
	// AttributeValueServiceGetAttributeValueProcedure is the fully-qualified name of the
	// AttributeValueService's GetAttributeValue RPC.
	AttributeValueServiceGetAttributeValueProcedure = "/flexitype.AttributeValueService/GetAttributeValue"
	// AttributeValueServiceArchiveAttributeValueProcedure is the fully-qualified name of the
	// AttributeValueService's ArchiveAttributeValue RPC.
	AttributeValueServiceArchiveAttributeValueProcedure = "/flexitype.AttributeValueService/ArchiveAttributeValue"
	// AttributeValueServiceListAttributeValuesProcedure is the fully-qualified name of the
	// AttributeValueService's ListAttributeValues RPC.
	AttributeValueServiceListAttributeValuesProcedure = "/flexitype.AttributeValueService/ListAttributeValues"
	// AttributeValueServiceGetAttributeValuesByAttributeIDProcedure is the fully-qualified name of the
	// AttributeValueService's GetAttributeValuesByAttributeID RPC.
	AttributeValueServiceGetAttributeValuesByAttributeIDProcedure = "/flexitype.AttributeValueService/GetAttributeValuesByAttributeID"
)

// AttributeValueServiceClient is a client for the flexitype.AttributeValueService service.
type AttributeValueServiceClient interface {
	// CreateAttributeValue creates a new attribute value
	CreateAttributeValue(context.Context, *connect_go.Request[pb.CreateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	// UpdateAttributeValue updates an existing attribute value
	UpdateAttributeValue(context.Context, *connect_go.Request[pb.UpdateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	// GetAttributeValue retrieves an attribute value by ID
	GetAttributeValue(context.Context, *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	// ArchiveAttributeValue archives an attribute value
	ArchiveAttributeValue(context.Context, *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListAttributeValues lists attribute values based on filter criteria
	ListAttributeValues(context.Context, *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error)
	// GetAttributeValuesByAttributeID retrieves values for a specific attribute
	GetAttributeValuesByAttributeID(context.Context, *connect_go.Request[pb.GetAttributeValuesByAttributeIDRequest]) (*connect_go.Response[pb.AttributeValueList], error)
}

// NewAttributeValueServiceClient constructs a client for the flexitype.AttributeValueService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAttributeValueServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AttributeValueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &attributeValueServiceClient{
		createAttributeValue: connect_go.NewClient[pb.CreateAttributeValueRequest, pb.AttributeValue](
			httpClient,
			baseURL+AttributeValueServiceCreateAttributeValueProcedure,
			opts...,
		),
		updateAttributeValue: connect_go.NewClient[pb.UpdateAttributeValueRequest, pb.AttributeValue](
			httpClient,
			baseURL+AttributeValueServiceUpdateAttributeValueProcedure,
			opts...,
		),
		getAttributeValue: connect_go.NewClient[pb.GetAttributeValueRequest, pb.AttributeValue](
			httpClient,
			baseURL+AttributeValueServiceGetAttributeValueProcedure,
			opts...,
		),
		archiveAttributeValue: connect_go.NewClient[pb.ArchiveAttributeValueRequest, emptypb.Empty](
			httpClient,
			baseURL+AttributeValueServiceArchiveAttributeValueProcedure,
			opts...,
		),
		listAttributeValues: connect_go.NewClient[pb.ListAttributeValuesRequest, pb.ListAttributeValuesResponse](
			httpClient,
			baseURL+AttributeValueServiceListAttributeValuesProcedure,
			opts...,
		),
		getAttributeValuesByAttributeID: connect_go.NewClient[pb.GetAttributeValuesByAttributeIDRequest, pb.AttributeValueList](
			httpClient,
			baseURL+AttributeValueServiceGetAttributeValuesByAttributeIDProcedure,
			opts...,
		),
	}
}

// attributeValueServiceClient implements AttributeValueServiceClient.
type attributeValueServiceClient struct {
	createAttributeValue            *connect_go.Client[pb.CreateAttributeValueRequest, pb.AttributeValue]
	updateAttributeValue            *connect_go.Client[pb.UpdateAttributeValueRequest, pb.AttributeValue]
	getAttributeValue               *connect_go.Client[pb.GetAttributeValueRequest, pb.AttributeValue]
	archiveAttributeValue           *connect_go.Client[pb.ArchiveAttributeValueRequest, emptypb.Empty]
	listAttributeValues             *connect_go.Client[pb.ListAttributeValuesRequest, pb.ListAttributeValuesResponse]
	getAttributeValuesByAttributeID *connect_go.Client[pb.GetAttributeValuesByAttributeIDRequest, pb.AttributeValueList]
}

// CreateAttributeValue calls flexitype.AttributeValueService.CreateAttributeValue.
func (c *attributeValueServiceClient) CreateAttributeValue(ctx context.Context, req *connect_go.Request[pb.CreateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.createAttributeValue.CallUnary(ctx, req)
}

// UpdateAttributeValue calls flexitype.AttributeValueService.UpdateAttributeValue.
func (c *attributeValueServiceClient) UpdateAttributeValue(ctx context.Context, req *connect_go.Request[pb.UpdateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.updateAttributeValue.CallUnary(ctx, req)
}

// GetAttributeValue calls flexitype.AttributeValueService.GetAttributeValue.
func (c *attributeValueServiceClient) GetAttributeValue(ctx context.Context, req *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.getAttributeValue.CallUnary(ctx, req)
}

// ArchiveAttributeValue calls flexitype.AttributeValueService.ArchiveAttributeValue.
func (c *attributeValueServiceClient) ArchiveAttributeValue(ctx context.Context, req *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.archiveAttributeValue.CallUnary(ctx, req)
}

// ListAttributeValues calls flexitype.AttributeValueService.ListAttributeValues.
func (c *attributeValueServiceClient) ListAttributeValues(ctx context.Context, req *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error) {
	return c.listAttributeValues.CallUnary(ctx, req)
}

// GetAttributeValuesByAttributeID calls
// flexitype.AttributeValueService.GetAttributeValuesByAttributeID.
func (c *attributeValueServiceClient) GetAttributeValuesByAttributeID(ctx context.Context, req *connect_go.Request[pb.GetAttributeValuesByAttributeIDRequest]) (*connect_go.Response[pb.AttributeValueList], error) {
	return c.getAttributeValuesByAttributeID.CallUnary(ctx, req)
}

// AttributeValueServiceHandler is an implementation of the flexitype.AttributeValueService service.
type AttributeValueServiceHandler interface {
	// CreateAttributeValue creates a new attribute value
	CreateAttributeValue(context.Context, *connect_go.Request[pb.CreateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	// UpdateAttributeValue updates an existing attribute value
	UpdateAttributeValue(context.Context, *connect_go.Request[pb.UpdateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	// GetAttributeValue retrieves an attribute value by ID
	GetAttributeValue(context.Context, *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	// ArchiveAttributeValue archives an attribute value
	ArchiveAttributeValue(context.Context, *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListAttributeValues lists attribute values based on filter criteria
	ListAttributeValues(context.Context, *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error)
	// GetAttributeValuesByAttributeID retrieves values for a specific attribute
	GetAttributeValuesByAttributeID(context.Context, *connect_go.Request[pb.GetAttributeValuesByAttributeIDRequest]) (*connect_go.Response[pb.AttributeValueList], error)
}

// NewAttributeValueServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAttributeValueServiceHandler(svc AttributeValueServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	attributeValueServiceCreateAttributeValueHandler := connect_go.NewUnaryHandler(
		AttributeValueServiceCreateAttributeValueProcedure,
		svc.CreateAttributeValue,
		opts...,
	)
	attributeValueServiceUpdateAttributeValueHandler := connect_go.NewUnaryHandler(
		AttributeValueServiceUpdateAttributeValueProcedure,
		svc.UpdateAttributeValue,
		opts...,
	)
	attributeValueServiceGetAttributeValueHandler := connect_go.NewUnaryHandler(
		AttributeValueServiceGetAttributeValueProcedure,
		svc.GetAttributeValue,
		opts...,
	)
	attributeValueServiceArchiveAttributeValueHandler := connect_go.NewUnaryHandler(
		AttributeValueServiceArchiveAttributeValueProcedure,
		svc.ArchiveAttributeValue,
		opts...,
	)
	attributeValueServiceListAttributeValuesHandler := connect_go.NewUnaryHandler(
		AttributeValueServiceListAttributeValuesProcedure,
		svc.ListAttributeValues,
		opts...,
	)
	attributeValueServiceGetAttributeValuesByAttributeIDHandler := connect_go.NewUnaryHandler(
		AttributeValueServiceGetAttributeValuesByAttributeIDProcedure,
		svc.GetAttributeValuesByAttributeID,
		opts...,
	)
	return "/flexitype.AttributeValueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AttributeValueServiceCreateAttributeValueProcedure:
			attributeValueServiceCreateAttributeValueHandler.ServeHTTP(w, r)
		case AttributeValueServiceUpdateAttributeValueProcedure:
			attributeValueServiceUpdateAttributeValueHandler.ServeHTTP(w, r)
		case AttributeValueServiceGetAttributeValueProcedure:
			attributeValueServiceGetAttributeValueHandler.ServeHTTP(w, r)
		case AttributeValueServiceArchiveAttributeValueProcedure:
			attributeValueServiceArchiveAttributeValueHandler.ServeHTTP(w, r)
		case AttributeValueServiceListAttributeValuesProcedure:
			attributeValueServiceListAttributeValuesHandler.ServeHTTP(w, r)
		case AttributeValueServiceGetAttributeValuesByAttributeIDProcedure:
			attributeValueServiceGetAttributeValuesByAttributeIDHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAttributeValueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAttributeValueServiceHandler struct{}

func (UnimplementedAttributeValueServiceHandler) CreateAttributeValue(context.Context, *connect_go.Request[pb.CreateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueService.CreateAttributeValue is not implemented"))
}

func (UnimplementedAttributeValueServiceHandler) UpdateAttributeValue(context.Context, *connect_go.Request[pb.UpdateAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueService.UpdateAttributeValue is not implemented"))
}

func (UnimplementedAttributeValueServiceHandler) GetAttributeValue(context.Context, *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueService.GetAttributeValue is not implemented"))
}

func (UnimplementedAttributeValueServiceHandler) ArchiveAttributeValue(context.Context, *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueService.ArchiveAttributeValue is not implemented"))
}

func (UnimplementedAttributeValueServiceHandler) ListAttributeValues(context.Context, *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueService.ListAttributeValues is not implemented"))
}

func (UnimplementedAttributeValueServiceHandler) GetAttributeValuesByAttributeID(context.Context, *connect_go.Request[pb.GetAttributeValuesByAttributeIDRequest]) (*connect_go.Response[pb.AttributeValueList], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueService.GetAttributeValuesByAttributeID is not implemented"))
}
