// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: attribute_value_dependency.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/zkrebbekx/flexitype/internal/api/connect/pb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AttributeValueDependencyServiceName is the fully-qualified name of the
	// AttributeValueDependencyService service.
	AttributeValueDependencyServiceName = "flexitype.AttributeValueDependencyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AttributeValueDependencyServiceCreateAttributeValueDependencyProcedure is the fully-qualified
	// name of the AttributeValueDependencyService's CreateAttributeValueDependency RPC.
	AttributeValueDependencyServiceCreateAttributeValueDependencyProcedure = "/flexitype.AttributeValueDependencyService/CreateAttributeValueDependency"
	// AttributeValueDependencyServiceUpdateAttributeValueDependencyProcedure is the fully-qualified
	// name of the AttributeValueDependencyService's UpdateAttributeValueDependency RPC.
	AttributeValueDependencyServiceUpdateAttributeValueDependencyProcedure = "/flexitype.AttributeValueDependencyService/UpdateAttributeValueDependency"
	// AttributeValueDependencyServiceGetAttributeValueDependencyProcedure is the fully-qualified name
	// of the AttributeValueDependencyService's GetAttributeValueDependency RPC.
	AttributeValueDependencyServiceGetAttributeValueDependencyProcedure = "/flexitype.AttributeValueDependencyService/GetAttributeValueDependency"
	// AttributeValueDependencyServiceArchiveAttributeValueDependencyProcedure is the fully-qualified
	// name of the AttributeValueDependencyService's ArchiveAttributeValueDependency RPC.
	AttributeValueDependencyServiceArchiveAttributeValueDependencyProcedure = "/flexitype.AttributeValueDependencyService/ArchiveAttributeValueDependency"
	// AttributeValueDependencyServiceListAttributeValueDependenciesProcedure is the fully-qualified
	// name of the AttributeValueDependencyService's ListAttributeValueDependencies RPC.
	AttributeValueDependencyServiceListAttributeValueDependenciesProcedure = "/flexitype.AttributeValueDependencyService/ListAttributeValueDependencies"
	// AttributeValueDependencyServiceGetDependentValuesProcedure is the fully-qualified name of the
	// AttributeValueDependencyService's GetDependentValues RPC.
	AttributeValueDependencyServiceGetDependentValuesProcedure = "/flexitype.AttributeValueDependencyService/GetDependentValues"
)

// AttributeValueDependencyServiceClient is a client for the
// flexitype.AttributeValueDependencyService service.
type AttributeValueDependencyServiceClient interface {
	// CreateAttributeValueDependency creates a new dependency
	CreateAttributeValueDependency(context.Context, *connect_go.Request[pb.CreateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	// UpdateAttributeValueDependency updates an existing dependency
	UpdateAttributeValueDependency(context.Context, *connect_go.Request[pb.UpdateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	// GetAttributeValueDependency retrieves a dependency by ID
	GetAttributeValueDependency(context.Context, *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	// ArchiveAttributeValueDependency archives a dependency
	ArchiveAttributeValueDependency(context.Context, *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListAttributeValueDependencies lists dependencies based on filter criteria
	ListAttributeValueDependencies(context.Context, *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error)
	// GetDependentValues retrieves dependent values for a source value
	GetDependentValues(context.Context, *connect_go.Request[pb.GetDependentValuesRequest]) (*connect_go.Response[pb.AttributeValueDependencyList], error)
}

// NewAttributeValueDependencyServiceClient constructs a client for the
// flexitype.AttributeValueDependencyService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAttributeValueDependencyServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AttributeValueDependencyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &attributeValueDependencyServiceClient{
		createAttributeValueDependency: connect_go.NewClient[pb.CreateAttributeValueDependencyRequest, pb.AttributeValueDependency](
			httpClient,
			baseURL+AttributeValueDependencyServiceCreateAttributeValueDependencyProcedure,
			opts...,
		),
		updateAttributeValueDependency: connect_go.NewClient[pb.UpdateAttributeValueDependencyRequest, pb.AttributeValueDependency](
			httpClient,
			baseURL+AttributeValueDependencyServiceUpdateAttributeValueDependencyProcedure,
			opts...,
		),
		getAttributeValueDependency: connect_go.NewClient[pb.GetAttributeValueDependencyRequest, pb.AttributeValueDependency](
			httpClient,
			baseURL+AttributeValueDependencyServiceGetAttributeValueDependencyProcedure,
			opts...,
		),
		archiveAttributeValueDependency: connect_go.NewClient[pb.ArchiveAttributeValueDependencyRequest, emptypb.Empty](
			httpClient,
			baseURL+AttributeValueDependencyServiceArchiveAttributeValueDependencyProcedure,
			opts...,
		),
		listAttributeValueDependencies: connect_go.NewClient[pb.ListAttributeValueDependenciesRequest, pb.ListAttributeValueDependenciesResponse](
			httpClient,
			baseURL+AttributeValueDependencyServiceListAttributeValueDependenciesProcedure,
			opts...,
		),
		getDependentValues: connect_go.NewClient[pb.GetDependentValuesRequest, pb.AttributeValueDependencyList](
			httpClient,
			baseURL+AttributeValueDependencyServiceGetDependentValuesProcedure,
			opts...,
		),
	}
}

// attributeValueDependencyServiceClient implements AttributeValueDependencyServiceClient.
type attributeValueDependencyServiceClient struct {
	createAttributeValueDependency  *connect_go.Client[pb.CreateAttributeValueDependencyRequest, pb.AttributeValueDependency]
	updateAttributeValueDependency  *connect_go.Client[pb.UpdateAttributeValueDependencyRequest, pb.AttributeValueDependency]
	getAttributeValueDependency     *connect_go.Client[pb.GetAttributeValueDependencyRequest, pb.AttributeValueDependency]
	archiveAttributeValueDependency *connect_go.Client[pb.ArchiveAttributeValueDependencyRequest, emptypb.Empty]
	listAttributeValueDependencies  *connect_go.Client[pb.ListAttributeValueDependenciesRequest, pb.ListAttributeValueDependenciesResponse]
	getDependentValues              *connect_go.Client[pb.GetDependentValuesRequest, pb.AttributeValueDependencyList]
}

// CreateAttributeValueDependency calls
// flexitype.AttributeValueDependencyService.CreateAttributeValueDependency.
func (c *attributeValueDependencyServiceClient) CreateAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.CreateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.createAttributeValueDependency.CallUnary(ctx, req)
}

// UpdateAttributeValueDependency calls
// flexitype.AttributeValueDependencyService.UpdateAttributeValueDependency.
func (c *attributeValueDependencyServiceClient) UpdateAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.UpdateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.updateAttributeValueDependency.CallUnary(ctx, req)
}

// GetAttributeValueDependency calls
// flexitype.AttributeValueDependencyService.GetAttributeValueDependency.
func (c *attributeValueDependencyServiceClient) GetAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.getAttributeValueDependency.CallUnary(ctx, req)
}

// ArchiveAttributeValueDependency calls
// flexitype.AttributeValueDependencyService.ArchiveAttributeValueDependency.
func (c *attributeValueDependencyServiceClient) ArchiveAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.archiveAttributeValueDependency.CallUnary(ctx, req)
}

// ListAttributeValueDependencies calls
// flexitype.AttributeValueDependencyService.ListAttributeValueDependencies.
func (c *attributeValueDependencyServiceClient) ListAttributeValueDependencies(ctx context.Context, req *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error) {
	return c.listAttributeValueDependencies.CallUnary(ctx, req)
}

// GetDependentValues calls flexitype.AttributeValueDependencyService.GetDependentValues.
func (c *attributeValueDependencyServiceClient) GetDependentValues(ctx context.Context, req *connect_go.Request[pb.GetDependentValuesRequest]) (*connect_go.Response[pb.AttributeValueDependencyList], error) {
	return c.getDependentValues.CallUnary(ctx, req)
}

// AttributeValueDependencyServiceHandler is an implementation of the
// flexitype.AttributeValueDependencyService service.
type AttributeValueDependencyServiceHandler interface {
	// CreateAttributeValueDependency creates a new dependency
	CreateAttributeValueDependency(context.Context, *connect_go.Request[pb.CreateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	// UpdateAttributeValueDependency updates an existing dependency
	UpdateAttributeValueDependency(context.Context, *connect_go.Request[pb.UpdateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	// GetAttributeValueDependency retrieves a dependency by ID
	GetAttributeValueDependency(context.Context, *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	// ArchiveAttributeValueDependency archives a dependency
	ArchiveAttributeValueDependency(context.Context, *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListAttributeValueDependencies lists dependencies based on filter criteria
	ListAttributeValueDependencies(context.Context, *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error)
	// GetDependentValues retrieves dependent values for a source value
	GetDependentValues(context.Context, *connect_go.Request[pb.GetDependentValuesRequest]) (*connect_go.Response[pb.AttributeValueDependencyList], error)
}

// NewAttributeValueDependencyServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAttributeValueDependencyServiceHandler(svc AttributeValueDependencyServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	attributeValueDependencyServiceCreateAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		AttributeValueDependencyServiceCreateAttributeValueDependencyProcedure,
		svc.CreateAttributeValueDependency,
		opts...,
	)
	attributeValueDependencyServiceUpdateAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		AttributeValueDependencyServiceUpdateAttributeValueDependencyProcedure,
		svc.UpdateAttributeValueDependency,
		opts...,
	)
	attributeValueDependencyServiceGetAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		AttributeValueDependencyServiceGetAttributeValueDependencyProcedure,
		svc.GetAttributeValueDependency,
		opts...,
	)
	attributeValueDependencyServiceArchiveAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		AttributeValueDependencyServiceArchiveAttributeValueDependencyProcedure,
		svc.ArchiveAttributeValueDependency,
		opts...,
	)
	attributeValueDependencyServiceListAttributeValueDependenciesHandler := connect_go.NewUnaryHandler(
		AttributeValueDependencyServiceListAttributeValueDependenciesProcedure,
		svc.ListAttributeValueDependencies,
		opts...,
	)
	attributeValueDependencyServiceGetDependentValuesHandler := connect_go.NewUnaryHandler(
		AttributeValueDependencyServiceGetDependentValuesProcedure,
		svc.GetDependentValues,
		opts...,
	)
	return "/flexitype.AttributeValueDependencyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AttributeValueDependencyServiceCreateAttributeValueDependencyProcedure:
			attributeValueDependencyServiceCreateAttributeValueDependencyHandler.ServeHTTP(w, r)
		case AttributeValueDependencyServiceUpdateAttributeValueDependencyProcedure:
			attributeValueDependencyServiceUpdateAttributeValueDependencyHandler.ServeHTTP(w, r)
		case AttributeValueDependencyServiceGetAttributeValueDependencyProcedure:
			attributeValueDependencyServiceGetAttributeValueDependencyHandler.ServeHTTP(w, r)
		case AttributeValueDependencyServiceArchiveAttributeValueDependencyProcedure:
			attributeValueDependencyServiceArchiveAttributeValueDependencyHandler.ServeHTTP(w, r)
		case AttributeValueDependencyServiceListAttributeValueDependenciesProcedure:
			attributeValueDependencyServiceListAttributeValueDependenciesHandler.ServeHTTP(w, r)
		case AttributeValueDependencyServiceGetDependentValuesProcedure:
			attributeValueDependencyServiceGetDependentValuesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAttributeValueDependencyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAttributeValueDependencyServiceHandler struct{}

func (UnimplementedAttributeValueDependencyServiceHandler) CreateAttributeValueDependency(context.Context, *connect_go.Request[pb.CreateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueDependencyService.CreateAttributeValueDependency is not implemented"))
}

func (UnimplementedAttributeValueDependencyServiceHandler) UpdateAttributeValueDependency(context.Context, *connect_go.Request[pb.UpdateAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueDependencyService.UpdateAttributeValueDependency is not implemented"))
}

func (UnimplementedAttributeValueDependencyServiceHandler) GetAttributeValueDependency(context.Context, *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueDependencyService.GetAttributeValueDependency is not implemented"))
}

func (UnimplementedAttributeValueDependencyServiceHandler) ArchiveAttributeValueDependency(context.Context, *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueDependencyService.ArchiveAttributeValueDependency is not implemented"))
}

func (UnimplementedAttributeValueDependencyServiceHandler) ListAttributeValueDependencies(context.Context, *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueDependencyService.ListAttributeValueDependencies is not implemented"))
}

func (UnimplementedAttributeValueDependencyServiceHandler) GetDependentValues(context.Context, *connect_go.Request[pb.GetDependentValuesRequest]) (*connect_go.Response[pb.AttributeValueDependencyList], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeValueDependencyService.GetDependentValues is not implemented"))
}
