// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: attribute.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/zkrebbekx/flexitype/internal/api/connect/pb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AttributeServiceName is the fully-qualified name of the AttributeService service.
	AttributeServiceName = "flexitype.AttributeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AttributeServiceCreateAttributeProcedure is the fully-qualified name of the AttributeService's
	// CreateAttribute RPC.
	AttributeServiceCreateAttributeProcedure = "/flexitype.AttributeService/CreateAttribute"
	// AttributeServiceUpdateAttributeProcedure is the fully-qualified name of the AttributeService's
	// UpdateAttribute RPC.
	AttributeServiceUpdateAttributeProcedure = "/flexitype.AttributeService/UpdateAttribute"
	// AttributeServiceGetAttributeProcedure is the fully-qualified name of the AttributeService's
	// GetAttribute RPC.
	AttributeServiceGetAttributeProcedure = "/flexitype.AttributeService/GetAttribute"
	// AttributeServiceArchiveAttributeProcedure is the fully-qualified name of the AttributeService's
	// ArchiveAttribute RPC.
	AttributeServiceArchiveAttributeProcedure = "/flexitype.AttributeService/ArchiveAttribute"
	// AttributeServiceListAttributesProcedure is the fully-qualified name of the AttributeService's
	// ListAttributes RPC.
	AttributeServiceListAttributesProcedure = "/flexitype.AttributeService/ListAttributes"
	// AttributeServiceGetAttributesByTypeDefinitionIDProcedure is the fully-qualified name of the
	// AttributeService's GetAttributesByTypeDefinitionID RPC.
	AttributeServiceGetAttributesByTypeDefinitionIDProcedure = "/flexitype.AttributeService/GetAttributesByTypeDefinitionID"
)

// AttributeServiceClient is a client for the flexitype.AttributeService service.
type AttributeServiceClient interface {
	// CreateAttribute creates a new attribute
	CreateAttribute(context.Context, *connect_go.Request[pb.CreateAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	// UpdateAttribute updates an existing attribute
	UpdateAttribute(context.Context, *connect_go.Request[pb.UpdateAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	// GetAttribute retrieves an attribute by ID
	GetAttribute(context.Context, *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	// ArchiveAttribute archives an attribute
	ArchiveAttribute(context.Context, *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListAttributes lists attributes based on filter criteria
	ListAttributes(context.Context, *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error)
	// GetAttributesByTypeDefinitionID retrieves attributes for a specific type definition
	GetAttributesByTypeDefinitionID(context.Context, *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.AttributeList], error)
}

// NewAttributeServiceClient constructs a client for the flexitype.AttributeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAttributeServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AttributeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &attributeServiceClient{
		createAttribute: connect_go.NewClient[pb.CreateAttributeRequest, pb.Attribute](
			httpClient,
			baseURL+AttributeServiceCreateAttributeProcedure,
			opts...,
		),
		updateAttribute: connect_go.NewClient[pb.UpdateAttributeRequest, pb.Attribute](
			httpClient,
			baseURL+AttributeServiceUpdateAttributeProcedure,
			opts...,
		),
		getAttribute: connect_go.NewClient[pb.GetAttributeRequest, pb.Attribute](
			httpClient,
			baseURL+AttributeServiceGetAttributeProcedure,
			opts...,
		),
		archiveAttribute: connect_go.NewClient[pb.ArchiveAttributeRequest, emptypb.Empty](
			httpClient,
			baseURL+AttributeServiceArchiveAttributeProcedure,
			opts...,
		),
		listAttributes: connect_go.NewClient[pb.ListAttributesRequest, pb.ListAttributesResponse](
			httpClient,
			baseURL+AttributeServiceListAttributesProcedure,
			opts...,
		),
		getAttributesByTypeDefinitionID: connect_go.NewClient[pb.GetAttributesByTypeDefinitionIDRequest, pb.AttributeList](
			httpClient,
			baseURL+AttributeServiceGetAttributesByTypeDefinitionIDProcedure,
			opts...,
		),
	}
}

// attributeServiceClient implements AttributeServiceClient.
type attributeServiceClient struct {
	createAttribute                 *connect_go.Client[pb.CreateAttributeRequest, pb.Attribute]
	updateAttribute                 *connect_go.Client[pb.UpdateAttributeRequest, pb.Attribute]
	getAttribute                    *connect_go.Client[pb.GetAttributeRequest, pb.Attribute]
	archiveAttribute                *connect_go.Client[pb.ArchiveAttributeRequest, emptypb.Empty]
	listAttributes                  *connect_go.Client[pb.ListAttributesRequest, pb.ListAttributesResponse]
	getAttributesByTypeDefinitionID *connect_go.Client[pb.GetAttributesByTypeDefinitionIDRequest, pb.AttributeList]
}

// CreateAttribute calls flexitype.AttributeService.CreateAttribute.
func (c *attributeServiceClient) CreateAttribute(ctx context.Context, req *connect_go.Request[pb.CreateAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return c.createAttribute.CallUnary(ctx, req)
}

// UpdateAttribute calls flexitype.AttributeService.UpdateAttribute.
func (c *attributeServiceClient) UpdateAttribute(ctx context.Context, req *connect_go.Request[pb.UpdateAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return c.updateAttribute.CallUnary(ctx, req)
}

// GetAttribute calls flexitype.AttributeService.GetAttribute.
func (c *attributeServiceClient) GetAttribute(ctx context.Context, req *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return c.getAttribute.CallUnary(ctx, req)
}

// ArchiveAttribute calls flexitype.AttributeService.ArchiveAttribute.
func (c *attributeServiceClient) ArchiveAttribute(ctx context.Context, req *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.archiveAttribute.CallUnary(ctx, req)
}

// ListAttributes calls flexitype.AttributeService.ListAttributes.
func (c *attributeServiceClient) ListAttributes(ctx context.Context, req *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error) {
	return c.listAttributes.CallUnary(ctx, req)
}

// GetAttributesByTypeDefinitionID calls flexitype.AttributeService.GetAttributesByTypeDefinitionID.
func (c *attributeServiceClient) GetAttributesByTypeDefinitionID(ctx context.Context, req *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.AttributeList], error) {
	return c.getAttributesByTypeDefinitionID.CallUnary(ctx, req)
}

// AttributeServiceHandler is an implementation of the flexitype.AttributeService service.
type AttributeServiceHandler interface {
	// CreateAttribute creates a new attribute
	CreateAttribute(context.Context, *connect_go.Request[pb.CreateAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	// UpdateAttribute updates an existing attribute
	UpdateAttribute(context.Context, *connect_go.Request[pb.UpdateAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	// GetAttribute retrieves an attribute by ID
	GetAttribute(context.Context, *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	// ArchiveAttribute archives an attribute
	ArchiveAttribute(context.Context, *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListAttributes lists attributes based on filter criteria
	ListAttributes(context.Context, *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error)
	// GetAttributesByTypeDefinitionID retrieves attributes for a specific type definition
	GetAttributesByTypeDefinitionID(context.Context, *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.AttributeList], error)
}

// NewAttributeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAttributeServiceHandler(svc AttributeServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	attributeServiceCreateAttributeHandler := connect_go.NewUnaryHandler(
		AttributeServiceCreateAttributeProcedure,
		svc.CreateAttribute,
		opts...,
	)
	attributeServiceUpdateAttributeHandler := connect_go.NewUnaryHandler(
		AttributeServiceUpdateAttributeProcedure,
		svc.UpdateAttribute,
		opts...,
	)
	attributeServiceGetAttributeHandler := connect_go.NewUnaryHandler(
		AttributeServiceGetAttributeProcedure,
		svc.GetAttribute,
		opts...,
	)
	attributeServiceArchiveAttributeHandler := connect_go.NewUnaryHandler(
		AttributeServiceArchiveAttributeProcedure,
		svc.ArchiveAttribute,
		opts...,
	)
	attributeServiceListAttributesHandler := connect_go.NewUnaryHandler(
		AttributeServiceListAttributesProcedure,
		svc.ListAttributes,
		opts...,
	)
	attributeServiceGetAttributesByTypeDefinitionIDHandler := connect_go.NewUnaryHandler(
		AttributeServiceGetAttributesByTypeDefinitionIDProcedure,
		svc.GetAttributesByTypeDefinitionID,
		opts...,
	)
	return "/flexitype.AttributeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AttributeServiceCreateAttributeProcedure:
			attributeServiceCreateAttributeHandler.ServeHTTP(w, r)
		case AttributeServiceUpdateAttributeProcedure:
			attributeServiceUpdateAttributeHandler.ServeHTTP(w, r)
		case AttributeServiceGetAttributeProcedure:
			attributeServiceGetAttributeHandler.ServeHTTP(w, r)
		case AttributeServiceArchiveAttributeProcedure:
			attributeServiceArchiveAttributeHandler.ServeHTTP(w, r)
		case AttributeServiceListAttributesProcedure:
			attributeServiceListAttributesHandler.ServeHTTP(w, r)
		case AttributeServiceGetAttributesByTypeDefinitionIDProcedure:
			attributeServiceGetAttributesByTypeDefinitionIDHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAttributeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAttributeServiceHandler struct{}

func (UnimplementedAttributeServiceHandler) CreateAttribute(context.Context, *connect_go.Request[pb.CreateAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeService.CreateAttribute is not implemented"))
}

func (UnimplementedAttributeServiceHandler) UpdateAttribute(context.Context, *connect_go.Request[pb.UpdateAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeService.UpdateAttribute is not implemented"))
}

func (UnimplementedAttributeServiceHandler) GetAttribute(context.Context, *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeService.GetAttribute is not implemented"))
}

func (UnimplementedAttributeServiceHandler) ArchiveAttribute(context.Context, *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeService.ArchiveAttribute is not implemented"))
}

func (UnimplementedAttributeServiceHandler) ListAttributes(context.Context, *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeService.ListAttributes is not implemented"))
}

func (UnimplementedAttributeServiceHandler) GetAttributesByTypeDefinitionID(context.Context, *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.AttributeList], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.AttributeService.GetAttributesByTypeDefinitionID is not implemented"))
}
