// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: flexitype.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/zkrebbekx/flexitype/internal/api/connect/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// FlexitypeServiceName is the fully-qualified name of the FlexitypeService service.
	FlexitypeServiceName = "flexitype.FlexitypeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FlexitypeServiceCreateTypeDefinitionProcedure is the fully-qualified name of the
	// FlexitypeService's CreateTypeDefinition RPC.
	FlexitypeServiceCreateTypeDefinitionProcedure = "/flexitype.FlexitypeService/CreateTypeDefinition"
	// FlexitypeServiceGetTypeDefinitionProcedure is the fully-qualified name of the FlexitypeService's
	// GetTypeDefinition RPC.
	FlexitypeServiceGetTypeDefinitionProcedure = "/flexitype.FlexitypeService/GetTypeDefinition"
	// FlexitypeServiceUpdateTypeDefinitionProcedure is the fully-qualified name of the
	// FlexitypeService's UpdateTypeDefinition RPC.
	FlexitypeServiceUpdateTypeDefinitionProcedure = "/flexitype.FlexitypeService/UpdateTypeDefinition"
	// FlexitypeServiceArchiveTypeDefinitionProcedure is the fully-qualified name of the
	// FlexitypeService's ArchiveTypeDefinition RPC.
	FlexitypeServiceArchiveTypeDefinitionProcedure = "/flexitype.FlexitypeService/ArchiveTypeDefinition"
	// FlexitypeServiceListTypeDefinitionsProcedure is the fully-qualified name of the
	// FlexitypeService's ListTypeDefinitions RPC.
	FlexitypeServiceListTypeDefinitionsProcedure = "/flexitype.FlexitypeService/ListTypeDefinitions"
	// FlexitypeServiceCreateAttributeProcedure is the fully-qualified name of the FlexitypeService's
	// CreateAttribute RPC.
	FlexitypeServiceCreateAttributeProcedure = "/flexitype.FlexitypeService/CreateAttribute"
	// FlexitypeServiceGetAttributeProcedure is the fully-qualified name of the FlexitypeService's
	// GetAttribute RPC.
	FlexitypeServiceGetAttributeProcedure = "/flexitype.FlexitypeService/GetAttribute"
	// FlexitypeServiceUpdateAttributeProcedure is the fully-qualified name of the FlexitypeService's
	// UpdateAttribute RPC.
	FlexitypeServiceUpdateAttributeProcedure = "/flexitype.FlexitypeService/UpdateAttribute"
	// FlexitypeServiceArchiveAttributeProcedure is the fully-qualified name of the FlexitypeService's
	// ArchiveAttribute RPC.
	FlexitypeServiceArchiveAttributeProcedure = "/flexitype.FlexitypeService/ArchiveAttribute"
	// FlexitypeServiceListAttributesProcedure is the fully-qualified name of the FlexitypeService's
	// ListAttributes RPC.
	FlexitypeServiceListAttributesProcedure = "/flexitype.FlexitypeService/ListAttributes"
	// FlexitypeServiceGetAttributesByTypeDefinitionIDProcedure is the fully-qualified name of the
	// FlexitypeService's GetAttributesByTypeDefinitionID RPC.
	FlexitypeServiceGetAttributesByTypeDefinitionIDProcedure = "/flexitype.FlexitypeService/GetAttributesByTypeDefinitionID"
	// FlexitypeServiceCreateAttributeValueProcedure is the fully-qualified name of the
	// FlexitypeService's CreateAttributeValue RPC.
	FlexitypeServiceCreateAttributeValueProcedure = "/flexitype.FlexitypeService/CreateAttributeValue"
	// FlexitypeServiceGetAttributeValueProcedure is the fully-qualified name of the FlexitypeService's
	// GetAttributeValue RPC.
	FlexitypeServiceGetAttributeValueProcedure = "/flexitype.FlexitypeService/GetAttributeValue"
	// FlexitypeServiceUpdateAttributeValueProcedure is the fully-qualified name of the
	// FlexitypeService's UpdateAttributeValue RPC.
	FlexitypeServiceUpdateAttributeValueProcedure = "/flexitype.FlexitypeService/UpdateAttributeValue"
	// FlexitypeServiceArchiveAttributeValueProcedure is the fully-qualified name of the
	// FlexitypeService's ArchiveAttributeValue RPC.
	FlexitypeServiceArchiveAttributeValueProcedure = "/flexitype.FlexitypeService/ArchiveAttributeValue"
	// FlexitypeServiceListAttributeValuesProcedure is the fully-qualified name of the
	// FlexitypeService's ListAttributeValues RPC.
	FlexitypeServiceListAttributeValuesProcedure = "/flexitype.FlexitypeService/ListAttributeValues"
	// FlexitypeServiceCreateAttributeValueDependencyProcedure is the fully-qualified name of the
	// FlexitypeService's CreateAttributeValueDependency RPC.
	FlexitypeServiceCreateAttributeValueDependencyProcedure = "/flexitype.FlexitypeService/CreateAttributeValueDependency"
	// FlexitypeServiceGetAttributeValueDependencyProcedure is the fully-qualified name of the
	// FlexitypeService's GetAttributeValueDependency RPC.
	FlexitypeServiceGetAttributeValueDependencyProcedure = "/flexitype.FlexitypeService/GetAttributeValueDependency"
	// FlexitypeServiceUpdateAttributeValueDependencyProcedure is the fully-qualified name of the
	// FlexitypeService's UpdateAttributeValueDependency RPC.
	FlexitypeServiceUpdateAttributeValueDependencyProcedure = "/flexitype.FlexitypeService/UpdateAttributeValueDependency"
	// FlexitypeServiceArchiveAttributeValueDependencyProcedure is the fully-qualified name of the
	// FlexitypeService's ArchiveAttributeValueDependency RPC.
	FlexitypeServiceArchiveAttributeValueDependencyProcedure = "/flexitype.FlexitypeService/ArchiveAttributeValueDependency"
	// FlexitypeServiceListAttributeValueDependenciesProcedure is the fully-qualified name of the
	// FlexitypeService's ListAttributeValueDependencies RPC.
	FlexitypeServiceListAttributeValueDependenciesProcedure = "/flexitype.FlexitypeService/ListAttributeValueDependencies"
)

// FlexitypeServiceClient is a client for the flexitype.FlexitypeService service.
type FlexitypeServiceClient interface {
	// Type Definition operations
	CreateTypeDefinition(context.Context, *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error)
	GetTypeDefinition(context.Context, *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	UpdateTypeDefinition(context.Context, *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error)
	ArchiveTypeDefinition(context.Context, *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	ListTypeDefinitions(context.Context, *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error)
	// Attribute operations
	CreateAttribute(context.Context, *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error)
	GetAttribute(context.Context, *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	UpdateAttribute(context.Context, *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error)
	ArchiveAttribute(context.Context, *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	ListAttributes(context.Context, *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error)
	GetAttributesByTypeDefinitionID(context.Context, *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.ListAttributesResponse], error)
	// Attribute Value operations
	CreateAttributeValue(context.Context, *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error)
	GetAttributeValue(context.Context, *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	UpdateAttributeValue(context.Context, *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error)
	ArchiveAttributeValue(context.Context, *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	ListAttributeValues(context.Context, *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error)
	// Attribute Value Dependency operations
	CreateAttributeValueDependency(context.Context, *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error)
	GetAttributeValueDependency(context.Context, *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	UpdateAttributeValueDependency(context.Context, *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error)
	ArchiveAttributeValueDependency(context.Context, *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	ListAttributeValueDependencies(context.Context, *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error)
}

// NewFlexitypeServiceClient constructs a client for the flexitype.FlexitypeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFlexitypeServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) FlexitypeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &flexitypeServiceClient{
		createTypeDefinition: connect_go.NewClient[pb.TypeDefinition, pb.TypeDefinition](
			httpClient,
			baseURL+FlexitypeServiceCreateTypeDefinitionProcedure,
			opts...,
		),
		getTypeDefinition: connect_go.NewClient[pb.GetTypeDefinitionRequest, pb.TypeDefinition](
			httpClient,
			baseURL+FlexitypeServiceGetTypeDefinitionProcedure,
			opts...,
		),
		updateTypeDefinition: connect_go.NewClient[pb.TypeDefinition, pb.TypeDefinition](
			httpClient,
			baseURL+FlexitypeServiceUpdateTypeDefinitionProcedure,
			opts...,
		),
		archiveTypeDefinition: connect_go.NewClient[pb.ArchiveTypeDefinitionRequest, pb.TypeDefinition](
			httpClient,
			baseURL+FlexitypeServiceArchiveTypeDefinitionProcedure,
			opts...,
		),
		listTypeDefinitions: connect_go.NewClient[pb.ListTypeDefinitionsRequest, pb.ListTypeDefinitionsResponse](
			httpClient,
			baseURL+FlexitypeServiceListTypeDefinitionsProcedure,
			opts...,
		),
		createAttribute: connect_go.NewClient[pb.Attribute, pb.Attribute](
			httpClient,
			baseURL+FlexitypeServiceCreateAttributeProcedure,
			opts...,
		),
		getAttribute: connect_go.NewClient[pb.GetAttributeRequest, pb.Attribute](
			httpClient,
			baseURL+FlexitypeServiceGetAttributeProcedure,
			opts...,
		),
		updateAttribute: connect_go.NewClient[pb.Attribute, pb.Attribute](
			httpClient,
			baseURL+FlexitypeServiceUpdateAttributeProcedure,
			opts...,
		),
		archiveAttribute: connect_go.NewClient[pb.ArchiveAttributeRequest, pb.Attribute](
			httpClient,
			baseURL+FlexitypeServiceArchiveAttributeProcedure,
			opts...,
		),
		listAttributes: connect_go.NewClient[pb.ListAttributesRequest, pb.ListAttributesResponse](
			httpClient,
			baseURL+FlexitypeServiceListAttributesProcedure,
			opts...,
		),
		getAttributesByTypeDefinitionID: connect_go.NewClient[pb.GetAttributesByTypeDefinitionIDRequest, pb.ListAttributesResponse](
			httpClient,
			baseURL+FlexitypeServiceGetAttributesByTypeDefinitionIDProcedure,
			opts...,
		),
		createAttributeValue: connect_go.NewClient[pb.AttributeValue, pb.AttributeValue](
			httpClient,
			baseURL+FlexitypeServiceCreateAttributeValueProcedure,
			opts...,
		),
		getAttributeValue: connect_go.NewClient[pb.GetAttributeValueRequest, pb.AttributeValue](
			httpClient,
			baseURL+FlexitypeServiceGetAttributeValueProcedure,
			opts...,
		),
		updateAttributeValue: connect_go.NewClient[pb.AttributeValue, pb.AttributeValue](
			httpClient,
			baseURL+FlexitypeServiceUpdateAttributeValueProcedure,
			opts...,
		),
		archiveAttributeValue: connect_go.NewClient[pb.ArchiveAttributeValueRequest, pb.AttributeValue](
			httpClient,
			baseURL+FlexitypeServiceArchiveAttributeValueProcedure,
			opts...,
		),
		listAttributeValues: connect_go.NewClient[pb.ListAttributeValuesRequest, pb.ListAttributeValuesResponse](
			httpClient,
			baseURL+FlexitypeServiceListAttributeValuesProcedure,
			opts...,
		),
		createAttributeValueDependency: connect_go.NewClient[pb.AttributeValueDependency, pb.AttributeValueDependency](
			httpClient,
			baseURL+FlexitypeServiceCreateAttributeValueDependencyProcedure,
			opts...,
		),
		getAttributeValueDependency: connect_go.NewClient[pb.GetAttributeValueDependencyRequest, pb.AttributeValueDependency](
			httpClient,
			baseURL+FlexitypeServiceGetAttributeValueDependencyProcedure,
			opts...,
		),
		updateAttributeValueDependency: connect_go.NewClient[pb.AttributeValueDependency, pb.AttributeValueDependency](
			httpClient,
			baseURL+FlexitypeServiceUpdateAttributeValueDependencyProcedure,
			opts...,
		),
		archiveAttributeValueDependency: connect_go.NewClient[pb.ArchiveAttributeValueDependencyRequest, pb.AttributeValueDependency](
			httpClient,
			baseURL+FlexitypeServiceArchiveAttributeValueDependencyProcedure,
			opts...,
		),
		listAttributeValueDependencies: connect_go.NewClient[pb.ListAttributeValueDependenciesRequest, pb.ListAttributeValueDependenciesResponse](
			httpClient,
			baseURL+FlexitypeServiceListAttributeValueDependenciesProcedure,
			opts...,
		),
	}
}

// flexitypeServiceClient implements FlexitypeServiceClient.
type flexitypeServiceClient struct {
	createTypeDefinition            *connect_go.Client[pb.TypeDefinition, pb.TypeDefinition]
	getTypeDefinition               *connect_go.Client[pb.GetTypeDefinitionRequest, pb.TypeDefinition]
	updateTypeDefinition            *connect_go.Client[pb.TypeDefinition, pb.TypeDefinition]
	archiveTypeDefinition           *connect_go.Client[pb.ArchiveTypeDefinitionRequest, pb.TypeDefinition]
	listTypeDefinitions             *connect_go.Client[pb.ListTypeDefinitionsRequest, pb.ListTypeDefinitionsResponse]
	createAttribute                 *connect_go.Client[pb.Attribute, pb.Attribute]
	getAttribute                    *connect_go.Client[pb.GetAttributeRequest, pb.Attribute]
	updateAttribute                 *connect_go.Client[pb.Attribute, pb.Attribute]
	archiveAttribute                *connect_go.Client[pb.ArchiveAttributeRequest, pb.Attribute]
	listAttributes                  *connect_go.Client[pb.ListAttributesRequest, pb.ListAttributesResponse]
	getAttributesByTypeDefinitionID *connect_go.Client[pb.GetAttributesByTypeDefinitionIDRequest, pb.ListAttributesResponse]
	createAttributeValue            *connect_go.Client[pb.AttributeValue, pb.AttributeValue]
	getAttributeValue               *connect_go.Client[pb.GetAttributeValueRequest, pb.AttributeValue]
	updateAttributeValue            *connect_go.Client[pb.AttributeValue, pb.AttributeValue]
	archiveAttributeValue           *connect_go.Client[pb.ArchiveAttributeValueRequest, pb.AttributeValue]
	listAttributeValues             *connect_go.Client[pb.ListAttributeValuesRequest, pb.ListAttributeValuesResponse]
	createAttributeValueDependency  *connect_go.Client[pb.AttributeValueDependency, pb.AttributeValueDependency]
	getAttributeValueDependency     *connect_go.Client[pb.GetAttributeValueDependencyRequest, pb.AttributeValueDependency]
	updateAttributeValueDependency  *connect_go.Client[pb.AttributeValueDependency, pb.AttributeValueDependency]
	archiveAttributeValueDependency *connect_go.Client[pb.ArchiveAttributeValueDependencyRequest, pb.AttributeValueDependency]
	listAttributeValueDependencies  *connect_go.Client[pb.ListAttributeValueDependenciesRequest, pb.ListAttributeValueDependenciesResponse]
}

// CreateTypeDefinition calls flexitype.FlexitypeService.CreateTypeDefinition.
func (c *flexitypeServiceClient) CreateTypeDefinition(ctx context.Context, req *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.createTypeDefinition.CallUnary(ctx, req)
}

// GetTypeDefinition calls flexitype.FlexitypeService.GetTypeDefinition.
func (c *flexitypeServiceClient) GetTypeDefinition(ctx context.Context, req *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.getTypeDefinition.CallUnary(ctx, req)
}

// UpdateTypeDefinition calls flexitype.FlexitypeService.UpdateTypeDefinition.
func (c *flexitypeServiceClient) UpdateTypeDefinition(ctx context.Context, req *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.updateTypeDefinition.CallUnary(ctx, req)
}

// ArchiveTypeDefinition calls flexitype.FlexitypeService.ArchiveTypeDefinition.
func (c *flexitypeServiceClient) ArchiveTypeDefinition(ctx context.Context, req *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.archiveTypeDefinition.CallUnary(ctx, req)
}

// ListTypeDefinitions calls flexitype.FlexitypeService.ListTypeDefinitions.
func (c *flexitypeServiceClient) ListTypeDefinitions(ctx context.Context, req *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error) {
	return c.listTypeDefinitions.CallUnary(ctx, req)
}

// CreateAttribute calls flexitype.FlexitypeService.CreateAttribute.
func (c *flexitypeServiceClient) CreateAttribute(ctx context.Context, req *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error) {
	return c.createAttribute.CallUnary(ctx, req)
}

// GetAttribute calls flexitype.FlexitypeService.GetAttribute.
func (c *flexitypeServiceClient) GetAttribute(ctx context.Context, req *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return c.getAttribute.CallUnary(ctx, req)
}

// UpdateAttribute calls flexitype.FlexitypeService.UpdateAttribute.
func (c *flexitypeServiceClient) UpdateAttribute(ctx context.Context, req *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error) {
	return c.updateAttribute.CallUnary(ctx, req)
}

// ArchiveAttribute calls flexitype.FlexitypeService.ArchiveAttribute.
func (c *flexitypeServiceClient) ArchiveAttribute(ctx context.Context, req *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return c.archiveAttribute.CallUnary(ctx, req)
}

// ListAttributes calls flexitype.FlexitypeService.ListAttributes.
func (c *flexitypeServiceClient) ListAttributes(ctx context.Context, req *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error) {
	return c.listAttributes.CallUnary(ctx, req)
}

// GetAttributesByTypeDefinitionID calls flexitype.FlexitypeService.GetAttributesByTypeDefinitionID.
func (c *flexitypeServiceClient) GetAttributesByTypeDefinitionID(ctx context.Context, req *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.ListAttributesResponse], error) {
	return c.getAttributesByTypeDefinitionID.CallUnary(ctx, req)
}

// CreateAttributeValue calls flexitype.FlexitypeService.CreateAttributeValue.
func (c *flexitypeServiceClient) CreateAttributeValue(ctx context.Context, req *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.createAttributeValue.CallUnary(ctx, req)
}

// GetAttributeValue calls flexitype.FlexitypeService.GetAttributeValue.
func (c *flexitypeServiceClient) GetAttributeValue(ctx context.Context, req *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.getAttributeValue.CallUnary(ctx, req)
}

// UpdateAttributeValue calls flexitype.FlexitypeService.UpdateAttributeValue.
func (c *flexitypeServiceClient) UpdateAttributeValue(ctx context.Context, req *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.updateAttributeValue.CallUnary(ctx, req)
}

// ArchiveAttributeValue calls flexitype.FlexitypeService.ArchiveAttributeValue.
func (c *flexitypeServiceClient) ArchiveAttributeValue(ctx context.Context, req *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return c.archiveAttributeValue.CallUnary(ctx, req)
}

// ListAttributeValues calls flexitype.FlexitypeService.ListAttributeValues.
func (c *flexitypeServiceClient) ListAttributeValues(ctx context.Context, req *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error) {
	return c.listAttributeValues.CallUnary(ctx, req)
}

// CreateAttributeValueDependency calls flexitype.FlexitypeService.CreateAttributeValueDependency.
func (c *flexitypeServiceClient) CreateAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.createAttributeValueDependency.CallUnary(ctx, req)
}

// GetAttributeValueDependency calls flexitype.FlexitypeService.GetAttributeValueDependency.
func (c *flexitypeServiceClient) GetAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.getAttributeValueDependency.CallUnary(ctx, req)
}

// UpdateAttributeValueDependency calls flexitype.FlexitypeService.UpdateAttributeValueDependency.
func (c *flexitypeServiceClient) UpdateAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.updateAttributeValueDependency.CallUnary(ctx, req)
}

// ArchiveAttributeValueDependency calls flexitype.FlexitypeService.ArchiveAttributeValueDependency.
func (c *flexitypeServiceClient) ArchiveAttributeValueDependency(ctx context.Context, req *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return c.archiveAttributeValueDependency.CallUnary(ctx, req)
}

// ListAttributeValueDependencies calls flexitype.FlexitypeService.ListAttributeValueDependencies.
func (c *flexitypeServiceClient) ListAttributeValueDependencies(ctx context.Context, req *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error) {
	return c.listAttributeValueDependencies.CallUnary(ctx, req)
}

// FlexitypeServiceHandler is an implementation of the flexitype.FlexitypeService service.
type FlexitypeServiceHandler interface {
	// Type Definition operations
	CreateTypeDefinition(context.Context, *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error)
	GetTypeDefinition(context.Context, *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	UpdateTypeDefinition(context.Context, *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error)
	ArchiveTypeDefinition(context.Context, *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	ListTypeDefinitions(context.Context, *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error)
	// Attribute operations
	CreateAttribute(context.Context, *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error)
	GetAttribute(context.Context, *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	UpdateAttribute(context.Context, *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error)
	ArchiveAttribute(context.Context, *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[pb.Attribute], error)
	ListAttributes(context.Context, *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error)
	GetAttributesByTypeDefinitionID(context.Context, *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.ListAttributesResponse], error)
	// Attribute Value operations
	CreateAttributeValue(context.Context, *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error)
	GetAttributeValue(context.Context, *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	UpdateAttributeValue(context.Context, *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error)
	ArchiveAttributeValue(context.Context, *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error)
	ListAttributeValues(context.Context, *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error)
	// Attribute Value Dependency operations
	CreateAttributeValueDependency(context.Context, *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error)
	GetAttributeValueDependency(context.Context, *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	UpdateAttributeValueDependency(context.Context, *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error)
	ArchiveAttributeValueDependency(context.Context, *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error)
	ListAttributeValueDependencies(context.Context, *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error)
}

// NewFlexitypeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFlexitypeServiceHandler(svc FlexitypeServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	flexitypeServiceCreateTypeDefinitionHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceCreateTypeDefinitionProcedure,
		svc.CreateTypeDefinition,
		opts...,
	)
	flexitypeServiceGetTypeDefinitionHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceGetTypeDefinitionProcedure,
		svc.GetTypeDefinition,
		opts...,
	)
	flexitypeServiceUpdateTypeDefinitionHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceUpdateTypeDefinitionProcedure,
		svc.UpdateTypeDefinition,
		opts...,
	)
	flexitypeServiceArchiveTypeDefinitionHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceArchiveTypeDefinitionProcedure,
		svc.ArchiveTypeDefinition,
		opts...,
	)
	flexitypeServiceListTypeDefinitionsHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceListTypeDefinitionsProcedure,
		svc.ListTypeDefinitions,
		opts...,
	)
	flexitypeServiceCreateAttributeHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceCreateAttributeProcedure,
		svc.CreateAttribute,
		opts...,
	)
	flexitypeServiceGetAttributeHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceGetAttributeProcedure,
		svc.GetAttribute,
		opts...,
	)
	flexitypeServiceUpdateAttributeHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceUpdateAttributeProcedure,
		svc.UpdateAttribute,
		opts...,
	)
	flexitypeServiceArchiveAttributeHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceArchiveAttributeProcedure,
		svc.ArchiveAttribute,
		opts...,
	)
	flexitypeServiceListAttributesHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceListAttributesProcedure,
		svc.ListAttributes,
		opts...,
	)
	flexitypeServiceGetAttributesByTypeDefinitionIDHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceGetAttributesByTypeDefinitionIDProcedure,
		svc.GetAttributesByTypeDefinitionID,
		opts...,
	)
	flexitypeServiceCreateAttributeValueHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceCreateAttributeValueProcedure,
		svc.CreateAttributeValue,
		opts...,
	)
	flexitypeServiceGetAttributeValueHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceGetAttributeValueProcedure,
		svc.GetAttributeValue,
		opts...,
	)
	flexitypeServiceUpdateAttributeValueHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceUpdateAttributeValueProcedure,
		svc.UpdateAttributeValue,
		opts...,
	)
	flexitypeServiceArchiveAttributeValueHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceArchiveAttributeValueProcedure,
		svc.ArchiveAttributeValue,
		opts...,
	)
	flexitypeServiceListAttributeValuesHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceListAttributeValuesProcedure,
		svc.ListAttributeValues,
		opts...,
	)
	flexitypeServiceCreateAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceCreateAttributeValueDependencyProcedure,
		svc.CreateAttributeValueDependency,
		opts...,
	)
	flexitypeServiceGetAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceGetAttributeValueDependencyProcedure,
		svc.GetAttributeValueDependency,
		opts...,
	)
	flexitypeServiceUpdateAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceUpdateAttributeValueDependencyProcedure,
		svc.UpdateAttributeValueDependency,
		opts...,
	)
	flexitypeServiceArchiveAttributeValueDependencyHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceArchiveAttributeValueDependencyProcedure,
		svc.ArchiveAttributeValueDependency,
		opts...,
	)
	flexitypeServiceListAttributeValueDependenciesHandler := connect_go.NewUnaryHandler(
		FlexitypeServiceListAttributeValueDependenciesProcedure,
		svc.ListAttributeValueDependencies,
		opts...,
	)
	return "/flexitype.FlexitypeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FlexitypeServiceCreateTypeDefinitionProcedure:
			flexitypeServiceCreateTypeDefinitionHandler.ServeHTTP(w, r)
		case FlexitypeServiceGetTypeDefinitionProcedure:
			flexitypeServiceGetTypeDefinitionHandler.ServeHTTP(w, r)
		case FlexitypeServiceUpdateTypeDefinitionProcedure:
			flexitypeServiceUpdateTypeDefinitionHandler.ServeHTTP(w, r)
		case FlexitypeServiceArchiveTypeDefinitionProcedure:
			flexitypeServiceArchiveTypeDefinitionHandler.ServeHTTP(w, r)
		case FlexitypeServiceListTypeDefinitionsProcedure:
			flexitypeServiceListTypeDefinitionsHandler.ServeHTTP(w, r)
		case FlexitypeServiceCreateAttributeProcedure:
			flexitypeServiceCreateAttributeHandler.ServeHTTP(w, r)
		case FlexitypeServiceGetAttributeProcedure:
			flexitypeServiceGetAttributeHandler.ServeHTTP(w, r)
		case FlexitypeServiceUpdateAttributeProcedure:
			flexitypeServiceUpdateAttributeHandler.ServeHTTP(w, r)
		case FlexitypeServiceArchiveAttributeProcedure:
			flexitypeServiceArchiveAttributeHandler.ServeHTTP(w, r)
		case FlexitypeServiceListAttributesProcedure:
			flexitypeServiceListAttributesHandler.ServeHTTP(w, r)
		case FlexitypeServiceGetAttributesByTypeDefinitionIDProcedure:
			flexitypeServiceGetAttributesByTypeDefinitionIDHandler.ServeHTTP(w, r)
		case FlexitypeServiceCreateAttributeValueProcedure:
			flexitypeServiceCreateAttributeValueHandler.ServeHTTP(w, r)
		case FlexitypeServiceGetAttributeValueProcedure:
			flexitypeServiceGetAttributeValueHandler.ServeHTTP(w, r)
		case FlexitypeServiceUpdateAttributeValueProcedure:
			flexitypeServiceUpdateAttributeValueHandler.ServeHTTP(w, r)
		case FlexitypeServiceArchiveAttributeValueProcedure:
			flexitypeServiceArchiveAttributeValueHandler.ServeHTTP(w, r)
		case FlexitypeServiceListAttributeValuesProcedure:
			flexitypeServiceListAttributeValuesHandler.ServeHTTP(w, r)
		case FlexitypeServiceCreateAttributeValueDependencyProcedure:
			flexitypeServiceCreateAttributeValueDependencyHandler.ServeHTTP(w, r)
		case FlexitypeServiceGetAttributeValueDependencyProcedure:
			flexitypeServiceGetAttributeValueDependencyHandler.ServeHTTP(w, r)
		case FlexitypeServiceUpdateAttributeValueDependencyProcedure:
			flexitypeServiceUpdateAttributeValueDependencyHandler.ServeHTTP(w, r)
		case FlexitypeServiceArchiveAttributeValueDependencyProcedure:
			flexitypeServiceArchiveAttributeValueDependencyHandler.ServeHTTP(w, r)
		case FlexitypeServiceListAttributeValueDependenciesProcedure:
			flexitypeServiceListAttributeValueDependenciesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFlexitypeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFlexitypeServiceHandler struct{}

func (UnimplementedFlexitypeServiceHandler) CreateTypeDefinition(context.Context, *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.CreateTypeDefinition is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) GetTypeDefinition(context.Context, *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.GetTypeDefinition is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) UpdateTypeDefinition(context.Context, *connect_go.Request[pb.TypeDefinition]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.UpdateTypeDefinition is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ArchiveTypeDefinition(context.Context, *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ArchiveTypeDefinition is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ListTypeDefinitions(context.Context, *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ListTypeDefinitions is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) CreateAttribute(context.Context, *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.CreateAttribute is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) GetAttribute(context.Context, *connect_go.Request[pb.GetAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.GetAttribute is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) UpdateAttribute(context.Context, *connect_go.Request[pb.Attribute]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.UpdateAttribute is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ArchiveAttribute(context.Context, *connect_go.Request[pb.ArchiveAttributeRequest]) (*connect_go.Response[pb.Attribute], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ArchiveAttribute is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ListAttributes(context.Context, *connect_go.Request[pb.ListAttributesRequest]) (*connect_go.Response[pb.ListAttributesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ListAttributes is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) GetAttributesByTypeDefinitionID(context.Context, *connect_go.Request[pb.GetAttributesByTypeDefinitionIDRequest]) (*connect_go.Response[pb.ListAttributesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.GetAttributesByTypeDefinitionID is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) CreateAttributeValue(context.Context, *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.CreateAttributeValue is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) GetAttributeValue(context.Context, *connect_go.Request[pb.GetAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.GetAttributeValue is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) UpdateAttributeValue(context.Context, *connect_go.Request[pb.AttributeValue]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.UpdateAttributeValue is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ArchiveAttributeValue(context.Context, *connect_go.Request[pb.ArchiveAttributeValueRequest]) (*connect_go.Response[pb.AttributeValue], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ArchiveAttributeValue is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ListAttributeValues(context.Context, *connect_go.Request[pb.ListAttributeValuesRequest]) (*connect_go.Response[pb.ListAttributeValuesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ListAttributeValues is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) CreateAttributeValueDependency(context.Context, *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.CreateAttributeValueDependency is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) GetAttributeValueDependency(context.Context, *connect_go.Request[pb.GetAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.GetAttributeValueDependency is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) UpdateAttributeValueDependency(context.Context, *connect_go.Request[pb.AttributeValueDependency]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.UpdateAttributeValueDependency is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ArchiveAttributeValueDependency(context.Context, *connect_go.Request[pb.ArchiveAttributeValueDependencyRequest]) (*connect_go.Response[pb.AttributeValueDependency], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ArchiveAttributeValueDependency is not implemented"))
}

func (UnimplementedFlexitypeServiceHandler) ListAttributeValueDependencies(context.Context, *connect_go.Request[pb.ListAttributeValueDependenciesRequest]) (*connect_go.Response[pb.ListAttributeValueDependenciesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.FlexitypeService.ListAttributeValueDependencies is not implemented"))
}
