// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: type_definition.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/zkrebbekx/flexitype/internal/api/connect/pb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// TypeDefinitionServiceName is the fully-qualified name of the TypeDefinitionService service.
	TypeDefinitionServiceName = "flexitype.TypeDefinitionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TypeDefinitionServiceCreateTypeDefinitionProcedure is the fully-qualified name of the
	// TypeDefinitionService's CreateTypeDefinition RPC.
	TypeDefinitionServiceCreateTypeDefinitionProcedure = "/flexitype.TypeDefinitionService/CreateTypeDefinition"
	// TypeDefinitionServiceUpdateTypeDefinitionProcedure is the fully-qualified name of the
	// TypeDefinitionService's UpdateTypeDefinition RPC.
	TypeDefinitionServiceUpdateTypeDefinitionProcedure = "/flexitype.TypeDefinitionService/UpdateTypeDefinition"
	// TypeDefinitionServiceGetTypeDefinitionProcedure is the fully-qualified name of the
	// TypeDefinitionService's GetTypeDefinition RPC.
	TypeDefinitionServiceGetTypeDefinitionProcedure = "/flexitype.TypeDefinitionService/GetTypeDefinition"
	// TypeDefinitionServiceArchiveTypeDefinitionProcedure is the fully-qualified name of the
	// TypeDefinitionService's ArchiveTypeDefinition RPC.
	TypeDefinitionServiceArchiveTypeDefinitionProcedure = "/flexitype.TypeDefinitionService/ArchiveTypeDefinition"
	// TypeDefinitionServiceListTypeDefinitionsProcedure is the fully-qualified name of the
	// TypeDefinitionService's ListTypeDefinitions RPC.
	TypeDefinitionServiceListTypeDefinitionsProcedure = "/flexitype.TypeDefinitionService/ListTypeDefinitions"
)

// TypeDefinitionServiceClient is a client for the flexitype.TypeDefinitionService service.
type TypeDefinitionServiceClient interface {
	// CreateTypeDefinition creates a new type definition
	CreateTypeDefinition(context.Context, *connect_go.Request[pb.CreateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	// UpdateTypeDefinition updates an existing type definition
	UpdateTypeDefinition(context.Context, *connect_go.Request[pb.UpdateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	// GetTypeDefinition retrieves a type definition by ID
	GetTypeDefinition(context.Context, *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	// ArchiveTypeDefinition archives a type definition
	ArchiveTypeDefinition(context.Context, *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListTypeDefinitions lists type definitions based on filter criteria
	ListTypeDefinitions(context.Context, *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error)
}

// NewTypeDefinitionServiceClient constructs a client for the flexitype.TypeDefinitionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTypeDefinitionServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) TypeDefinitionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &typeDefinitionServiceClient{
		createTypeDefinition: connect_go.NewClient[pb.CreateTypeDefinitionRequest, pb.TypeDefinition](
			httpClient,
			baseURL+TypeDefinitionServiceCreateTypeDefinitionProcedure,
			opts...,
		),
		updateTypeDefinition: connect_go.NewClient[pb.UpdateTypeDefinitionRequest, pb.TypeDefinition](
			httpClient,
			baseURL+TypeDefinitionServiceUpdateTypeDefinitionProcedure,
			opts...,
		),
		getTypeDefinition: connect_go.NewClient[pb.GetTypeDefinitionRequest, pb.TypeDefinition](
			httpClient,
			baseURL+TypeDefinitionServiceGetTypeDefinitionProcedure,
			opts...,
		),
		archiveTypeDefinition: connect_go.NewClient[pb.ArchiveTypeDefinitionRequest, emptypb.Empty](
			httpClient,
			baseURL+TypeDefinitionServiceArchiveTypeDefinitionProcedure,
			opts...,
		),
		listTypeDefinitions: connect_go.NewClient[pb.ListTypeDefinitionsRequest, pb.ListTypeDefinitionsResponse](
			httpClient,
			baseURL+TypeDefinitionServiceListTypeDefinitionsProcedure,
			opts...,
		),
	}
}

// typeDefinitionServiceClient implements TypeDefinitionServiceClient.
type typeDefinitionServiceClient struct {
	createTypeDefinition  *connect_go.Client[pb.CreateTypeDefinitionRequest, pb.TypeDefinition]
	updateTypeDefinition  *connect_go.Client[pb.UpdateTypeDefinitionRequest, pb.TypeDefinition]
	getTypeDefinition     *connect_go.Client[pb.GetTypeDefinitionRequest, pb.TypeDefinition]
	archiveTypeDefinition *connect_go.Client[pb.ArchiveTypeDefinitionRequest, emptypb.Empty]
	listTypeDefinitions   *connect_go.Client[pb.ListTypeDefinitionsRequest, pb.ListTypeDefinitionsResponse]
}

// CreateTypeDefinition calls flexitype.TypeDefinitionService.CreateTypeDefinition.
func (c *typeDefinitionServiceClient) CreateTypeDefinition(ctx context.Context, req *connect_go.Request[pb.CreateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.createTypeDefinition.CallUnary(ctx, req)
}

// UpdateTypeDefinition calls flexitype.TypeDefinitionService.UpdateTypeDefinition.
func (c *typeDefinitionServiceClient) UpdateTypeDefinition(ctx context.Context, req *connect_go.Request[pb.UpdateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.updateTypeDefinition.CallUnary(ctx, req)
}

// GetTypeDefinition calls flexitype.TypeDefinitionService.GetTypeDefinition.
func (c *typeDefinitionServiceClient) GetTypeDefinition(ctx context.Context, req *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return c.getTypeDefinition.CallUnary(ctx, req)
}

// ArchiveTypeDefinition calls flexitype.TypeDefinitionService.ArchiveTypeDefinition.
func (c *typeDefinitionServiceClient) ArchiveTypeDefinition(ctx context.Context, req *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.archiveTypeDefinition.CallUnary(ctx, req)
}

// ListTypeDefinitions calls flexitype.TypeDefinitionService.ListTypeDefinitions.
func (c *typeDefinitionServiceClient) ListTypeDefinitions(ctx context.Context, req *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error) {
	return c.listTypeDefinitions.CallUnary(ctx, req)
}

// TypeDefinitionServiceHandler is an implementation of the flexitype.TypeDefinitionService service.
type TypeDefinitionServiceHandler interface {
	// CreateTypeDefinition creates a new type definition
	CreateTypeDefinition(context.Context, *connect_go.Request[pb.CreateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	// UpdateTypeDefinition updates an existing type definition
	UpdateTypeDefinition(context.Context, *connect_go.Request[pb.UpdateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	// GetTypeDefinition retrieves a type definition by ID
	GetTypeDefinition(context.Context, *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error)
	// ArchiveTypeDefinition archives a type definition
	ArchiveTypeDefinition(context.Context, *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[emptypb.Empty], error)
	// ListTypeDefinitions lists type definitions based on filter criteria
	ListTypeDefinitions(context.Context, *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error)
}

// NewTypeDefinitionServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTypeDefinitionServiceHandler(svc TypeDefinitionServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	typeDefinitionServiceCreateTypeDefinitionHandler := connect_go.NewUnaryHandler(
		TypeDefinitionServiceCreateTypeDefinitionProcedure,
		svc.CreateTypeDefinition,
		opts...,
	)
	typeDefinitionServiceUpdateTypeDefinitionHandler := connect_go.NewUnaryHandler(
		TypeDefinitionServiceUpdateTypeDefinitionProcedure,
		svc.UpdateTypeDefinition,
		opts...,
	)
	typeDefinitionServiceGetTypeDefinitionHandler := connect_go.NewUnaryHandler(
		TypeDefinitionServiceGetTypeDefinitionProcedure,
		svc.GetTypeDefinition,
		opts...,
	)
	typeDefinitionServiceArchiveTypeDefinitionHandler := connect_go.NewUnaryHandler(
		TypeDefinitionServiceArchiveTypeDefinitionProcedure,
		svc.ArchiveTypeDefinition,
		opts...,
	)
	typeDefinitionServiceListTypeDefinitionsHandler := connect_go.NewUnaryHandler(
		TypeDefinitionServiceListTypeDefinitionsProcedure,
		svc.ListTypeDefinitions,
		opts...,
	)
	return "/flexitype.TypeDefinitionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TypeDefinitionServiceCreateTypeDefinitionProcedure:
			typeDefinitionServiceCreateTypeDefinitionHandler.ServeHTTP(w, r)
		case TypeDefinitionServiceUpdateTypeDefinitionProcedure:
			typeDefinitionServiceUpdateTypeDefinitionHandler.ServeHTTP(w, r)
		case TypeDefinitionServiceGetTypeDefinitionProcedure:
			typeDefinitionServiceGetTypeDefinitionHandler.ServeHTTP(w, r)
		case TypeDefinitionServiceArchiveTypeDefinitionProcedure:
			typeDefinitionServiceArchiveTypeDefinitionHandler.ServeHTTP(w, r)
		case TypeDefinitionServiceListTypeDefinitionsProcedure:
			typeDefinitionServiceListTypeDefinitionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTypeDefinitionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTypeDefinitionServiceHandler struct{}

func (UnimplementedTypeDefinitionServiceHandler) CreateTypeDefinition(context.Context, *connect_go.Request[pb.CreateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.TypeDefinitionService.CreateTypeDefinition is not implemented"))
}

func (UnimplementedTypeDefinitionServiceHandler) UpdateTypeDefinition(context.Context, *connect_go.Request[pb.UpdateTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.TypeDefinitionService.UpdateTypeDefinition is not implemented"))
}

func (UnimplementedTypeDefinitionServiceHandler) GetTypeDefinition(context.Context, *connect_go.Request[pb.GetTypeDefinitionRequest]) (*connect_go.Response[pb.TypeDefinition], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.TypeDefinitionService.GetTypeDefinition is not implemented"))
}

func (UnimplementedTypeDefinitionServiceHandler) ArchiveTypeDefinition(context.Context, *connect_go.Request[pb.ArchiveTypeDefinitionRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.TypeDefinitionService.ArchiveTypeDefinition is not implemented"))
}

func (UnimplementedTypeDefinitionServiceHandler) ListTypeDefinitions(context.Context, *connect_go.Request[pb.ListTypeDefinitionsRequest]) (*connect_go.Response[pb.ListTypeDefinitionsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("flexitype.TypeDefinitionService.ListTypeDefinitions is not implemented"))
}
