// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/connect/attribute_value.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributeValue represents a value for an attribute
type AttributeValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeId   string                 `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeValue) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

func (x *AttributeValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AttributeValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AttributeValue) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AttributeValue) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AttributeValue) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

// AttributeValueList represents a list of attribute values
type AttributeValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AttributeValue      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValueList) Reset() {
	*x = AttributeValueList{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValueList) ProtoMessage() {}

func (x *AttributeValueList) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValueList.ProtoReflect.Descriptor instead.
func (*AttributeValueList) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeValueList) GetValues() []*AttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// CreateAttributeValueRequest represents a request to create an attribute value
type CreateAttributeValueRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AttributeDefinitionId string                 `protobuf:"bytes,1,opt,name=attribute_definition_id,json=attributeDefinitionId,proto3" json:"attribute_definition_id,omitempty"`
	Value                 string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateAttributeValueRequest) Reset() {
	*x = CreateAttributeValueRequest{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeValueRequest) ProtoMessage() {}

func (x *CreateAttributeValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeValueRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeValueRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAttributeValueRequest) GetAttributeDefinitionId() string {
	if x != nil {
		return x.AttributeDefinitionId
	}
	return ""
}

func (x *CreateAttributeValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// UpdateAttributeValueRequest represents a request to update an attribute value
type UpdateAttributeValueRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeDefinitionId string                 `protobuf:"bytes,2,opt,name=attribute_definition_id,json=attributeDefinitionId,proto3" json:"attribute_definition_id,omitempty"`
	Value                 string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version               int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateAttributeValueRequest) Reset() {
	*x = UpdateAttributeValueRequest{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttributeValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttributeValueRequest) ProtoMessage() {}

func (x *UpdateAttributeValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttributeValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttributeValueRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAttributeValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAttributeValueRequest) GetAttributeDefinitionId() string {
	if x != nil {
		return x.AttributeDefinitionId
	}
	return ""
}

func (x *UpdateAttributeValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateAttributeValueRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetAttributeValueRequest represents a request to get an attribute value
type GetAttributeValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeValueRequest) Reset() {
	*x = GetAttributeValueRequest{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeValueRequest) ProtoMessage() {}

func (x *GetAttributeValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeValueRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeValueRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttributeValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ArchiveAttributeValueRequest represents a request to archive an attribute value
type ArchiveAttributeValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveAttributeValueRequest) Reset() {
	*x = ArchiveAttributeValueRequest{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveAttributeValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveAttributeValueRequest) ProtoMessage() {}

func (x *ArchiveAttributeValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveAttributeValueRequest.ProtoReflect.Descriptor instead.
func (*ArchiveAttributeValueRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveAttributeValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListAttributeValuesRequest represents a request to list attribute values
type ListAttributeValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LatestVersion bool                   `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	AttributeId   string                 `protobuf:"bytes,4,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributeValuesRequest) Reset() {
	*x = ListAttributeValuesRequest{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeValuesRequest) ProtoMessage() {}

func (x *ListAttributeValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeValuesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributeValuesRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{6}
}

func (x *ListAttributeValuesRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListAttributeValuesRequest) GetLatestVersion() bool {
	if x != nil {
		return x.LatestVersion
	}
	return false
}

func (x *ListAttributeValuesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListAttributeValuesRequest) GetAttributeId() string {
	if x != nil {
		return x.AttributeId
	}
	return ""
}

// ListAttributeValuesResponse represents a response to list attribute values
type ListAttributeValuesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttributeValues []*AttributeValue      `protobuf:"bytes,1,rep,name=attribute_values,json=attributeValues,proto3" json:"attribute_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAttributeValuesResponse) Reset() {
	*x = ListAttributeValuesResponse{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeValuesResponse) ProtoMessage() {}

func (x *ListAttributeValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeValuesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributeValuesResponse) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{7}
}

func (x *ListAttributeValuesResponse) GetAttributeValues() []*AttributeValue {
	if x != nil {
		return x.AttributeValues
	}
	return nil
}

// GetAttributeValuesByAttributeIDRequest represents a request to get values by attribute ID
type GetAttributeValuesByAttributeIDRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AttributeDefinitionId string                 `protobuf:"bytes,1,opt,name=attribute_definition_id,json=attributeDefinitionId,proto3" json:"attribute_definition_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAttributeValuesByAttributeIDRequest) Reset() {
	*x = GetAttributeValuesByAttributeIDRequest{}
	mi := &file_api_connect_attribute_value_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeValuesByAttributeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeValuesByAttributeIDRequest) ProtoMessage() {}

func (x *GetAttributeValuesByAttributeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_attribute_value_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeValuesByAttributeIDRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeValuesByAttributeIDRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_attribute_value_proto_rawDescGZIP(), []int{8}
}

func (x *GetAttributeValuesByAttributeIDRequest) GetAttributeDefinitionId() string {
	if x != nil {
		return x.AttributeDefinitionId
	}
	return ""
}

var File_api_connect_attribute_value_proto protoreflect.FileDescriptor

const file_api_connect_attribute_value_proto_rawDesc = "" +
	"\n" +
	"!api/connect/attribute_value.proto\x12\tflexitype\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa6\x02\n" +
	"\x0eAttributeValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fattribute_id\x18\x02 \x01(\tR\vattributeId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\varchived_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\"G\n" +
	"\x12AttributeValueList\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.flexitype.AttributeValueR\x06values\"k\n" +
	"\x1bCreateAttributeValueRequest\x126\n" +
	"\x17attribute_definition_id\x18\x01 \x01(\tR\x15attributeDefinitionId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x95\x01\n" +
	"\x1bUpdateAttributeValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x17attribute_definition_id\x18\x02 \x01(\tR\x15attributeDefinitionId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"*\n" +
	"\x18GetAttributeValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x1cArchiveAttributeValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x92\x01\n" +
	"\x1aListAttributeValuesRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\bR\rlatestVersion\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12!\n" +
	"\fattribute_id\x18\x04 \x01(\tR\vattributeId\"c\n" +
	"\x1bListAttributeValuesResponse\x12D\n" +
	"\x10attribute_values\x18\x01 \x03(\v2\x19.flexitype.AttributeValueR\x0fattributeValues\"`\n" +
	"&GetAttributeValuesByAttributeIDRequest\x126\n" +
	"\x17attribute_definition_id\x18\x01 \x01(\tR\x15attributeDefinitionId2\xe3\x04\n" +
	"\x15AttributeValueService\x12[\n" +
	"\x14CreateAttributeValue\x12&.flexitype.CreateAttributeValueRequest\x1a\x19.flexitype.AttributeValue\"\x00\x12[\n" +
	"\x14UpdateAttributeValue\x12&.flexitype.UpdateAttributeValueRequest\x1a\x19.flexitype.AttributeValue\"\x00\x12U\n" +
	"\x11GetAttributeValue\x12#.flexitype.GetAttributeValueRequest\x1a\x19.flexitype.AttributeValue\"\x00\x12Z\n" +
	"\x15ArchiveAttributeValue\x12'.flexitype.ArchiveAttributeValueRequest\x1a\x16.google.protobuf.Empty\"\x00\x12f\n" +
	"\x13ListAttributeValues\x12%.flexitype.ListAttributeValuesRequest\x1a&.flexitype.ListAttributeValuesResponse\"\x00\x12u\n" +
	"\x1fGetAttributeValuesByAttributeID\x121.flexitype.GetAttributeValuesByAttributeIDRequest\x1a\x1d.flexitype.AttributeValueList\"\x00B8Z6github.com/zkrebbekx/flexitype/internal/api/connect/pbb\x06proto3"

var (
	file_api_connect_attribute_value_proto_rawDescOnce sync.Once
	file_api_connect_attribute_value_proto_rawDescData []byte
)

func file_api_connect_attribute_value_proto_rawDescGZIP() []byte {
	file_api_connect_attribute_value_proto_rawDescOnce.Do(func() {
		file_api_connect_attribute_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_connect_attribute_value_proto_rawDesc), len(file_api_connect_attribute_value_proto_rawDesc)))
	})
	return file_api_connect_attribute_value_proto_rawDescData
}

var file_api_connect_attribute_value_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_connect_attribute_value_proto_goTypes = []any{
	(*AttributeValue)(nil),                         // 0: flexitype.AttributeValue
	(*AttributeValueList)(nil),                     // 1: flexitype.AttributeValueList
	(*CreateAttributeValueRequest)(nil),            // 2: flexitype.CreateAttributeValueRequest
	(*UpdateAttributeValueRequest)(nil),            // 3: flexitype.UpdateAttributeValueRequest
	(*GetAttributeValueRequest)(nil),               // 4: flexitype.GetAttributeValueRequest
	(*ArchiveAttributeValueRequest)(nil),           // 5: flexitype.ArchiveAttributeValueRequest
	(*ListAttributeValuesRequest)(nil),             // 6: flexitype.ListAttributeValuesRequest
	(*ListAttributeValuesResponse)(nil),            // 7: flexitype.ListAttributeValuesResponse
	(*GetAttributeValuesByAttributeIDRequest)(nil), // 8: flexitype.GetAttributeValuesByAttributeIDRequest
	(*timestamppb.Timestamp)(nil),                  // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                          // 10: google.protobuf.Empty
}
var file_api_connect_attribute_value_proto_depIdxs = []int32{
	9,  // 0: flexitype.AttributeValue.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: flexitype.AttributeValue.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: flexitype.AttributeValue.archived_at:type_name -> google.protobuf.Timestamp
	0,  // 3: flexitype.AttributeValueList.values:type_name -> flexitype.AttributeValue
	0,  // 4: flexitype.ListAttributeValuesResponse.attribute_values:type_name -> flexitype.AttributeValue
	2,  // 5: flexitype.AttributeValueService.CreateAttributeValue:input_type -> flexitype.CreateAttributeValueRequest
	3,  // 6: flexitype.AttributeValueService.UpdateAttributeValue:input_type -> flexitype.UpdateAttributeValueRequest
	4,  // 7: flexitype.AttributeValueService.GetAttributeValue:input_type -> flexitype.GetAttributeValueRequest
	5,  // 8: flexitype.AttributeValueService.ArchiveAttributeValue:input_type -> flexitype.ArchiveAttributeValueRequest
	6,  // 9: flexitype.AttributeValueService.ListAttributeValues:input_type -> flexitype.ListAttributeValuesRequest
	8,  // 10: flexitype.AttributeValueService.GetAttributeValuesByAttributeID:input_type -> flexitype.GetAttributeValuesByAttributeIDRequest
	0,  // 11: flexitype.AttributeValueService.CreateAttributeValue:output_type -> flexitype.AttributeValue
	0,  // 12: flexitype.AttributeValueService.UpdateAttributeValue:output_type -> flexitype.AttributeValue
	0,  // 13: flexitype.AttributeValueService.GetAttributeValue:output_type -> flexitype.AttributeValue
	10, // 14: flexitype.AttributeValueService.ArchiveAttributeValue:output_type -> google.protobuf.Empty
	7,  // 15: flexitype.AttributeValueService.ListAttributeValues:output_type -> flexitype.ListAttributeValuesResponse
	1,  // 16: flexitype.AttributeValueService.GetAttributeValuesByAttributeID:output_type -> flexitype.AttributeValueList
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_connect_attribute_value_proto_init() }
func file_api_connect_attribute_value_proto_init() {
	if File_api_connect_attribute_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_connect_attribute_value_proto_rawDesc), len(file_api_connect_attribute_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_connect_attribute_value_proto_goTypes,
		DependencyIndexes: file_api_connect_attribute_value_proto_depIdxs,
		MessageInfos:      file_api_connect_attribute_value_proto_msgTypes,
	}.Build()
	File_api_connect_attribute_value_proto = out.File
	file_api_connect_attribute_value_proto_goTypes = nil
	file_api_connect_attribute_value_proto_depIdxs = nil
}
