// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/connect/type_definition.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeDefinition represents a type definition in the system
type TypeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDefinition) Reset() {
	*x = TypeDefinition{}
	mi := &file_api_connect_type_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinition) ProtoMessage() {}

func (x *TypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinition.ProtoReflect.Descriptor instead.
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{0}
}

func (x *TypeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TypeDefinition) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TypeDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TypeDefinition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TypeDefinition) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

// TypeDefinitionList represents a list of type definitions
type TypeDefinitionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*TypeDefinition      `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDefinitionList) Reset() {
	*x = TypeDefinitionList{}
	mi := &file_api_connect_type_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDefinitionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinitionList) ProtoMessage() {}

func (x *TypeDefinitionList) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinitionList.ProtoReflect.Descriptor instead.
func (*TypeDefinitionList) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{1}
}

func (x *TypeDefinitionList) GetDefinitions() []*TypeDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

// CreateTypeDefinitionRequest represents a request to create a type definition
type CreateTypeDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeDefinitionRequest) Reset() {
	*x = CreateTypeDefinitionRequest{}
	mi := &file_api_connect_type_definition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeDefinitionRequest) ProtoMessage() {}

func (x *CreateTypeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateTypeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTypeDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTypeDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UpdateTypeDefinitionRequest represents a request to update a type definition
type UpdateTypeDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTypeDefinitionRequest) Reset() {
	*x = UpdateTypeDefinitionRequest{}
	mi := &file_api_connect_type_definition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypeDefinitionRequest) ProtoMessage() {}

func (x *UpdateTypeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTypeDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTypeDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTypeDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTypeDefinitionRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// GetTypeDefinitionRequest represents a request to get a type definition
type GetTypeDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeDefinitionRequest) Reset() {
	*x = GetTypeDefinitionRequest{}
	mi := &file_api_connect_type_definition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeDefinitionRequest) ProtoMessage() {}

func (x *GetTypeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetTypeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{4}
}

func (x *GetTypeDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ArchiveTypeDefinitionRequest represents a request to archive a type definition
type ArchiveTypeDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveTypeDefinitionRequest) Reset() {
	*x = ArchiveTypeDefinitionRequest{}
	mi := &file_api_connect_type_definition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveTypeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTypeDefinitionRequest) ProtoMessage() {}

func (x *ArchiveTypeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTypeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*ArchiveTypeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{5}
}

func (x *ArchiveTypeDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListTypeDefinitionsRequest represents a request to list type definitions
type ListTypeDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LatestVersion bool                   `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypeDefinitionsRequest) Reset() {
	*x = ListTypeDefinitionsRequest{}
	mi := &file_api_connect_type_definition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypeDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypeDefinitionsRequest) ProtoMessage() {}

func (x *ListTypeDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypeDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListTypeDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{6}
}

func (x *ListTypeDefinitionsRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListTypeDefinitionsRequest) GetLatestVersion() bool {
	if x != nil {
		return x.LatestVersion
	}
	return false
}

func (x *ListTypeDefinitionsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// ListTypeDefinitionsResponse represents a response to list type definitions
type ListTypeDefinitionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TypeDefinitions []*TypeDefinition      `protobuf:"bytes,1,rep,name=type_definitions,json=typeDefinitions,proto3" json:"type_definitions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTypeDefinitionsResponse) Reset() {
	*x = ListTypeDefinitionsResponse{}
	mi := &file_api_connect_type_definition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypeDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypeDefinitionsResponse) ProtoMessage() {}

func (x *ListTypeDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_type_definition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypeDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListTypeDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_api_connect_type_definition_proto_rawDescGZIP(), []int{7}
}

func (x *ListTypeDefinitionsResponse) GetTypeDefinitions() []*TypeDefinition {
	if x != nil {
		return x.TypeDefinitions
	}
	return nil
}

var File_api_connect_type_definition_proto protoreflect.FileDescriptor

const file_api_connect_type_definition_proto_rawDesc = "" +
	"\n" +
	"!api/connect/type_definition.proto\x12\tflexitype\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa3\x02\n" +
	"\x0eTypeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\varchived_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\"Q\n" +
	"\x12TypeDefinitionList\x12;\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x19.flexitype.TypeDefinitionR\vdefinitions\"S\n" +
	"\x1bCreateTypeDefinitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"}\n" +
	"\x1bUpdateTypeDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"*\n" +
	"\x18GetTypeDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x1cArchiveTypeDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x1aListTypeDefinitionsRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\bR\rlatestVersion\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"c\n" +
	"\x1bListTypeDefinitionsResponse\x12D\n" +
	"\x10type_definitions\x18\x01 \x03(\v2\x19.flexitype.TypeDefinitionR\x0ftypeDefinitions2\xec\x03\n" +
	"\x15TypeDefinitionService\x12[\n" +
	"\x14CreateTypeDefinition\x12&.flexitype.CreateTypeDefinitionRequest\x1a\x19.flexitype.TypeDefinition\"\x00\x12[\n" +
	"\x14UpdateTypeDefinition\x12&.flexitype.UpdateTypeDefinitionRequest\x1a\x19.flexitype.TypeDefinition\"\x00\x12U\n" +
	"\x11GetTypeDefinition\x12#.flexitype.GetTypeDefinitionRequest\x1a\x19.flexitype.TypeDefinition\"\x00\x12Z\n" +
	"\x15ArchiveTypeDefinition\x12'.flexitype.ArchiveTypeDefinitionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12f\n" +
	"\x13ListTypeDefinitions\x12%.flexitype.ListTypeDefinitionsRequest\x1a&.flexitype.ListTypeDefinitionsResponse\"\x00B8Z6github.com/zkrebbekx/flexitype/internal/api/connect/pbb\x06proto3"

var (
	file_api_connect_type_definition_proto_rawDescOnce sync.Once
	file_api_connect_type_definition_proto_rawDescData []byte
)

func file_api_connect_type_definition_proto_rawDescGZIP() []byte {
	file_api_connect_type_definition_proto_rawDescOnce.Do(func() {
		file_api_connect_type_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_connect_type_definition_proto_rawDesc), len(file_api_connect_type_definition_proto_rawDesc)))
	})
	return file_api_connect_type_definition_proto_rawDescData
}

var file_api_connect_type_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_connect_type_definition_proto_goTypes = []any{
	(*TypeDefinition)(nil),               // 0: flexitype.TypeDefinition
	(*TypeDefinitionList)(nil),           // 1: flexitype.TypeDefinitionList
	(*CreateTypeDefinitionRequest)(nil),  // 2: flexitype.CreateTypeDefinitionRequest
	(*UpdateTypeDefinitionRequest)(nil),  // 3: flexitype.UpdateTypeDefinitionRequest
	(*GetTypeDefinitionRequest)(nil),     // 4: flexitype.GetTypeDefinitionRequest
	(*ArchiveTypeDefinitionRequest)(nil), // 5: flexitype.ArchiveTypeDefinitionRequest
	(*ListTypeDefinitionsRequest)(nil),   // 6: flexitype.ListTypeDefinitionsRequest
	(*ListTypeDefinitionsResponse)(nil),  // 7: flexitype.ListTypeDefinitionsResponse
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 9: google.protobuf.Empty
}
var file_api_connect_type_definition_proto_depIdxs = []int32{
	8,  // 0: flexitype.TypeDefinition.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: flexitype.TypeDefinition.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 2: flexitype.TypeDefinition.archived_at:type_name -> google.protobuf.Timestamp
	0,  // 3: flexitype.TypeDefinitionList.definitions:type_name -> flexitype.TypeDefinition
	0,  // 4: flexitype.ListTypeDefinitionsResponse.type_definitions:type_name -> flexitype.TypeDefinition
	2,  // 5: flexitype.TypeDefinitionService.CreateTypeDefinition:input_type -> flexitype.CreateTypeDefinitionRequest
	3,  // 6: flexitype.TypeDefinitionService.UpdateTypeDefinition:input_type -> flexitype.UpdateTypeDefinitionRequest
	4,  // 7: flexitype.TypeDefinitionService.GetTypeDefinition:input_type -> flexitype.GetTypeDefinitionRequest
	5,  // 8: flexitype.TypeDefinitionService.ArchiveTypeDefinition:input_type -> flexitype.ArchiveTypeDefinitionRequest
	6,  // 9: flexitype.TypeDefinitionService.ListTypeDefinitions:input_type -> flexitype.ListTypeDefinitionsRequest
	0,  // 10: flexitype.TypeDefinitionService.CreateTypeDefinition:output_type -> flexitype.TypeDefinition
	0,  // 11: flexitype.TypeDefinitionService.UpdateTypeDefinition:output_type -> flexitype.TypeDefinition
	0,  // 12: flexitype.TypeDefinitionService.GetTypeDefinition:output_type -> flexitype.TypeDefinition
	9,  // 13: flexitype.TypeDefinitionService.ArchiveTypeDefinition:output_type -> google.protobuf.Empty
	7,  // 14: flexitype.TypeDefinitionService.ListTypeDefinitions:output_type -> flexitype.ListTypeDefinitionsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_connect_type_definition_proto_init() }
func file_api_connect_type_definition_proto_init() {
	if File_api_connect_type_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_connect_type_definition_proto_rawDesc), len(file_api_connect_type_definition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_connect_type_definition_proto_goTypes,
		DependencyIndexes: file_api_connect_type_definition_proto_depIdxs,
		MessageInfos:      file_api_connect_type_definition_proto_msgTypes,
	}.Build()
	File_api_connect_type_definition_proto = out.File
	file_api_connect_type_definition_proto_goTypes = nil
	file_api_connect_type_definition_proto_depIdxs = nil
}
