// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/connect/type_definition.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TypeDefinitionService_CreateTypeDefinition_FullMethodName  = "/flexitype.TypeDefinitionService/CreateTypeDefinition"
	TypeDefinitionService_UpdateTypeDefinition_FullMethodName  = "/flexitype.TypeDefinitionService/UpdateTypeDefinition"
	TypeDefinitionService_GetTypeDefinition_FullMethodName     = "/flexitype.TypeDefinitionService/GetTypeDefinition"
	TypeDefinitionService_ArchiveTypeDefinition_FullMethodName = "/flexitype.TypeDefinitionService/ArchiveTypeDefinition"
	TypeDefinitionService_ListTypeDefinitions_FullMethodName   = "/flexitype.TypeDefinitionService/ListTypeDefinitions"
)

// TypeDefinitionServiceClient is the client API for TypeDefinitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TypeDefinitionService provides operations for managing type definitions
type TypeDefinitionServiceClient interface {
	// CreateTypeDefinition creates a new type definition
	CreateTypeDefinition(ctx context.Context, in *CreateTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error)
	// UpdateTypeDefinition updates an existing type definition
	UpdateTypeDefinition(ctx context.Context, in *UpdateTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error)
	// GetTypeDefinition retrieves a type definition by ID
	GetTypeDefinition(ctx context.Context, in *GetTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error)
	// ArchiveTypeDefinition archives a type definition
	ArchiveTypeDefinition(ctx context.Context, in *ArchiveTypeDefinitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListTypeDefinitions lists type definitions based on filter criteria
	ListTypeDefinitions(ctx context.Context, in *ListTypeDefinitionsRequest, opts ...grpc.CallOption) (*ListTypeDefinitionsResponse, error)
}

type typeDefinitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTypeDefinitionServiceClient(cc grpc.ClientConnInterface) TypeDefinitionServiceClient {
	return &typeDefinitionServiceClient{cc}
}

func (c *typeDefinitionServiceClient) CreateTypeDefinition(ctx context.Context, in *CreateTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, TypeDefinitionService_CreateTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeDefinitionServiceClient) UpdateTypeDefinition(ctx context.Context, in *UpdateTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, TypeDefinitionService_UpdateTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeDefinitionServiceClient) GetTypeDefinition(ctx context.Context, in *GetTypeDefinitionRequest, opts ...grpc.CallOption) (*TypeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeDefinition)
	err := c.cc.Invoke(ctx, TypeDefinitionService_GetTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeDefinitionServiceClient) ArchiveTypeDefinition(ctx context.Context, in *ArchiveTypeDefinitionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TypeDefinitionService_ArchiveTypeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *typeDefinitionServiceClient) ListTypeDefinitions(ctx context.Context, in *ListTypeDefinitionsRequest, opts ...grpc.CallOption) (*ListTypeDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTypeDefinitionsResponse)
	err := c.cc.Invoke(ctx, TypeDefinitionService_ListTypeDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypeDefinitionServiceServer is the server API for TypeDefinitionService service.
// All implementations must embed UnimplementedTypeDefinitionServiceServer
// for forward compatibility.
//
// TypeDefinitionService provides operations for managing type definitions
type TypeDefinitionServiceServer interface {
	// CreateTypeDefinition creates a new type definition
	CreateTypeDefinition(context.Context, *CreateTypeDefinitionRequest) (*TypeDefinition, error)
	// UpdateTypeDefinition updates an existing type definition
	UpdateTypeDefinition(context.Context, *UpdateTypeDefinitionRequest) (*TypeDefinition, error)
	// GetTypeDefinition retrieves a type definition by ID
	GetTypeDefinition(context.Context, *GetTypeDefinitionRequest) (*TypeDefinition, error)
	// ArchiveTypeDefinition archives a type definition
	ArchiveTypeDefinition(context.Context, *ArchiveTypeDefinitionRequest) (*emptypb.Empty, error)
	// ListTypeDefinitions lists type definitions based on filter criteria
	ListTypeDefinitions(context.Context, *ListTypeDefinitionsRequest) (*ListTypeDefinitionsResponse, error)
	mustEmbedUnimplementedTypeDefinitionServiceServer()
}

// UnimplementedTypeDefinitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTypeDefinitionServiceServer struct{}

func (UnimplementedTypeDefinitionServiceServer) CreateTypeDefinition(context.Context, *CreateTypeDefinitionRequest) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTypeDefinition not implemented")
}
func (UnimplementedTypeDefinitionServiceServer) UpdateTypeDefinition(context.Context, *UpdateTypeDefinitionRequest) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTypeDefinition not implemented")
}
func (UnimplementedTypeDefinitionServiceServer) GetTypeDefinition(context.Context, *GetTypeDefinitionRequest) (*TypeDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTypeDefinition not implemented")
}
func (UnimplementedTypeDefinitionServiceServer) ArchiveTypeDefinition(context.Context, *ArchiveTypeDefinitionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveTypeDefinition not implemented")
}
func (UnimplementedTypeDefinitionServiceServer) ListTypeDefinitions(context.Context, *ListTypeDefinitionsRequest) (*ListTypeDefinitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTypeDefinitions not implemented")
}
func (UnimplementedTypeDefinitionServiceServer) mustEmbedUnimplementedTypeDefinitionServiceServer() {}
func (UnimplementedTypeDefinitionServiceServer) testEmbeddedByValue()                               {}

// UnsafeTypeDefinitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypeDefinitionServiceServer will
// result in compilation errors.
type UnsafeTypeDefinitionServiceServer interface {
	mustEmbedUnimplementedTypeDefinitionServiceServer()
}

func RegisterTypeDefinitionServiceServer(s grpc.ServiceRegistrar, srv TypeDefinitionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTypeDefinitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TypeDefinitionService_ServiceDesc, srv)
}

func _TypeDefinitionService_CreateTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDefinitionServiceServer).CreateTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeDefinitionService_CreateTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDefinitionServiceServer).CreateTypeDefinition(ctx, req.(*CreateTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeDefinitionService_UpdateTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDefinitionServiceServer).UpdateTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeDefinitionService_UpdateTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDefinitionServiceServer).UpdateTypeDefinition(ctx, req.(*UpdateTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeDefinitionService_GetTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDefinitionServiceServer).GetTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeDefinitionService_GetTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDefinitionServiceServer).GetTypeDefinition(ctx, req.(*GetTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeDefinitionService_ArchiveTypeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveTypeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDefinitionServiceServer).ArchiveTypeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeDefinitionService_ArchiveTypeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDefinitionServiceServer).ArchiveTypeDefinition(ctx, req.(*ArchiveTypeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TypeDefinitionService_ListTypeDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTypeDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeDefinitionServiceServer).ListTypeDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeDefinitionService_ListTypeDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeDefinitionServiceServer).ListTypeDefinitions(ctx, req.(*ListTypeDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TypeDefinitionService_ServiceDesc is the grpc.ServiceDesc for TypeDefinitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypeDefinitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexitype.TypeDefinitionService",
	HandlerType: (*TypeDefinitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTypeDefinition",
			Handler:    _TypeDefinitionService_CreateTypeDefinition_Handler,
		},
		{
			MethodName: "UpdateTypeDefinition",
			Handler:    _TypeDefinitionService_UpdateTypeDefinition_Handler,
		},
		{
			MethodName: "GetTypeDefinition",
			Handler:    _TypeDefinitionService_GetTypeDefinition_Handler,
		},
		{
			MethodName: "ArchiveTypeDefinition",
			Handler:    _TypeDefinitionService_ArchiveTypeDefinition_Handler,
		},
		{
			MethodName: "ListTypeDefinitions",
			Handler:    _TypeDefinitionService_ListTypeDefinitions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/connect/type_definition.proto",
}
